### ISSUE TITLE
Provide PricingModel for AWS

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/autoscaler#131]
Follow up of #82 

cc: @mumoshu

**Comment by mrcrgl** [comment]
We're interested in this feature. Are contributions welcome?

**Comment by mwielgus** [comment]
@mrcrgl Absolutely, please send us a PR.

**Comment by mrcrgl** [comment]
@mwielgus Ok. I'll start on it. Is it fine for you guys to evaluate the spot prices on demand via the spot price history api? I also tend to load the price list on demand as well (with caching).

**Comment by kylegato** [comment]
@mrcrgl It looks like some of the work for the on-demand pricing was started here: 

https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/ec2_instance_types/gen.go

Because pricing can be dependent on your region and account features, this seems to cover some of that, but it needs to be fixed to work with the current API response formats.

Support for detecting the GPU field and instance types would also be nice for that.

I think getting the spot prices from the spot price history API makes perfect sense.

**Comment by mrcrgl** [comment]
I've worked on it. I'll test these feature within the next few days on one of our clusters. 
Does this change work for you guys?

**Comment by mrcrgl** [comment]
@mwielgus PTAL https://github.com/kubernetes/autoscaler/pull/486

**Comment by patrickf55places** [comment]
The `lifecycle/rotten` label should be removed; the PR is still active.

**Comment by kesor** [comment]
@mwielgus @mumoshu can you reopen this? or if this has been implemented, link the issue that has this merged?
