### ISSUE TITLE
GPU node should only calculate gpu utilization

### ISSUE THREAD

**Issue by ringtail** [kubernetes/autoscaler#1367]
GPU instance is quite different from other instance. It's much more expansive and not sensitive to cpu or memory. If this instance has GPU,Should we have different utilization formula for it. 

```
I1031 20:38:32.303631   31733 scale_down.go:407] Node cn-shenzhen.i-wz9ex1vq9wpu4sxvyy8o - utilization 0.600000
I1031 20:38:32.303670   31733 scale_down.go:411] Node cn-shenzhen.i-wz9ex1vq9wpu4sxvyy8o is not suitable for removal - utilization too big (0.600000)
I1031 20:38:32.303694   31733 scale_down.go:407] Node cn-shenzhen.i-wz91n8ywxxvcmqa2jxxh - utilization 0.600000
I1031 20:38:32.303711   31733 scale_down.go:411] Node cn-shenzhen.i-wz91n8ywxxvcmqa2jxxh is not suitable for removal - utilization too big (0.600000)
```
Here is a 2C8G1GPU instance and  nvidia-device-plugin will request at least 1 core so this instance can't scale down forever even no one use this GPU.

**Comment by MaciekPytel** [comment]
+1 sounds like a good improvement. If you're willing to implement I'm happy to review, otherwise I can add it to my backlog, but it will probably take a while before I get to it.

**Comment by Jeffwan** [comment]
@MaciekPytel  I can help look at this issue and submit a patch.

**Comment by pierreozoux** [comment]
I'm interested in this features as well.
From what I read here, there is no request/limit on the Nvidia pod 
https://github.com/NVIDIA/k8s-device-plugin/blob/v1.11/nvidia-device-plugin.yml
If the add-on doesnt request 1 core, and as it is a deamon set, I think CA should work as expected? Am I right?
If not, I guess the CA for scaledown, should ignore add on and deamon sets.

What do you think about this idea? Did you workaround it for you?

**Comment by Jeffwan** [comment]
@pierreozoux  Right. Daemonset is not a blocker for CA to remove nodes.  The problem here is GPU Node speciality or GPU utilization is not considered when CA make scale down decision.

**Comment by seh** [comment]
@Jeffwan, that's a different complaint than what @ringtail mentioned originally. That problem was that the GPUs were idle, but there was (ignorable) CPU being used by the device plugin.

Having said, that, though, I agree with you; I _think_—but have not yet been able to confirm—that the autoscaler is shutting down our GPU nodes due to low CPU reservation. The events I expect to see posted confirming this aren't there, though, so it's hard to tell when the autoscaler is responsible versus when AWS EC2 is responsible.

**Comment by seh** [comment]
I've confirmed now that the autoscaler is evicting pods due to low CPU and memory utilization, even though these are GPU-dependent pods. They use the lone GPU on the machine, but don't require much memory or CPU, at least as expressed in the resource requests.

Do we need to artificially inflate these requests in order to allow these pods to keep the node alive, even though they _are_ using the GPU?

**Comment by Jeffwan** [comment]
@seh Yeah. GPU is kind of special because they have different use case for training and serving. 
For training workloads, pods don't like to be interrupted as it may has impact on entire training job. 
But serving/inference workloads are movable. They don't mind to be binpacked to other available nodes. 

I am working on a basic proposal to address GPU related issues and publish it next week. Hope I can also finish code change part. I will let you know after New Year.

**Comment by seh** [comment]
I see the difference; thank you for bringing that up. In our case, these are the former: training workloads.

I look forward to your proposal. In the meantime, we'll find a way to work around the utilization threshold, which we'd rather not adjust for our non-GPU-bearing nodes.

**Comment by MaciekPytel** [comment]
If you don't want your workload moved just don't allow CA to move it. You can use safe-to-evict: false annotation (https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node) or a PDB. CA will never remove a node with such a pod, regardless of utilization.

The issue here, as I see it, is CA will not remove a node with GPU if it has a CPU utilization >50%, even if no GPU is used. Given the relative price of CPU/GPU this is silly.
The simplest fix is to make https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/simulator/cluster.go#L155 calculate gpu utilization and, if present, ignore CPU and memory utilization.

**Comment by seh** [comment]
I assume that calculating GPU utilization will require some interaction with vendor-specific utilities such as _nvidia-smi_. At present, as you pointed out, even the CPU utilization isn't measured by actual use, but rather merely by [how much the pod requested](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/simulator/cluster.go#L186-L188). Are you considering calculating GPU utilization the same way? That is, if I ask for one GPU and the machine has one GPU, then I'm using 100% of the GPU resources on the machine?

**Comment by MaciekPytel** [comment]
>That is, if I ask for one GPU and the machine has one GPU, then I'm using 100% of the GPU resources on the machine?

Exactly. 

> At present, as you pointed out, even the CPU utilization isn't measured by actual use

This is by design. Cluster Autoscaler's is based around scheduling and making sure every pod in cluster is schedulable. Kubernetes scheduling only cares about resource requests, not actual usage. And therefore so does CA.
If you want to autoscale based on real usage metrics you must use HPA or VPA to update your pods based on usage. CA will react to those changes and provide nodes as needed.

**Comment by Jeffwan** [comment]
@ringtail I think we can close this issue? Now we have a threshold and corresponding logic to handle the case.

**Comment by ringtail** [comment]
@Jeffwan Cool!
