### ISSUE TITLE
Switch to github.com/pkg/errors

### ISSUE THREAD

**Issue by Rajat-0** [kubernetes/autoscaler#1371]
Currently Autoscaler is using fmt.Errorf both for wrapping errors and for creating new errors, but there is a general consensus on moving toward github.com/pkg/errors.

Ref:
https://github.com/kubernetes/kubeadm/issues/1183#issue-372862070
https://github.com/kubernetes/kubernetes/pull/70271#issue-225967737

If Owner/Approver agrees  to this I would like to work on it.

**Comment by aleksandra-malinowska** [comment]
cc @MaciekPytel

**Comment by MaciekPytel** [comment]
I agree fmt.Errorf() is pretty bad, which is why we already have our own custom error type: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/utils/errors/errors.go. The wrapping it does is simpler than what pkg/errors seem to do, but we haven't needed more complex wrapping so far. What we do need is to categorize errors into a few high-level types, which doesn't seem to be supported by pkg/errors.

All top-level functions (generally stuff in cluster-autoscaler/core/) were migrated to use AutoscalerError a year or so ago and we use it in any new functions we add. We haven't migrated our pre-existing helper/inner functions, because:
1. It's a ton of work. As I said we mainly need AutoscalerError to categorize errors and migrating a function requires manually assigning type to each possible error. We decided to approximate by wrapping errors from internal functions based on what the function does. It's not 100% accurate, but so far it seems to work well enough.
2. We don't want to change cloudprovider. There are a lot of implementations and forks owned by different people and we try to limit changes to the interface as much as we can.

Given the above I'd rather not introduce third type of errors. If we need more advanced wrapping (why?) let's add it to AutoscalerError.

**Comment by Rajat-0** [comment]
@MaciekPytel thanks for the explaination.
