### ISSUE TITLE
Too much unneeded Scale up and scale down in CA

### ISSUE THREAD

**Issue by lvjing2** [kubernetes/autoscaler#1471]
Hi all, is cluster autoscaling safe to be used for production?  when I through the cluster-autoscaler repo, I found this maybe a problem for production. The case is that 
1. when we set the min/max range of resource utilization to 60%-80% for a NodeGroup which contains 3 node with each usage 80%, 80%, 40%. 
2. Then the third one is blow the min, so it will be delete, and all the pod will be migrate to the other two nodes. So the utilization of other node will reached  100% which is bigger than the max. 
3. Then the CA will start to scale up a new node. 

In this case, there need to one scale up and one scale down. But from my point, it is better if there should is no scale up and no scale down.

**Comment by seeruk** [comment]
I'm experiencing something like this now. I have a cluster running in EKS. My nodes are running in an ASG using the Cloudformation stack provided by Amazon, this doesn't enable any scaling policies on the ASG, so I believe the only thing controlling whether the desired capacity of the ASG changes is the CA.

My cluster currently never has nodes that are older than about 15 minutes, because it's stuck in a cycle of bringing nodes up and down all of the time, bouncing between having 2 nodes and 3 nodes. I'm not actually doing anything on the cluster. No traffic is going to the cluster either, it's just sitting there without any user interaction during this process.

Here's what my current node selection looks like:

```
$ kubectl get nodes
NAME                                         STATUS   ROLES    AGE   VERSION
ip-172-29-3-9.eu-west-1.compute.internal     Ready    <none>   10m   v1.11.5
ip-172-29-4-63.eu-west-1.compute.internal    Ready    <none>   14m   v1.11.5
ip-172-29-5-239.eu-west-1.compute.internal   Ready    <none>   5m    v1.11.5
```

Just after pasting that, I've lost one of those instances, and now am left with this:

```
$ kubectl get nodes
NAME                                         STATUS   ROLES    AGE   VERSION
ip-172-29-3-9.eu-west-1.compute.internal     Ready    <none>   10m   v1.11.5
ip-172-29-5-239.eu-west-1.compute.internal   Ready    <none>   6m    v1.11.5
```

I've looked through the FAQ and have seen the list of reasons why a pod might prevent a node from being removed, and seen that adding the annotation `"cluster-autoscaler.kubernetes.io/safe-to-evict": "false"` should prevent a node with a pod on it that has that annotation from being removed. So, I applied this annotation to the CA pod:

```
$ kubectl describe pods -n kube-system -l app=aws-cluster-autoscaler
Name:               cluster-autoscaler-aws-cluster-autoscaler-5ddd4fd945-l2vnb
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               ip-172-29-5-239.eu-west-1.compute.internal/172.29.5.239
Start Time:         Fri, 18 Jan 2019 15:54:31 +0000
Labels:             app=aws-cluster-autoscaler
                    pod-template-hash=1888098501
                    release=cluster-autoscaler
Annotations:        cluster-autoscaler.kubernetes.io/safe-to-evict: false
Status:             Running
...
```

The node that this pod is on still ends up being removed eventually as it cycles through the nodes. 

This how I installed CA on my cluster:

```
$ helm upgrade cluster-autoscaler "stable/cluster-autoscaler" \
  --set "autoDiscovery.clusterName=icelolly-${env}" \
  --set "awsRegion=eu-west-1" \
  --set "cloudProvider=aws" \
  --set "image.tag=v1.3.5" \
  --set "rbac.create=true" \
  --set "sslCertPath=/etc/kubernetes/pki/ca.crt" \
  --values "${script_dir}/cluster-autoscaler/values.yaml" \
  --version "${cluster_autoscaler_chart_version}" \
  --wait --install --namespace kube-system >> "${log_file}" 2>&1
```

Here is values.yaml:

```
podAnnotations:
  cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
```

Here's a bunch of logs from one lifetime of the CA: https://gist.github.com/seeruk/63b338bd13535c987010892332e0755a

Happy to give any more information where possible.

**Comment by aleksandra-malinowska** [comment]
Can you check events with `$ kubectl get events | grep cluster-autoscaler`? This should give you information about recent (less than 1 hour ago) scale down activity. If Cluster Autoscaler removed a node, there should be an event for it. You can also verify it looking for the node's name in logs (if they're exported somewhere before the instance is lost).

In general, it's unlikely that autoscaler would remove a pod where it is running. Unless a PDB exists that explicitly allow it, it will not try to evict pods running in kube-system namespace.

**Comment by aleksandra-malinowska** [comment]
This message sounds as if the group was set to keep the number of instances constant (presumably at 2). So whenever Cluster Autoscaler adds a node (as indicated by events), ASG would terminate one of the instances.

If I understand correctly, the way to configure the ASG is to disable autoscaling activity, but leave minimum/maximum limits such that autoscaler can do its job. Can't advise how to do it precisely, since I don't use AWS.

**Comment by seeruk** [comment]
Hmm, from what I understand you have the min, max, and desired capacity, and the cluster autoscaler works by updating that desired capacity. This part is working fine at the moment.

After some investigation, I'm beginning to wonder if it could be the ELB that's pointing at Istio Ingress Gateway's health check, as right now it's saying that the instance it's pointing at is unhealth (despite it being healthy). Perhaps that is trigger the current node that's pointed at to shut down after some set amount of time. I'll update when I do find the solution, but I'm pretty sure it's nothing to do with the cluster autoscaler now.

**Comment by seeruk** [comment]
Found the problem. Another developer in our team has been using the same infrastructure code to spin up a K8s cluster, and had forgotten to update a variable. So it turns out the cluster autoscaler in his cluster was set to scale the ASG in my region. This left the two cluster autoscalers to battle against each other, one shutting down nodes it deemed unnecessary, the other bringing back nodes to allocate pods.

Cloudtrails highlighted the issue, as we could see the termination events there that had been sent to the AWS API, and from that could see the instance that was triggering the termination. I knew he was working in another region, and found that instance there.

**Comment by Jeffwan** [comment]
Sounds good. @seeruk  
1. I notice lots of AWS users are confused about min/max/desired setting in CA.  I would suggest to auto discovery and adjust values directly on ASG. 
2. Have role policy is great, or you can use different cluster tag in CA node group auto discovery. 

https://github.com/kubernetes/autoscaler/blob/c79cbff1638e0ca10be66bbe62e891329bdcf31d/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml#L140

**Comment by seeruk** [comment]
Hi @Jeffwan 

We're currently using the auto-discovery with those tags, the other developer had just left the `awsRegion` value in the Helm chart pointing at the region my cluster was in. The name of the cluster he'd made was the same as mine, just in a different region, so his CA ended up looking at the ASG in my region via the auto-discovery.

I've limited the policy we create so that the role the nodes receive only gets the required permissions for resources in the same region that the cluster is in.

**Comment by altdelnow** [comment]
We are consistently facing issue of 503 connection time out during POD scale up/down. We are using Istio 1.18.5 and EKS 1.25.
I have gone through the complete thread and it appears except for retry policy, there is no other alternative. Please let me know if someone has better solution other then retry option. Its bit critical
