### ISSUE TITLE
Failed to decrease agentpool

### ISSUE THREAD

**Issue by hadr10** [kubernetes/autoscaler#1513]
Hi,

we had got issue with autoscaler on AKS. 
AKS version: 1.11.3 (with RBAC)
Autoscaler version: 1.3.1

error message:
E1217 13:31:34.867548       1 static_autoscaler.go:190] Failed to fix node group sizes: Failed to decrease agentpool: attempt to delete existing nodes targetSize:3 delta:-1 existingNodes: 3 

After deleting pod on AKS, the new one autoscaler was created and scale up started working.

Thank you,
Honza

**Comment by rachelvwood** [comment]
/reopen I'm seeing this on AKS as well.

AKS version: 1.13.7
Autoscaler version: 1.13.6

1 utils.go:483] Decreasing size of <vmss name>, expected=27 current=26 delta=-1
1 static_autoscaler.go:223] Failed to fix node group sizes: Failed to decrease <vmss-name>: attempt to delete existing nodes targetSize:27 delta:-1 existingNodes: 27

Based on my reading of the code, this happens when the number of nodes from "kubectl get nodes" disagrees with the number of nodes from the vmss api call.  One of our nodes is cordoned.  Could that cause this issue?
