### ISSUE TITLE
Run e2e tests during CI

### ISSUE THREAD

**Issue by petr-k** [kubernetes/autoscaler#1535]
End-to-end tests do not seem to be run during CI. I think it would be beneficial to put up the necessary plumbing to allow tests to be run in Travis. Also, autoscaling components could be tested against multiple Kubernetes versions (if that makes sense?).

[kubeadm-dind-cluster](https://github.com/kubernetes-sigs/kubeadm-dind-cluster)  or [kind](https://github.com/kubernetes-sigs/kind) could be used to spin up the testing cluster.

**Comment by bskiba** [comment]
We have continuously running e2e tests here: https://k8s-testgrid.appspot.com/sig-autoscaling-cluster-autoscaler 
Config lives here: https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-autoscaling/sig-autoscaling-config.yaml
Cluster Autoscaler is tested against multiple versions of Kubernetes, since it depends on Kubernetes scheduler code. I guess we could have a similar setup for VPA if we find it is needed. 
We use [prow](https://github.com/kubernetes/test-infra/tree/master/prow) to spin up test clusters and run tests - same as k8s.

e2e tests are looong. For Cluster Autoscaler they run on the order of hours and cannot be parallelized on a single cluster. From what I've seen most failures of tests (especially for CA) come rather from changes in Kubernetes, not in autoscaling code.
I don't see us running e2e tests on each PR, but others may disagree @MaciekPytel @mwielgus

**Comment by forkbomber** [comment]
Slightly related to this issue:

Is it possible to locate docker images build off PRs branches and/or master branch somewhere?
Official repository contains only release branch:
```
curl -s https://k8s.gcr.io/v2/vpa-recommender/tags/list | jq '.tags[]'
"0.2.0"
"0.3.0"
"0.3.1"
"0.4.0"
"v0.1.0"
```

and I wasn't able to locate scripts pushing release images anywhere.
