### ISSUE TITLE
is there any Doc on how to create a customized cloud provider?

### ISSUE THREAD

**Issue by immarvin** [kubernetes/autoscaler#1619]
I tried to search any tutorials or Doc on "how to create a customized cloud provider?" in google, the autoscaler Docs and K8S Docs, but got nothing.

How can I create a customized cloud provider? is there any material on this?   

thanks

**Comment by MaciekPytel** [comment]
I don't think such tutorial exists. In general you need to implement interfaces defined in https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/cloud_provider.go. 
Any method with comment saying 'Implementation optional' can just return ErrNotImplemented. I believe most cloudproviders are created by using one of existing implementations as an inspiration. Unfortunately this is quite a bit of work, existing cloudproviders consist of 3k+ LOC.

If you do try to implement it you're likely to find another can of worms if/when you try to add or change any dependencies. CA imports Kubernetes internals and Kubernetes is really not designed for that - so godeps don't really work. We have an evil, evil workaround described in https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-update-ca-dependencies-particularly-k8siokubernetes.

**Comment by aleksandra-malinowska** [comment]
There's no tutorial as such, I previously described some starting points in https://github.com/kubernetes/autoscaler/issues/953#issuecomment-396583127

**Comment by immarvin** [comment]
hi @MaciekPytel @aleksandra-malinowska , thanks a lot for your explanation, the information is quite helpful, I will try to start the work from the points you mentioned.

Let me give a brief introduction of what we want to do: Our project(http://xcat.org) is a bare metal cluster management tool focus on High-Performance-Computing, currently we are trying to run the HPC stack in K8S on bare-metal cluster.  We are considering to leverage CA to enable xCAT to provision or remove the bare metal work nodes. Do you any comments on this?

I have another question: currently, most public cloud provider or on-prem cluster management tools have provided Infra-as-Code interface with Terraform, does CA has any plan or project under incubation to enable Terraform to autoscale the cluster? 

thanks

**Comment by MaciekPytel** [comment]
For the case of bare metal I think it's worth to explicitly mention that CA is based around a concept of NodeGroup - a resizable set of identical machines. Core CA logic scales up by setting a desired size of NodeGroup, it doesn't create individual VMs. This comes from various implementations of such groups in cloud (ASG on AWS, MIG on GCP, VMSS on Azure, etc). 
In bare metal world you may need to implement your cloudprovider so that it groups identical VMs into a NodeGroup and manages them behind the scenes.

**Comment by immarvin** [comment]
hi @aleksandra-malinowska , I mean `CA modifying Terraform config of the cluster to change number of nodes`

**Comment by immarvin** [comment]
hi @MaciekPytel , I go through the Doc of ASG@AWS, VMSS@Azure and Heat@Openstack, I think I get the NodeGroup concept in Cloud autoscaling. 

Seems most Public Cloud Providers provide their own implementation of Autoscaling feature, the workflow looks similar, like 
#1. define and create resource node group
#2. define the autoscaling policy
#3. enable LoadBalance on the node group
#4. enable the autoscaling


I have a question on this: does CA depend on the underlie autoscaling engine of public provider? or CA just leverage the capability to create node group and instances in node group? seems the features, like autoscaling policy, autoscaling engine, are duplicate with what CA does.

**Comment by aleksandra-malinowska** [comment]
> I have a question on this: does CA depend on the underlie autoscaling engine of public provider? or CA just leverage the capability to create node group and instances in node group? seems the features, like autoscaling policy, autoscaling engine, are duplicate with what CA does.

It just uses create/delete and in some cases templates provided by groups. It's strongly recommended to disable all cloud autoscaling functionality, the reason being that two autoscalers manipulating the same resources tend to chaotically break things.

The feature scope is duplicated, but the underlying algorithm has no overlap with typical VM autoscalers, which are usually not well suited for autoscaling Kubernetes nodes.

> I mean `CA modifying Terraform config of the cluster to change number of nodes`

So what you're looking for is probably something like 'Terraform' cloud provider module in CA. This may be tricky. Does modifying config alone allow you to delete a specific machine (NOT just reduce some number and let a random machine be killed)? If yes, there's a chance it could work, but it may still require reading some resources directly from cloud provider.

**Comment by immarvin** [comment]
hi @aleksandra-malinowska , your explanation and the methods in https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/cloud_provider.go make me much clear. 

thanks a lot.

I noticed that besides `cloud_provider.go`,  there are files like `node_group_discovery_options.go`, what are these `discovery` functions for?

**Comment by aleksandra-malinowska** [comment]
It can be impractical to have to restart autoscaler and change its flags every time a node group is added or removed to a cluster, so some cloud providers support automated discovery of node groups via e.g. matching instance group name or tags.

**Comment by Bessonov** [comment]
I think it make sense to reopen this issue until a such documentation exists.

**Comment by balleon** [comment]
@immarvin 
Did you found a way to autoscale on-premise Kubernetes cluster using cluster-autoscaler?
I have a similar case with an on-premise OpenStack cluster.

**Comment by immarvin** [comment]
> @immarvin
> Did you found a way to autoscale on-premise Kubernetes cluster using cluster-autoscaler?
> I have a similar case with an on-premise OpenStack cluster.

nope

**Comment by Bessonov** [comment]
@balleon @immarvin 

I'm on the same way, but for custom provisioning of VMs. It's not easy (especially for no-go folks), but it's not to hard. Although I'm not done yet - just PoC.

First thing first: until https://github.com/kubernetes/autoscaler/issues/3644 or https://github.com/kubernetes/autoscaler/pull/3140 are done/implemented I don't see any way to avoid go. Because of that I learn go and after years of TypeScript, Java, Python or even php I dislike it very much. But well, don't let stop you.

In my opinion the code isn't in great shape, which should be kept in mind:
1. You can't easily implement it out-of-tree (in own repo) like cloud-controller-manager. Therefore you have all providers in this repo. Just clone/fork it and get all bad things with it.
2. There is no abstraction and no reasonable utils. You can't just implement up/down/get nodes and be happy. You must implement everything from scratch. You can see it on all providers - every providers has own way of caching or management.

In core there are just two interfaces to implement:
- [CloudProvider](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/cloud_provider.go#L60)
- [NodeGroup](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/cloud_provider.go#L115)

Both are well documented, but sometimes it's hard to understand what is to do. I found this is a [good example](https://github.com/kubernetes/autoscaler/pull/3640) from beginner to beginners like me.

I found two parts are special: caching and manager. I've not implemented caching yet (one of next steps forme) and I don't found any value behind the manager (although all autoscalers use managers, I go without for now. We'll see).
