### ISSUE TITLE
cluster-autoscaler/aws: Unable to get instance type

### ISSUE THREAD

**Issue by koooge** [kubernetes/autoscaler#1647]
Hi there ✋ 
I tried to set new ASG's launch template option to "Combine purchase options and instances". But it failed to scale up due to the missing instance type. Isn't this option supported yet?

```
E0202 02:39:04.817953       1 utils.go:274] Unable to build proper template node for foo-bar: Unable to get instance type from launch config or launch template
E0202 02:39:04.817967       1 static_autoscaler.go:312] Failed to scale up: failed to build node infos for node groups: Unable to get instance type from launch config or launch template
```

https://aws.amazon.com/about-aws/whats-new/2018/11/scale-instances-across-purchase-options-in-a-single-ASG/?nc1=h_ls

**Comment by Jeffwan** [comment]
This is not supported yet. We need to consider price model for long time at this moment since the way fleet abstract is different from the nodegroup abstract in the past. 

Fleet support OnDemand/ Spot and different node flavors in one node group. Currenctly, ca use node group to differentiate node flavors.

Please track status on issue and probably just close this one. Thanks! 
https://github.com/aws/containers-roadmap/issues/144
https://github.com/kubernetes/autoscaler/issues/838

**Comment by bskiba** [comment]
Closing in favour of the issues mentioned by @Jeffwan. Thanks!
/close
