### ISSUE TITLE
Cluster-autoscaler minimum number for nodes

### ISSUE THREAD

**Issue by aerostitch** [kubernetes/autoscaler#1652]
Hi,

We're using the cluster-autoscaler 1.3.5 with k8s 1.11.6 on latest coreos in AWS.
During the night we have some jobs that do sudden spikes of cpu usage, which we handled in the past by setting the minimum size of the autoscaling group via the nodes flag: `--nodes=40:120:services-k8s-worker` as we are fine keeping some provisioning overhead.
We are on AWS and have been running k8s way before EKS so haven't switched to EKS yet.

Question 1:
Recently I noticed that the minimum size of our autoscaling group was way bellow the 40 nodes we set in the flags (it was set to 30 manually at some point and hasn't moved since then), so I'm wondering if setting it this way has been deprecated. (We've done the upgrade to k8s from 1.9 to 1.10 and then 1.11 over the last few months and upgrade the cluster-autoscaler too so not sure exactly when it stopped working).

Question 2:
I tried to set the `cores-total` flag to a minimum too `--cores-total=500:1920` but it doesn't seem to change anything on my cluster size. Wondering if that could be due to the fact that we're still using heapster (preparing to move to the metrics server soon but still not there yet).

Note that there's nothing in the logs that indicate an issue:
```
$ kubectl logs --namespace kube-system -l app=cluster-autoscaler
I0205 00:15:21.037178       1 leaderelection.go:185] attempting to acquire leader lease  kube-system/cluster-autoscaler...
I0205 00:15:36.996668       1 leaderelection.go:194] successfully acquired lease kube-system/cluster-autoscaler
W0205 17:39:27.344999       1 reflector.go:341] k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:149: watch of *v1.Pod ended with: too old resource version: 473097260 (473105247)
```

Thanks for your help,
Joseph

**Comment by aleksandra-malinowska** [comment]
Node group size limits are only applied to scale-up/scale-down. Cluster Autoscaler won't add or remove any nodes just to bring the value within range (it never did). So if the group went to 30 back when that was a minimum limit, it's WAI.

There was a bug some months back when due to race condition limits on AWS could be violated under some conditions, but 1.3.5 should have the fix for this.

Regarding --cores-total, it has nothing to do with actual utilization metrics, so heapster and metrics server don't matter here. Those limits are applied to a sum of nodes' capacity values. Like limits on node groups sizes, they're applied only during scale-up/scale-down. Reason for them to be added was that limits on node groups are independent of each others (i.e. if you're ok to have either 16 1-core machines or 4 4-core machines in the cluster, but not both at the same time, there was no way to express it.)

**Comment by aerostitch** [comment]
Right, that makes sense, there was a manual scale down recently right before we started to see some issues with the short burst.
Thanks for the reminder! :)
