### ISSUE TITLE
Ability to tag priorities to different ASG's for preferring particular array. 

### ISSUE THREAD

**Issue by garo** [kubernetes/autoscaler#1709]
I wish there would be a way to set priorities to different autoscaling groups so that the cluster-autoscaler would prefer to scale one group instead of another based on a pod's nodeSelector.

My use case is that I'm running batch loads which can use any worker node, but I want to mainly use cheap AWS Spot instances. The spot instances have a taint set so that only suitable workloads (pods that can be killed at any moment without affecting the whole batch operation) are scheduled there and my batch load has an appropriate toleration.

With an appropriate toleration and a nodeSelector I can force my pods to fit only to the spot instances and cluster-autoscaler will scale those up and this works. However what does not currently work is that I don't have any meaningful way to utilise free resources on my non-spot (permanent) worker nodes while still preventing cluster-autoscaler from spinning up permanent nodes instead of spot nodes.

**Comment by aleksandra-malinowska** [comment]
Sounds like a use-case for pricing expander (select the cheapest scale-up option). Right now it's only available for GCP, but there's a PR adding support for AWS that's been open for >year: #486. I'm not sure if it's being actively worked on.

**Comment by Jeffwan** [comment]
I am curious what's scale of on demand nodes? 

Let's assume if you have 3 node with utilization rate above 50% which can not be scaled down. You want your new created resource pack those 3 nodes first but scale up spot node group rather than on demand.

The resource you save is up to 50% * number of nodes. Have you considered to improve your scale-down-utilization-threshold may be to 90% and make sure not lots of idle resources in onDemand node group?

**Comment by Jeffwan** [comment]
I think improving threshold may not be very helpful. 
Utilization rate in CA comes from Math.max(cpu, memory). Which means the other resource maybe underutilized.

**Comment by Jeffwan** [comment]
#1801 priority expander has been added to 1.15 CA and feel free to have a try.  I will close this PR and feel free to reopen
