### ISSUE TITLE
Think about how to handle dedicated node groups

### ISSUE THREAD

**Issue by davidopp** [kubernetes/autoscaler#171]
The way we implement dedicated node groups in Kubernetes is 
1) attach a taint to one or more nodes (like `dedicated=foo`); pods that are *allowed* to use those nodes tolerate that taint
2) attach a label to the same set of nodes (like `dedicated=foo`; the key/value space of taints is separate from the key/value space of labels); pods that *must* use those nodes have node affinity or nodeSelector for that label (in addition to having the toleration from (1))

Say we have a pending pod that is supposed to run on a dedicated node. The node created for this pod must have the label (part (2) above). But it does not need to have the taint (part (1) above) since a pod with a toleration will just as well schedule onto a node with or without the corresponding taint. When CA sees such a pending pod, it should presumably create a node with both the label and taint, not just the label, but the logic today probably does not do this.

**Comment by MaciekPytel** [comment]
I'm not sure if I understand your issue correctly. Do you mean CA should put the taint on the new node that is added in scale-up? CA doesn't create new node, it just resizes the underlying node group (MIG, ASG, ...) and assumes that when the node group is resized a new node will show up and it will look like all the other nodes in a given node group. On GCP you can create your dedicated node group by adding a separate MIG and setting kube-env, so that new node spins up with both a given set of labels and taints (taint support has been added in 1.7 by @mwielgus kubernetes/kubernetes#47632).

If you create a dedicated MIG in that way cluster-autoscaler will take both 1 and 2 into account and only scale it up for pods that have the toleration. 

I'm not sure - does this answer your question? Or have I misunderstood and you mean something else?

**Comment by mwielgus** [comment]
The core requirement in CA is that all nodes inside a single node group (MIG, ASG, whatever) look more-or-less the same. Thus CA will not attach any extra, permanent labels or taints to the nodes. If the users want to put a pod on a particular node group they should configure taints/labels during the node group creation and again put the appropriate configuration inside of the pod. With the scale to 0 feature the group will go to 0 if there are no pods that can be executed on it.
