### ISSUE TITLE
Add scale up threshold instead of scaling up only when new pods already can't be run. For upfront scaling.

### ISSUE THREAD

**Issue by fog1985** [kubernetes/autoscaler#1714]
It seems to me a little bit illogical scaling up only when there are no resources for starting containers at all.
I didn't find any parameters for making this value E.G. 70% as for scaling down which is 50% by default.
Please correct me if I am wrong and we can tell `CA` to scale upfront and not only when there are no more resources. Which would be very useful for highly loaded production systems.

**Comment by aleksandra-malinowska** [comment]
What logic would you propose? If there are no pending pods, new nodes would be completely empty (literally; there's no load spreading in this case). Should autoscaler add them only to remove them after --scale-down-unneeded-time? Or should it stop removing empty nodes even if there's nothing running on them?

In other words, autoscaling _cluster_ is completely different from autoscaling _workload_, where you can count on new instances actually running something. That doesn't mean autoscaling in advance of anticipated need doesn't make sense, or that overprovisioning for pods that aren't yet there can't be done. However, for service workloads it's usually more reliable to overprovision those workloads (i.e. have more pods running than necessary by some margin), rather than keep around empty nodes for those pods to start. If you have multiple workloads or batch workloads with similar scheduling properties (affinity, selectors, tolerations and resource requests) and want to keep some shared spare resources for them, you can create [placeholder pods with low priority](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-configure-overprovisioning-with-cluster-autoscaler) to reserve resources.

**Comment by fog1985** [comment]
Thank you @aleksandra-malinowska for the prompt reply.
Actually, I went with the overprovisioning approach. To have some dummy podes with a lower priority so that they could be evicted when needed.
I have got 1 more question about `CA` downscaling. If you happen to know.
I have just had a cluster upscaling. Once load stabilized `CA` says that nodes utilization is 0.9+. Hence no nodes to scale down.
But in fact, CPU and MEMORY usage is not more than 30-40% of each node. There are 10+ nodes with CPU+MEMORY utilization of under30%.
It deleted only 1 node. 
I can't figure out what is actually telling `CA` the utilization is too high.

`CA` says:
```I0226 19:21:38.563960       1 scale_down.go:402] Node ip-10-12-85-104.ec2.internal - utilization 0.930000
I0226 19:21:38.563967       1 scale_down.go:406] Node ip-10-12-85-104.ec2.internal is not suitable for removal - utilization too big (0.930000)```
For all of these 35 nodes/workers.
But in fact there are: *2-5* `ht` pods per node.
`3 top loaded nodes per cpu usage:`
```tklym@Tarass-MacBook-Pro-2 test (DEVOPS-352) $ kubectl --context=prod.k8s.couchsurfing.com top nodes | sort -k3 -rn
ip-10-12-107-219.ec2.internal   1331m        33%    2825Mi          37%
ip-10-12-102-44.ec2.internal    1222m        30%    5501Mi          73%
ip-10-12-77-17.ec2.internal     609m         15%    3129Mi          41%```
`3 top loaded nodes per RAM usage:`
```tklym@Tarass-MacBook-Pro-2 test (DEVOPS-352) $ kubectl --context=prod.k8s.couchsurfing.com top nodes | sort -k5 -rn
ip-10-12-102-44.ec2.internal    945m         23%    5486Mi          72%
ip-10-12-46-103.ec2.internal    151m         7%     3830Mi          50%
ip-10-12-70-192.ec2.internal    103m         5%     3580Mi          47%```
So how come `Utilization is 0.9+ for CA`.

**Comment by MaciekPytel** [comment]
Cluster Autoscaler doesn't care about real resource usage. It's operates on pods' resource requests. The utilization in this case is `sum(requested_resources) / available_resources`. 

The reason for that is because that's how kubernetes scheduling works - CA's primary job is making sure every pod can schedule and actual resource usage doesn't matter for scheduling. To autoscale based on real usage you need to use CA and HPA together.

**Comment by fog1985** [comment]
Hm. So if I have let's say `requested resources` = `50% from resources of the instance` and `still available resources on the instance` = `50%` after pods have been provisioned, I will get `utilization = 1` (E.G. Fully utilized)? Even though I have half of the instance resources available and idle?
Please correct me if I am wrong in my assumptions.

**Comment by aleksandra-malinowska** [comment]
There may be some confusion regarding what "request" and "utilization" means in this context. Both Cluster Autoscaler and scheduler use values from container's `requests` field in pod `Spec` to make decisions. On the other hand, `kubectl top` will tell you how many resources are actually used, regardless of specified requests. In this case, you may be overprovisioning by putting a larger value in pod spec than the application uses.

**Comment by fog1985** [comment]
Got it. Thank you @aleksandra-malinowska for the clarification on this.
