### ISSUE TITLE
Continue operation if parsing some ASG fails

### ISSUE THREAD

**Issue by nielsole** [kubernetes/autoscaler#1728]
One of our ASGs uses mixed instance types and has 0 instances.

Expected Behaviour:
Autoscaler behaves like described in: https://github.com/kubernetes/autoscaler/issues/1647.
The autoscaler fails to parse the mixed ASG with
`Unable to build proper template node for {{ASG_NAME}}: Unable to get instance type from launch config or launch template`
 and continues with the existing others.

Actual Behaviour:
The autoscaler fails to parse the mixed ASG with
`Unable to build proper template node for {{ASG_NAME}}: Unable to get instance type from launch config or launch template` and stops processing ASGs with the following message:
`static_autoscaler.go:312] Failed to scale up: failed to build node infos for node groups: Unable to get instance type from launch config or launch template`

I just had to remove the ASG and everything was fine, but a single invalid ASG shouldn't incapacitate the Autoscaler IMO.

**Comment by nielsole** [comment]
This happens not only when there are 0 instances in an ASG but also if all nodes are cordoned in that ASG :/

**Comment by Jeffwan** [comment]
Yeah. As you know, Mixed instance type in one ASG are not supported. Maybe we can change to skip invalid ASG instead to prevent CA stop working. What do you think?

**Comment by nielsole** [comment]
sounds good.

**Comment by jsharpe** [comment]
/remove-lifecycle stale
I'm hitting this issue with one of my ASGs - at the very least processing should continue to scale up as this effectively disables autoscaling for the whole cluster.

**Comment by jsharpe** [comment]
@jaypipes I think I am still seeing this issue; the root cause I identified in my comment: https://github.com/kubernetes/autoscaler/pull/2248#issuecomment-520749665 in PR #2248 but this was merged without handling this case... I still think that the code should be robust against provider implementation errors though as turning off the autoscaling when an error starts occurring is a bad undesirable behaviour (and could be very costly!)

**Comment by jsharpe** [comment]
For the record its clusters create via kops that generates ASGs which fallback to the default version for the template and don't explicitly set it.

**Comment by jsharpe** [comment]
Yes, I'm currently running a fork with that setup and it seems to resolve the issue I was seeing. I think the issue is with the autoscaler as the aws sdk says that the version parameter field is optional and has a default of "$Default" which I take to mean that you should use "$Default" if the field is empty? I guess ideally the AWS Go SDK would fill this in for us.

**Comment by jaypipes** [comment]
Hi @jsharpe, sorry for delay, was on vacation and dealing with other stuff! Please check out https://github.com/kubernetes/autoscaler/pull/2385 and let me know if this addresses the problem for you. Thanks!

**Comment by jsharpe** [comment]
@jaypipes Yes #2385 looks like it should address the problem.
