### ISSUE TITLE
'vertical-pod-autoscaler-0.4.0' tag points to 0.3.1 images

### ISSUE THREAD

**Issue by mattnworb** [kubernetes/autoscaler#1750]
For example:

https://github.com/kubernetes/autoscaler/blob/vertical-pod-autoscaler-0.4.0/vertical-pod-autoscaler/deploy/recommender-deployment.yaml#L23

https://github.com/kubernetes/autoscaler/blob/7f77136aeea401ca5199292c4e5eb17eb1597e55/vertical-pod-autoscaler/deploy/recommender-deployment.yaml#L23

**Comment by bskiba** [comment]
This is maybe not so much by design but the expected result of current release process.
The tag is exactly at the place when the binaries were built. We create the release first, test and verify this and then update the config to use the verified release.

We could first update configs and build release later, but I don't like having config pointing at the untested (or yet nonexistent) release.

**Comment by mattnworb** [comment]
Makes sense, thanks for clarifying!
