### ISSUE TITLE
Add ephemeral storage requests recommendation and update to vpa

### ISSUE THREAD

**Issue by mfilotto** [kubernetes/autoscaler#1751]
It would be nice if vpa could also take care of ephemeral storage usage and set request accordinngly

**Comment by bskiba** [comment]
@kgolab I think you were looking into this. Are there usage metrics for ephemeral storage available form Metric Server?

**Comment by kgolab** [comment]
@bskiba , at the moment Metric Server only serves metrics for CPU & memory usage.
But, since:
- the ephemeral storage usage is also available via Kubelet summary API, scraped by Metric Server to obtain all the information,
- and ephemeral storage is part of Pod resource request,
- and it's been also mentioned in [comments to in-place update KEP proposal](https://github.com/kubernetes/enhancements/pull/686#discussion_r248990810),

maybe we could make a case for it being included in Metric Server and then supported by VPA.

@mfilotto , do you already have a use case in mind or, even better, described somewhere? We'd like to understand more about intended usage of these recommendations.
In particular I'm very interested in *when* would the recommendations be applicable from your perspective.

**Comment by mfilotto** [comment]
@kgolab I use vpa to set requests automatically. This way kubelets and scheduler will have a more precise intel of what's going on on each node. So my goal is to reduce evictions as much as possible. vpa help well for memory and cpu but ephemeral storage are left unset and keep triggering evictions.
If vpa could also set ephemeral storage it would be awesome and this way vpa would help to reduce all evictions and be precious for capacity planning.

**Comment by kgolab** [comment]
/remove-lifecycle stale
Marking as not to disappear from the radar, this might be revisited at some point.
