### ISSUE TITLE
When a host is scaling down how can unregister license attached on the host ?

### ISSUE THREAD

**Issue by bysnupy** [kubernetes/autoscaler#1784]
Some license is subscribed on the each running host, and counting the number through internet.
If the cluster is scaling out, we can attach the license using `user data` (`cloud-init`), 
but how can we unregister the license while the host is scaling down ? `cluster-autoscaler` have any feature to resolve ?

Thanks.

**Comment by aleksandra-malinowska** [comment]
I'd try to add a VM shutdown hook, if your cloud provider supports it. Failing that, it should be relatively straightforward to create a component that watches nodes and performs cleanup actions whenever they disappear. If you really only want to handle the case of autoscaler deleting the node (not if it disappears due to machine failure, or if a user deletes it manually), you can listen for scale down events published by autoscaler (keeping in mind that Kubernetes events are best-effort only).

**Comment by bysnupy** [comment]
Thank you for your information, as my first approach I will try your suggestions. By the way it seems cluster-autoscaler does not provide the related feature now. @aleksandra-malinowska answer my question, I will close this issue.

**Comment by aleksandra-malinowska** [comment]
To the best of my knowledge, there's no way to make autoscaler execute arbitrary actions, short of building your own release. ;)
