### ISSUE TITLE
Failed to create AWS Manager: RequestError: send request failed ( i/o timeout)

### ISSUE THREAD

**Issue by AESwrite** [kubernetes/autoscaler#1860]
Hello, 
I'm currently using kubernetes v1.12.5 and CA v1.12.3
Cluster was created with kubespray v.2.8.3 (kubeadm enabled). 
Provider: AWS

I'm using the standart example of cluster-autoscaler-one-asg.yaml, I've modified only this lines:

>containers:
        _- image: k8s.gcr.io/cluster-autoscaler:v1.12.3_

>  _--nodes=1:4:k8s-worker-20190403143728147500000003-asg_

>   _env:
            - name: AWS_REGION
              value: us-east-2_

>   volumes:
        - name: ssl-certs
          hostPath:
            _path: "/etc/ssl/certs/ca-bundle.crt"_

**I get this kind of error (the same in different versions of CA):**

>I0404 13:30:06.959934       1 leaderelection.go:227] successfully renewed lease kube-system/cluster-autoscaler
**E0404 13:30:07.364127       1 aws_manager.go:153] Failed to regenerate ASG cache: RequestError: send request failed
caused by: Post https://autoscaling.us-east-2.amazonaws.com/: dial tcp: i/o timeout
F0404 13:30:07.364158       1 cloud_provider_builder.go:149] 
caused by: Post https://autoscaling.us-east-2.amazonaws.com/: dial tcp: i/o timeout'**

I tried to use CA v1.3.0 on kubernetes v1.11.3 last week (the same yaml file, only different version of CA), and it worked. But today i get timeout error even on that v1.11.3 configuration (i didn't change anything in this configuration from last week).

How can i solve this issue? I will be glad to any help!

Update 1: container with autoscaler somehow can't reach internet.

**Comment by Jeffwan** [comment]
Can you run `kubectl get pods ${your_ca_pod} -o yaml` and check what's the value of `dnsPolicy`? 

Is you cluster running in `us-east-2`? AWS_REGION is not required in v1.12. 

From last week, samples has some clean up but I didn't see any problems there.

**Comment by AESwrite** [comment]
> kubectl get pods ${your_ca_pod} -o yaml

**dnsPolicy: ClusterFirst**

Yes, cluster is running in us-east-2.
I discovered that pod somehow uses default resolv.conf file 

`; generated by /usr/sbin/dhclient-script
search us-east-2.compute.internal
nameserver 10.0.0.2
`


And when i added `nameserver 8.8.8.8` to it on master and worker, the CA started to work. I'm not sure if it's a solution or just a workaround (i don't think CA should use this file, because kubespray should write it's own resolv.conf, so maybe it is a kubespray problem), but now i can google some similar cases and find it out.

**Comment by AESwrite** [comment]
The problem is still relevant.
Sometimes it works (in 10% of cases), but most of the time it crashes with timeout error.
DNS settings and services look ok, and working on other pods perfectly.

**Comment by Jeffwan** [comment]
Hi @AESwrite, sorry for late response. Anything special to your VPC settings?  If you can consistently reproduce this issue, that probably a bug somewhere. I'd like to try to reproduce and fix it.

**Comment by Siddharthk** [comment]
I am also getting the same error:
CA version: 1.12.3
AWS EKS version: 1.12.7


`I0529 12:05:53.849655       1 leaderelection.go:227] successfully renewed lease kube-system/cluster-autoscaler
I0529 12:05:55.942323       1 leaderelection.go:227] successfully renewed lease kube-system/cluster-autoscaler
E0529 12:05:56.036033       1 aws_manager.go:153] Failed to regenerate ASG cache: RequestError: send request failed
caused by: Post https://autoscaling.us-east-1.amazonaws.com/: dial tcp 72.21.206.37:443: i/o timeout
F0529 12:05:56.036064       1 cloud_provider_builder.go:149] Failed to create AWS Manager: RequestError: send request failed
caused by: Post https://autoscaling.us-east-1.amazonaws.com/: dial tcp 72.21.206.37:443: i/o timeout`

@AESwrite @Jeffwan  Can someone help here?

**Comment by thinalai** [comment]
> I am also getting the same error:
> CA version: 1.12.3
> AWS EKS version: 1.12.7
> 
> > I0529 12:05:53.849655       1 leaderelection.go:227] successfully renewed lease kube-system/cluster-autoscaler
> 
> > I0529 12:05:55.942323       1 leaderelection.go:227] successfully renewed lease kube-system/cluster-autoscaler
> 
> > E0529 12:05:56.036033       1 aws_manager.go:153] Failed to regenerate ASG cache: RequestError: send request failed
> 
> > caused by: Post https://autoscaling.us-east-1.amazonaws.com/: dial tcp 72.21.206.37:443: i/o timeout
> 
> > F0529 12:05:56.036064       1 cloud_provider_builder.go:149] Failed to create AWS Manager: RequestError: send request failed
> 
> > caused by: Post https://autoscaling.us-east-1.amazonaws.com/: dial tcp 72.21.206.37:443: i/o timeout
> 
> @AESwrite @Jeffwan Can someone help here? It was working fine on EKS v1.11.5.

check your CA pod public network accessibility

**Comment by lmansur** [comment]
I was running into this problem in a cluster created by kops using a pre-existing VPC.

The route table for my subnets was the default one created by AWS. Setting the route table created by kops as _main_ and deleting the one created by AWS solved my problem.

**Comment by michaelpporter** [comment]
I am having the same issue. We have installed CA in 4 different VPCs the three us-east-1 instances all work fine, the one in us-east-2 fails.

```bash
{"log":"E0109 14:11:31.735207       1 aws_manager.go:153] Failed to regenerate ASG cache: RequestError: send request failed\n","stream":"stderr","time":"2020-01-09T14:11:31.736567592Z"}
{"log":"caused by: Post https://autoscaling.us-east-2.amazonaws.com/: dial tcp: i/o timeout\n","stream":"stderr","time":"2020-01-09T14:11:31.736595585Z"}
{"log":"F0109 14:11:31.735237       1 cloud_provider_builder.go:149] Failed to create AWS Manager: RequestError: send request failed\n","stream":"stderr","time":"2020-01-09T14:11:31.736600881Z"}
{"log":"caused by: Post https://autoscaling.us-east-2.amazonaws.com/: dial tcp: i/o timeout\n","stream":"stderr","time":"2020-01-09T14:11:31.736605602Z"}
```

We have used the [helm](https://github.com/helm/charts/tree/master/stable/cluster-autoscaler) version and the [standalone example for multi-asg](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-multi-asg.yaml) 

The EKS is built with terraform, so each one is using the same settings, besides region and VPC.

We have used 2 different accounts, VPCs are in one account while the failing one is in another. We are adding an EKS cluster to us-east-1 in the account that is currently failing to test regions. I will report back our findings.

**Comment by michaelpporter** [comment]
Summary:

| account-vpc        | region    | status  |
| -------------- | --------- | ------- |
| data-qa2       | us-east-2 | inconsistent   |
| data-qa1       | us-east-1 | inconsistent   |
| nonprod-qa1   | us-east-1 | success |
| nonprod-test  | us-east-1 | success |
| nonprod-stage | us-east-1 | success |

I will report if we find anything new.

**Comment by biswarup1290dass** [comment]
@Jeffwan From the above discussion I was not able to conclude what was the solution to this issue. Would it be possible for you to help me for a similar issue mentioned below:
`I0323 14:22:09.443369       1 reflector.go:161] Listing and watching *v1.ReplicaSet from k8s.io/client-go/informers/factory.go:132
E0323 14:24:10.335006       1 aws_manager.go:259] Failed to regenerate ASG cache: RequestError: send request failed
caused by: Post https://autoscaling.us-east-2.amazonaws.com/: dial tcp: i/o timeout
F0323 14:24:10.335046       1 aws_cloud_provider.go:330] Failed to create AWS Manager: RequestError: send request failed
caused by: Post https://autoscaling.us-east-2.amazonaws.com/: dial tcp: i/o timeout
`

I am using the multi ASG deploynment for AWS CA.
Versions:
CA Version : k8s.gcr.io/cluster-autoscaler:v1.14.7 
EKS Version : 1.14
Platform Version eks.9
coredns: v1.6.6 
aws-node: amazon-k8s-cni:v1.5.5

**Comment by Jeffwan** [comment]
@biswarup1290dass  Em... Can you share dnsPolicy of your pod and if your coreDNS pod is running well (check logs probably)

**Comment by yiyan-wish** [comment]
same issue
`E1210 03:15:12.303121       1 aws_manager.go:265] Failed to regenerate ASG cache: cannot autodiscover ASGs: RequestError: send request failed
caused by: Post "https://autoscaling.cn-northwest-1.amazonaws.com.cn/": dial tcp 52.82.209.176:443: i/o timeout`
and the cluster-autoscaler pod's dnsPolicy is `ClusterFirst`
