### ISSUE TITLE
Add a configuration to CA that limits the number of nodes added per scale up.

### ISSUE THREAD

**Issue by ceelion** [kubernetes/autoscaler#1962]
Cluster autoscaler does not limit the number of nodes added per scale up. We have a use case where we want to scale up in batches and limit the number of nodes added per scale up cycle.

**Comment by aleksandra-malinowska** [comment]
At first sight, I don't see a problem with it as long as it stays unlimited by default.

By the way, can you share a bit more about your setup and the problem you want to solve with this?

**Comment by MaciekPytel** [comment]
The problem is the definition of a 'scale-up cycle'. You could easily add a parameter to cap it at whatever number of nodes, but it won't really do anything. CA doesn't have any sort of cooldown - it will trigger new scale-up every loop (so every 10-20s) until it thinks there is enough nodes. 

What you're trying to do sounds more like something you'd do in utilization-based autoscaler, where you can add some nodes and only make next scaling decision after observing the state after scale-up. It doesn't really fit CA model. Can you describe your use-case in more detail, so we can understand where this requirement comes from and possibly suggest a different approach?

**Comment by ringtail** [comment]
I think it might be the limit of cloud provider. In some providers. You can only scale up nodes less than a fix number.

**Comment by MaciekPytel** [comment]
I see. But is it fixed number of nodes per request or per second/minute/some other unit of time? If it's the former it feels like cloudprovider implementation could split the scale-up into multiple requests (controlled by internal flag). If it's the latter adding a simple cutoff to size of single scale-up won't solve it, because we'd likely trigger another scale-up too soon.

**Comment by aleksandra-malinowska** [comment]
I don't think there's a specific implementation to discuss yet. Adding it in cloudprovider modules sounds good, but depending on what exactly are the limitations of the given cloud, it could also break the feature - e.g. if the limitation is per node group, but multiple node groups can be resized at once without hitting this limit, splitting scale-ups alone would be sufficient, while throttling in cloud provider would just result in slower scale-up in one group.

**Comment by ceelion** [comment]
Thanks for all the comments. The use-case that we had was to avoid aggressive scale up caused by a single user's application. Thought more about it and seems that this approach is not going to solve it, so closing the issue.

**Comment by MaciekPytel** [comment]
@ceelion Kubernetes has mechanisms for controlling how much resources a single user can request (https://kubernetes.io/docs/concepts/policy/resource-quotas/) and those are probably the best way to tackle your issue. Autoscaler assumes that all the control happens at the time of pod admission control and if a pod requests a given amount of resources it has the right to do so.
