### ISSUE TITLE
When Azure subscription quota is going to be exceeded during new node scale-out for Azure VMSS, the cluster is crushing

### ISSUE THREAD

**Issue by elutsky** [kubernetes/autoscaler#1975]
Unfortunately, have no logs / ,,, to provide - it happened us several months ago.
When we got close to the quota of Azure subscription CPUs, and CA did try to add additional node (which supposed to exceed the quota) - the cluster crashed.

We just enlarged quota and re-created cluster.

CA is working fine for us - before and after.

Our environment:
K8s: 1.12.1
Cloud: Azure: 
Reource: VMSS

**Comment by bskiba** [comment]
What do you mean by "the cluster crushed"?

**Comment by feiskyer** [comment]
@elutsky Same question as bskiba. What do you mean by `the cluster crashed`?

**Comment by feiskyer** [comment]
> When we got close to the quota of Azure subscription CPUs, and CA did try to add additional node (which supposed to exceed the quota) - the cluster crashed.

> We just enlarged quota and re-created cluster.

> CA is working fine for us - before and after.

Since CA is working fine before and after, I'm not sure what `the cluster crashed` means here. Though new nodes won't be able to scale, the Kubernetes cluster itself should still work good.

close since we didn't get enough context for the issue. @elutsky feel free to reopen if you still have problems.

/close
