### ISSUE TITLE
recommender Error adding metric sample for container

### ISSUE THREAD

**Issue by qist** [kubernetes/autoscaler#2010]
{"log":"W0511 06:07:10.273944       6 cluster_feeder.go:386] Error adding metric sample for container {{default my-rec-deployment-55c8bd8657-j5fmp} POD}: KeyError: {{default my-rec-deployment-55c8bd8657-j5fmp} POD}\n","stream":"stderr","time":"2019-05-11T06:07:10.276302417Z"}

**Comment by bskiba** [comment]
Does it cause any visible issues? This is expected if we get a sample for a pod that stopped to exist in the meantime.

**Comment by qist** [comment]
kube-apiserver --version
Kubernetes v1.14.0
docker images
k8s.gcr.io/vpa-recommender:0.5.1 

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vpa-recommender
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vpa-recommender
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vpa-recommender
    spec:
      serviceAccountName: vpa-recommender
      containers:
      - name: recommender
        image: k8s.gcr.io/vpa-recommender:0.5.1
        imagePullPolicy: Always
        args:
          - "--v=4"
          - "--storage=prometheus"
          - "--prometheus-address=http://prometheus-k8s.monitoring.svc:9090"
          - "--prometheus-cadvisor-job-name=kubelet"
        resources:
          limits:
            cpu: 200m
            memory: 1000Mi
          requests:
            cpu: 50m
            memory: 500Mi
        ports:
        - containerPort: 8080

**Comment by bskiba** [comment]
@qist Sorry, but I do not understand what problem you are facing. Is the VPA misbehaving in any way or is it just the warning message worrying you?

**Comment by lli-hiya** [comment]
I am also seeing this issue. 

To be more specific, i am using VPA release 0.8, and I have VPAs set up for only a tiny portion of Deployments in our cluster. When the Recommender first starts up and init from Prometheus, it logs is filled with error like

```
I0720 22:10:10.160316       1 cluster_feeder.go:212] Adding pod {syslog disk-metrics-1595223600-plpwj} with labels map[controller_uid:d5fa6460-cacd-4dc4-ac32-e35895069f0a job_name:disk-metrics-1595223600]
I0720 22:10:10.160335       1 cluster_feeder.go:218] Adding 11 samples for container {{syslog disk-metrics-1595223600-plpwj} disk-metrics}
W0720 22:10:10.160347       1 cluster_feeder.go:224] Error adding metric sample for container {{syslog disk-metrics-1595223600-plpwj} disk-metrics}: KeyError: {{syslog disk-metrics-1595223600-plpwj} disk-metrics}
W0720 22:10:10.160356       1 cluster_feeder.go:224] Error adding metric sample for container {{syslog disk-metrics-1595223600-plpwj} disk-metrics}: KeyError: {{syslog disk-metrics-1595223600-plpwj} disk-metrics}
...
```


The error logs seems to come from code: https://github.com/kubernetes/autoscaler/blob/vpa-release-0.8/vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go#L219-L224, and the error message for each container repeats itself one or multiple times, which in line with the code because the error message should appear for each PodHistory sample. Also, some containers appeared in the log **do** exist at the moment and are not init container, so I don't think this is the same issue as https://github.com/kubernetes/autoscaler/issues/2512. 

The errors log only exist when the Recommender first starts up, and won't repeat itself at the later cycles. 

Have anyone else seen this problem? Functionally it is not a blocker, but it is very annoying because whenever I query Recommender logs, these errors will flush to the screen and then the useful info starts later.

**Comment by sjentzsch** [comment]
Yes, same here. Also just stumbled upon it, thinking I got my label parameters wrong.

**Comment by superset1** [comment]
I am still getting "Error adding metric sample for container" in our logs.

**Comment by theophileds** [comment]
I'm having the same error as well, it has appeared after a cluster upgrade to 1.24.
