### ISSUE TITLE
[cluster-autoscaler][magnum] Support /resize API

### ISSUE THREAD

**Issue by openstacker** [kubernetes/autoscaler#2011]
Now Magnum has a /resize API which can accept the list of nodes to be removed and a target node count after the resize. That's a better option than the current way by calling Heat to remove the node and then calling Magnum to update the correct node count.

**Comment by openstacker** [comment]
@losipiuk Could you please help assign this issue to me? Thanks.

**Comment by tghartland** [comment]
@openstacker I have made these changes to my own fork of autoscaler (https://github.com/tghartland/autoscaler/tree/magnum-resize).

Since the resize API is much easier to use, it is possible to cut out a lot of the code that was required for deleting nodes with heat (blocking scaling while the cluster is updating, for example), but it means that kubernetes 1.16 and later will require magnum stein or later. Is that acceptable for the openstack community?
