### ISSUE TITLE
Ensure pods fit on mixed instance pools

### ISSUE THREAD

**Issue by nielsole** [kubernetes/autoscaler#2057]
We use launch templates with mixed instance types with varying CPU and memory for spot instance pools in AWS. 

This poses some challenges for the estimation of available CPU and memory on an ASG.
In our use-case we would like to use the smallest resources of each type across all instances (not the smallest instance, but that smallest value for each resource type).
This ensures that that if the autoscaler scales up an ASG, the pods are guaranteed to actually fit on it. 

IIUC as soon as an instance was created, that instance is used for estimation of the size that can be expected of that ASG. But this assumption is not necessarily true. 
Let's assume m5.xlarge and m5.2xlarge are in the same ASG and the autoscaler randomly brings up a m5.2xlarge it will use this for estimation. But the next instance might be a m5.xlarge. If the autoscaler chose this ASG for scale-up because it would fit an especially large pod, scheduling it would fail.

We would like to fix this. I am wondering whether this minimum resources across the ASG is a good default for everyone. If it is not, I would like to be able to override the CPU and memory available in an ASG using manually set tags on the ASG. 

Manual tagging has already been pondered in https://github.com/kubernetes/autoscaler/issues/1650 (specifically https://github.com/kubernetes/autoscaler/pull/1656#discussion_r255289482) for a different use-case and could be extended for CPU and memory. One possible blocker for this that IIRC the autoscaler wouldn't use the `buildNodeFromTemplate` if there are existing nodes. It would then use the existing nodes as a template (with all the problems described above).

Which of the two approaches would you favor? Or do you see a better solution alltogether?

**Comment by Jeffwan** [comment]
Still working on a doc in internal review.. This takes some time. I checked several limitation with our EC2 teams and seems no perfect solution right now. We can make it work for some cases but won't cover all use case. Currently, the best practice here is to use `similar` node with same resources as much as possible. 

The assumption here is container can alway run on the `template` node. Otherwise, ASG is backed by different instance types, there's always possibility pod can not schedule on the node since user doesn't have control on the scale up instance. Then let's consider how to build this template. 

1. If we have m5.xlarge (4CPU, 16Memory) and m5.2xlarge (8CPU, 32Memory) in the same ASG Mixed Instance Pool, we should use Min (instances.CPU) and Min(instances.Memory) which is (4GPU, 16 Memory) to do estimation.  No matter scale up from existing node or scale up from 0 (template). I have a PR ongoing to honor override LaunchTemplate values.


2. Manual tagging brings some management efforts. I am not sure if users like this way. Using m5.xlarge and m5.2xlarge, what's the right CPU/Memory you want to use? For users understand their workloads, they may come with some good combination with high cost efficiency. There're also lots of users don't know what the limit range of their workloads. (like cluster admin). That would be hard to give right value.  If there's one perfect formula or algorithm, we can also make it work in #1.

**Comment by nielsole** [comment]
1. would currently be our preferred approach. Do you have a link to your PR?
