### ISSUE TITLE
Pods scale past the MaxPods with the HPA

### ISSUE THREAD

**Issue by NolanChan** [kubernetes/autoscaler#2109]
We've been using the HPA for about a month now, and it's been working well. However today, one of our instances went over the MaxPods

`k get all -n ugrnxfjjqunttwzmrc`
<img width="1193" alt="Screen Shot 2019-06-07 at 11 44 42 AM" src="https://user-images.githubusercontent.com/1487616/59119918-acee5900-8919-11e9-8a3e-d197ea4f95a0.png">

Is this known behavior?

**Comment by Denton24646** [comment]
The HPA works based off utilization metrics - for stuff like CPU the utilization metric can be over 100% and this could potentially cause max pods to be exceeded. CPU utilization is the actual container CPU usage divided by the requested CPU usage (which is the minimum amount of CPU available to the container). Since the container can use more than the minimum this can cause the actual to be higher than the requested and the utilization ratio will exceed 100%. This can cause "out of bounds" scale up potentially. 

Looking through the HPA source code, it seems like your scenario is plausible.
Here is where the pod replica count calculation takes place (that could potentially return a number greater than max for a `Resource` type metric:
https://github.com/kubernetes/kubernetes/blob/5fe910191a6a1a64872e249c4c431b0169d763ed/pkg/controller/podautoscaler/horizontal.go#L603
Here is where the logic that consumes this information is - it includes a check against max pods, or `hpa.Spec.MaxReplicas`, but compares via ` if currentReplicas > hpa.Spec.MaxReplicas  {...}`:
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podautoscaler/horizontal.go#L592
I think maybe the comparison operator being `>` instead of `>=` can cause this off by one error to occur. If the current replica count is 10, and max spec is 10, this condition will be false, and the conditional logic will go into the actual metric calculation via `computeReplicasForMetrics()` that I linked above which then edits the scale subresource and triggers a scale up. 

I'm new to the codebase, but if this is in fact the issue I would be happy to open up a PR 👍

**Comment by xjas** [comment]
@Denton24646 Personally, after reading some revelant source code,I think the logic you have described could not make sense.
If possible, please have a look at these code: https://github.com/kubernetes/kubernetes/blob/5fe910191a6a1a64872e249c4c431b0169d763ed/pkg/controller/podautoscaler/horizontal.go#L626

@NolanChan However, I still can not figure out how  this happened, and I can not reproduce it neither.
Can you describe how to reproduce it? Or the phenomenon occurs frequently?

**Comment by xjas** [comment]
@fgrzadkowski @jszczepkowski If possible, could you take a look at this issue and the relevant PR: https://github.com/kubernetes/kubernetes/pull/78859  ?

**Comment by Denton24646** [comment]
Ah yes, I see that if you dig deeper into the code this condition should be hit later on and return the `hpa.Spec.MaxReplicas` 
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podautoscaler/horizontal.go#L743

The `convertDesiredReplicasWithRules()` function uses the `stabilizedRecommendation` variable as `desiredReplicas` within its function context. I think the off-by-one bug may be originating from that portion of the code instead - I will update my PR. 

Another issue worth noting is that in the OP the target metrics don't seem to be coming through - maybe the HPA was just started or there was an issue with the custom metrics source. I am not sure if that's the cause of this but is worth mentioning and I meant to do it in my original response.

**Comment by Denton24646** [comment]
I closed my PR after not receiving any feedback from folks on the autoscaling team for a month. Seems like this will remain a mystery @NolanChan
