### ISSUE TITLE
GKE nodes with local SSD

### ISSUE THREAD

**Issue by k1ng440** [kubernetes/autoscaler#2145]
Hello,
I have database pool that has local ssd. is there anyway to automatically scale the pool?

**Comment by aleksandra-malinowska** [comment]
Hi, due to the way local SSDs are represented in Kubernetes, autoscaling doesn't currently support them directly. More specifically, scale up isn't supported, as schedule predicate fails for the template node due to lack of matching local volume.

I haven't tried that, but I think there may be a workaround: assuming you're using pod autoscaling for your database deployment, you could configure another, empty deployment with pod autoscaling configuration using the same metric (so the number of replicas is the same). This additional deployment can request negligible resources, but if it has node selector matching the database pool and requests a specific host port, CA should scale up for it, effectively ensuring space for any new database pods. 

If you run more than one database pod per node, it may still work with different target for pod autoscaling, but I'd expect it to be less precise (and so less reliable).
