### ISSUE TITLE
autoscaller and emptydir

### ISSUE THREAD

**Issue by cristifalcas** [kubernetes/autoscaler#2184]
What is the reasoning behind https://github.com/kubernetes/autoscaler/blob/fae2c903a3a6615fc53b748e7a17398128b60745/cluster-autoscaler/utils/drain/drain.go#L197-L199

Why would emptydir make the pod unevictable? 

Shouldn't be considered that it's stateless and can be moved safely?

**Comment by Denton24646** [comment]
I think it's because `emptyDir` volumes are generally backed by the storage of the node and in effect act like local storage volumes.

> By default, emptyDir volumes are stored on whatever medium is backing the node - that might be disk or SSD or network storage, depending on your environment.

So I guess evicting pods backed by an `emptyDir` volume could lead to data loss and that's why its disabled by default. 

Source:
https://kubernetes.io/docs/concepts/storage/volumes/#emptydir

**Comment by Denton24646** [comment]
That being said, you can override the default behavior and allow pods backed by `emptyDir` volumes to be evicted by adding the `"cluster-autoscaler.kubernetes.io/safe-to-evict": true` annotation to the pod

**Comment by sslavic** [comment]
Thanks both! Just small correction, for any by-passer, valid annotation value is a quoted string i.e. `"cluster-autoscaler.kubernetes.io/safe-to-evict": "true"` (see related [docs](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node))
