### ISSUE TITLE
Scaling cluster for running out of IPs

### ISSUE THREAD

**Issue by mkorbi** [kubernetes/autoscaler#2210]
Hey,

I discovered now a few times with AWS EKS cluster that we reach the maximum amount of given IPs per Elastic Network Interfaces (ENI) and instance. This happens because with AWS EKS you have a limited number of available IPs e.g. m5.large can have 3 ENI each with 10 IPs = 30 possible IPs per node. 

It would be awesome to have the possibility to configure the autoscaler to spin up new instances in case there are no IPs available and pods are pending.

/aws
/cluster-autoscaler
/sig aws
/kind feature

**Comment by ivanfoo** [comment]
@mkorbi are you using the EKS-optimized AMI? If not, you have to set up the --max-pods flag in kubelet to don't allocate more pods that allowed IPs per instance.

You can take a look here: https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt

**Comment by mkorbi** [comment]
@ivanfoo yes I do. It anyhow can't schedule more pods then IPs. But that`s why I think it could be an interesting feature (especially for AWS EKS :/ ) to autoscale if you run out of available IPs. So basically then you treat the IP like other resources.

**Comment by MaciekPytel** [comment]
I think this problem is generally addressed by setting max-pods in kubelet, as @ivanfoo suggested. 

If you think a new mechanism is needed, I don't think autoscaler is the right place to add it. If scheduler is not aware of limitation, adding new node is potentially useless - CA has no control over scheduling and no way to make the pod schedule on the new node. If scheduler is aware of the limitation, CA should pick it up automatically (because it uses imported scheduler internals).

**Comment by Jeffwan** [comment]
For these kind of features, please submit a request here. https://github.com/aws/containers-roadmap. 

This is the limitation of current CNI implementation, another solution is to use `kubenet` to get rid of IP limitation, it would be helpful for high density workloads. This is in the roadmap now.

**Comment by rohith-gittest** [comment]
Issue Summary:
EKS worker nodes has limitations  for running number of pod based on the instance type. In our case we use instance type-c5.2xlarge which allows 58 pods per instance. If the pods are scheduled more than that number on the same instance, then those pods are getting stuck in ContainerCreating status.
Describing the pods gives us following errors:  " Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "8be3026cc6bb2b311570f118dfef8ab93ae491e6d6fc20e12a46e9b814cff716" network for pod "pod-name": networkPlugin cni failed to set up pod "pod-name" network: add cmd: failed to assign an IP address to container "

As part of solution we tried adding --use-max-pods false --kubelet-extra-args '--max-pods=110' into our EKS worker node bootstrap script. Still the issue remains same.
Please guide us the solutions if there are any to remove pods restriction based on instance type and run max number of pods in a worker node.

Note: 
Based on the AWS premium support they suggest us to consider greater instance types to achieve our use-case(which is to run max number of pods in a worker node). 
This solution provided by AWS is absolutely weird in many ways as listed below:

1) If we run maximum number of pods in a EKS worker node, Still we can see worker nodes are being underutilized in terms of CPU and memory. In this case using higher instance type will cost us more.
Even if i run max number of pods in a worker node consuming the total % of CPU will not cross double digits. In this use case again having greater instance type is not the cost optimization strategy.

2) If the pods are stuck in ContainerCreating state, the same pod can't move to running state unless it's being killed and restarted.
So our requirement is kube-scheduler should know if the node have the sufficient IPs, Then only it should schedule the pod  on that particular node. Indeed kube-scheduler should know if IPs are exhausted in the worker node before placing the pods.

3) If we use aws vpc custom cni then worker nodes cant make use of all the NIC available for that instance type.
For Ex: We use c5.2xlarge which supports max 4 NIC. Since we use a different subnets each for nodes and pods. 1 NIC will be assigned to our node which will have only 1 IP and rest of the 14 IPS will be wasted.
other 3 NIC*15=45 pods only we can run instead of 58 pods. Please give us a justification on this.

4) If pods stuck in Container creating status any auto scaling option available to bring new nodes	as like cluster autoscaler will monito CPU and memory.
