### ISSUE TITLE
why can not  cluster-autoscaler work from empty cluster?

### ISSUE THREAD

**Issue by yan234280533** [kubernetes/autoscaler#2218]
In cluster-autoscaler  we found this, it limit the cluster-autoscaler in empty node cluster, It why ? Can we remove the limit ?

The code is :
if a.actOnEmptyCluster(allNodes, readyNodes, currentTime) {
    return nil
}

**Comment by MaciekPytel** [comment]
IIRC the reason for that is that many parts of logic (clusterstate?) break if the cluster is empty. I don't think just removing this if will make CA work with empty cluster - it would require careful testing, identifying and fixing all parts that make assumptions about cluster being not empty.
@aleksandra-malinowska may know more details on this.

**Comment by aleksandra-malinowska** [comment]
Yes, most of the logic, and clusterstate in particular, assumes that there are some nodes in the cluster. More details are in #555 - it may be a bit outdated as there were some changes since, but I don't believe the issues were resolved. Fixing it isn't probably especially hard, but requires more work than just removing the checks.

**Comment by yan234280533** [comment]
@MaciekPytel @aleksandra-malinowska  I found that too, it not only to remove the limit logic, must modify many logics in the CA. I will have feature look of how to modiy this.
