### ISSUE TITLE
Incorrect backoff duration in case of overlapping scale-ups

### ISSUE THREAD

**Issue by MaciekPytel** [kubernetes/autoscaler#2225]
`duration` variable is not properly updated in https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/utils/backoff/exponential_backoff.go#L69 if the NodeGroup is already in backoff. As a result, if there are multiple concurrent scale-ups the duration of backoff will keep resetting to `initialBackoffDuration`.

In default configuration `--scale-down-delay-after-add` is 10m and `initialBackoffDuration` is 5m. This means that CA will not do any scale-down within 10m of scale-up and it will retry failed scale-up every 5 minutes. In other words a single NodeGroup that consistently fails to scale-up will block any scale-down in cluster.

**Comment by Denton24646** [comment]
I'd like to take a shot at this bug - if I understand correctly, we need to check for backoff already inside `Backoff()` via `IsBackedOff()` and in the case where the NodeGroup is already in backoff, increment it appropriately so it ends up higher than `--scale-down-delay-after-add` at some point to not block as you described. It's nice because it's fairly testable.

**Comment by MaciekPytel** [comment]
I meant to fix it myself later this week, but I'm happy to review your fix if you beat me to it. I think the fix is literally 1 LOC in Backoff() + unittest.
