### ISSUE TITLE
Cluster Autoscaler should suppurt using a kubeconfig file to create kube-client

### ISSUE THREAD

**Issue by drinktee** [kubernetes/autoscaler#223]
I run ca out of cluster and I think it is more convenient to use a kubeconfig file to create kube-client.

**Comment by drinktee** [comment]
@ @

**Comment by drinktee** [comment]
@mwielgus @DirectXMan12  It will be great if someone from sig-autoscaling can have a look at this. Thanks!

**Comment by MaciekPytel** [comment]
Hi @drinktee,
It sounds like a reasonable feature, we could have a new flag (`--kubeconfig` or similar) that can be passed instead of `--kubernetes`. 
If you want to contribute such feature I'm happy to review. Otherwise we can add it to our todo list. However, we're currently focusing on getting all the features we're already committed to for 1.8 (mostly optimizing CA, so it can be used on larger clusters without major performance hiccups) and this falls into a 'nice to have' category, meaning it most likely won't happen in 1.8 timeframe.

**Comment by mwielgus** [comment]
Fixed with #268
