### ISSUE TITLE
cluster autoscaler cannot start with readOnlyRootFilesystem

### ISSUE THREAD

**Issue by pbecotte** [kubernetes/autoscaler#2253]
Seems like cluster-autoscaler tries to open a log file in /tmp, even if you pass `--logtostderr`.

Replicate-
`docker run --read-only -it --rm k8s.gcr.io/google-containers/cluster-autoscaler:v1.13.6 ./cluster-autoscaler --logtostderr --help`

>> 

> log: exiting because of error: log: cannot create log: open /tmp/cluster-autoscaler.35cb3a9d1c2d.root.log.INFO.20190812-144433.1: read-only file system

(I dont actually see `logtostderr` anywhere in the codebase outside of the examples... not being a golang person, couldn't find the implementation)

**Comment by Denton24646** [comment]
The `logtostderr` flag gets set by `klog` which is a separate kubernetes package responsible for parsing and setting command line flags. `klog.InitFlags` is actually is the very first thing that runs in the cluster-autoscaler:
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/main.go#L352

If we look at this function more closely we can see some interesting comments about `logtostderr` specifically:
```
		logging.logFileMaxSizeMB = 1800
		// TODO: The default value of toStderr should be false.
		// Ideally, toStderr can be deprecated.
		// If --log-file is set, only log to the dedicated log-file.
		// If --alsoToStderr is true, whether or not --log-file is set, we will
		// log to stderr.
		// Since kubernetes/kubernetes are currently using klog with
		// default --toStderr to be true, we can't change this default value
		// directly.
		// As a compromise, when --log-file is set, the toStdErr is reset to
		// be false. e.g. See function `IsSingleMode`.
		logging.toStderr = true
```
So it looks like it's by default true, but should be false, or something fun like that.

Regardless, the issue you raise is not a result of the code but a script was being used in 1.13.6 to setup dependencies. If I just run

**Comment by Denton24646** [comment]
The `logtostderr` flag gets set by `klog` which is a separate kubernetes package responsible for parsing and setting command line flags. `klog.InitFlags` is actually is the very first thing that runs in the cluster-autoscaler:
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/main.go#L352

If we look at this function more closely we can see some interesting comments about `logtostderr` specifically:
```
		logging.logFileMaxSizeMB = 1800
		// TODO: The default value of toStderr should be false.
		// Ideally, toStderr can be deprecated.
		// If --log-file is set, only log to the dedicated log-file.
		// If --alsoToStderr is true, whether or not --log-file is set, we will
		// log to stderr.
		// Since kubernetes/kubernetes are currently using klog with
		// default --toStderr to be true, we can't change this default value
		// directly.
		// As a compromise, when --log-file is set, the toStdErr is reset to
		// be false. e.g. See function `IsSingleMode`.
		logging.toStderr = true
```
So it looks like it's by default true, but should be false, or something fun like that.

Regardless, the issue you raise is not a result of the code but a script was being used in 1.13.6 to setup dependencies. If I just run
```
docker run --read-only -it --rm gcr.io/google-containers/cluster-autoscaler:v1.13.6
./run.sh: 24: ./run.sh: cannot create /var/log/cluster_autoscaler.log: Read-only file system
```
We can see there is a separate run.sh script that is actually trying to create that file and causing the error. The cluster-autoscaler v1.13.6 Dockerfile pulls in the entire directory in and then just executes run.sh. Here's the run.sh file:
https://github.com/kubernetes/autoscaler/blob/c7ae868cb115dd61e9d563085757b93cd9d35f82/cluster-autoscaler/run.sh#L24

I noticed if you look at HEAD of master the run.sh file is gone now, so I think this behavior will change/be fixed in the next release of the CA.
