### ISSUE TITLE
Autoscaler exits after failing to fix node group size (AWS EKS)

### ISSUE THREAD

**Issue by xrl** [kubernetes/autoscaler#2285]
I have an AWS EKS cluster (1.13.8) and I'm running the master build of the autoscaler. I use spot instance ASGs and `eu-central-1c` is rejecting my requests for a `r5.xlarge` (which is fine, to be expected). But the autoscaler does not appear to be handling it gracefully. I have 86 restarts on the autoscaler component and the `k logs --previous` for the autoscaler pod show this before exiting:

```
I0829 14:14:00.057299       1 static_autoscaler.go:192] Starting main loop
I0829 14:14:00.058057       1 utils.go:464] Removing autoscaler soft taint when creating template from node ip-172-30-60-142.eu-central-1.compute.internal
I0829 14:14:00.058200       1 utils.go:464] Removing autoscaler soft taint when creating template from node ip-172-30-25-34.eu-central-1.compute.internal
I0829 14:14:00.058359       1 utils.go:464] Removing autoscaler soft taint when creating template from node ip-172-30-73-124.eu-central-1.compute.internal
I0829 14:14:00.058902       1 utils.go:464] Removing autoscaler soft taint when creating template from node ip-172-30-42-66.eu-central-1.compute.internal
W0829 14:14:00.249993       1 clusterstate.go:585] Failed to get nodegroup for aws:///eu-central-1c/i-placeholder-K3-EKS-spotr5xlasgsubnet02af43b02922e710f-10QH9H0C8PG7O-13: wrong id: expected format aws:///<zone>/<name>, got aws:///eu-central-1c/i-placeholder-K3-EKS-spotr5xlasgsubnet02af43b02922e710f-10QH9H0C8PG7O-13
W0829 14:14:00.250032       1 clusterstate.go:585] Failed to get nodegroup for aws:///eu-central-1c/i-placeholder-K3-EKS-spotr5xlasgsubnet02af43b02922e710f-10QH9H0C8PG7O-14: wrong id: expected format aws:///<zone>/<name>, got aws:///eu-central-1c/i-placeholder-K3-EKS-spotr5xlasgsubnet02af43b02922e710f-10QH9H0C8PG7O-14
W0829 14:14:00.250047       1 clusterstate.go:585] Failed to get nodegroup for aws:///eu-central-1c/i-placeholder-K3-EKS-spotr5xlasgsubnet02af43b02922e710f-10QH9H0C8PG7O-15: wrong id: expected format aws:///<zone>/<name>, got aws:///eu-central-1c/i-placeholder-K3-EKS-spotr5xlasgsubnet02af43b02922e710f-10QH9H0C8PG7O-15
I0829 14:14:00.250111       1 static_autoscaler.go:260] 3 unregistered nodes present
I0829 14:14:00.250125       1 utils.go:491] Removing unregistered node aws:///eu-central-1c/i-placeholder-K3-EKS-spotr5xlasgsubnet02af43b02922e710f-10QH9H0C8PG7O-14
W0829 14:14:00.250136       1 utils.go:494] Failed to get node group for aws:///eu-central-1c/i-placeholder-K3-EKS-spotr5xlasgsubnet02af43b02922e710f-10QH9H0C8PG7O-14: wrong id: expected format aws:///<zone>/<name>, got aws:///eu-central-1c/i-placeholder-K3-EKS-spotr5xlasgsubnet02af43b02922e710f-10QH9H0C8PG7O-14
W0829 14:14:00.250154       1 static_autoscaler.go:265] Failed to remove unregistered nodes: wrong id: expected format aws:///<zone>/<name>, got aws:///eu-central-1c/i-placeholder-K3-EKS-spotr5xlasgsubnet02af43b02922e710f-10QH9H0C8PG7O-14
I0829 14:14:00.250178       1 utils.go:538] Decreasing size of K3-EKS-spotr5xlasgsubnet02af43b02922e710f-10QH9H0C8PG7O, expected=16 current=13 delta=-3
E0829 14:14:00.250190       1 static_autoscaler.go:287] Failed to fix node group sizes: failed to decrease K3-EKS-spotr5xlasgsubnet02af43b02922e710f-10QH9H0C8PG7O: attempt to delete existing nodes targetSize:16 delta:-3 existingNodes: 16
I0829 14:14:00.656225       1 reflector.go:385] k8s.io/client-go/informers/factory.go:133: Watch close - *v1.Node total 1765 items received
I0829 14:14:01.530893       1 main.go:275] Received signal, attempting cleanup
I0829 14:14:01.543011       1 main.go:277] Cleaned up, exiting...
```

**Comment by jaypipes** [comment]
@xrl we were wondering if this only occurs when your ASG lists instance types that either don't exist or have no capacity for the region you are using. Could you let us know? Thanks!

**Comment by patoarvizu** [comment]
@jaypipes I am seeing a similar issue (K8s 1.12.7, kops 1.12.2, CA 1.12.8, AWS). I purposefully scaled up a `Deployment` replication to a very high number, and I hit a point where AWS couldn't scale up. There were two variations of of AWS not scaling up, 1) The ASG was trying to request instances of a type that wasn't available in a given AZ, or 2) I hit my account-wide limit.

In any case, after I scale down my `Deployment` and waiting for `--scale-down-unneeded-time`, I get the same error as above, so it never scales down.

Is there a way to at least manually clean up these `aws://<availability-zone>/i-placeholder-<nodegroup>` records (if they're persisted somewhere)? The way I've been doing this is that I manually set the ASG to the number it should be at, but I would prefer not to have to do that because it's a bit of a guessing game.

**Comment by jaypipes** [comment]
> @jaypipes I am seeing a similar issue (K8s 1.12.7, kops 1.12.2, CA 1.12.8, AWS). I purposefully scaled up a `Deployment` replication to a very high number, and I hit a point where AWS couldn't scale up. There were two variations of of AWS not scaling up, 1) The ASG was trying to request instances of a type that wasn't available in a given AZ, or 2) I hit my account-wide limit.
> 
> In any case, after I scale down my `Deployment` and waiting for `--scale-down-unneeded-time`, I get the same error as above, so it never scales down.
> 
> Is there a way to at least manually clean up these `aws://<availability-zone>/i-placeholder-<nodegroup>` records (if they're persisted somewhere)? The way I've been doing this is that I manually set the ASG to the number it should be at, but I would prefer not to have to do that because it's a bit of a guessing game.

Thanks for the feedback, @patoarvizu. I think I see what the issue is. I'll push a fix up shortly.

**Comment by jaypipes** [comment]
Turns out the code in master and the latest 1.13 release is correct. I added a unit test that proves this in #2641. @xrl and @patoarvizu please verify that you are running CAS with this patch from @gjtempleton:

https://github.com/kubernetes/autoscaler/commit/7d7b6e555fe0ea8a7fa58548c25c0eacffbeab98#diff-34ecd32e36ab8898fff1637bb1b39c2c

**Comment by patoarvizu** [comment]
We're running CAS in a production environment with a ~> 1.12 constraint so we can't upgrade to run this (without risk), so we'll have to wait and work around it for now.

**Comment by Nyefan** [comment]
We have run into a problem which is similar to this and [#790](https://github.com/kubernetes/autoscaler/issues/790).  When scaling up while hitting the spot instance limit for that region, and a bunch of metadata for placeholder nodes got created and never attached to an instance.  These entries couldn't get cleaned up because the cluster-autoscaler kept erroring out, saying

```
E0322 20:29:26.782157       1 static_autoscaler.go:214] Failed to remove unregistered nodes: wrong id: expected format aws:///<zone>/<name>, got aws:///eu-west-1b/i-placeholder-igname.eu-west-1.domain.com-160
```

Eventually, we get the `Failed to remove unregistered nodes` and `Failed to fix nodegroup sizes` log messages followed by the exit/restart.

**Comment by gjtempleton** [comment]
@Nyefan what version of the CA are you running with?

**Comment by m0rganic** [comment]
I'm on @Nyefan 's team we're currently running `k8s.gcr.io/cluster-autoscaler:v1.14.5`

**Comment by gjtempleton** [comment]
Have a look here: https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-1.14.5/cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go and here: https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-1.14.6/cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go

As you can see, the fix I made to that placeholder instance validation that @jaypipes mentioned above didn't make it into a release until 1.14.6. I believe simply upgrading to a later release in the 1.14 branch should resolve your problem. Let us know if it doesn't.

**Comment by gjtempleton** [comment]
Assuming this is safe to close
/assign @gjtempleton 
/close
