### ISSUE TITLE
Implement OpenStack cloud provider

### ISSUE THREAD

**Issue by praseodym** [kubernetes/autoscaler#230]
To support cluster autoscaling for Kubernetes clusters hosted on OpenStack, a new cloud provider should be added.

[Previous work was done on this in kubernetes/contrib](https://github.com/kubernetes/contrib/pull/1980) leveraging OpenStack Heat and the [Gophercloud](https://github.com/gophercloud/gophercloud/) library.

**Comment by mwielgus** [comment]
@praseodym Would you be interested in contributing this support?

**Comment by praseodym** [comment]
Sure! If @taimir is not in a position to update his previous PR I'll be willing to pick this up.

**Comment by taimir** [comment]
@praseodym feel free to take over this topic, I doubt I will have the time for that during the next few months. If you want to reuse something from the stale PR, I can give you access to the fork.

**Comment by mwielgus** [comment]
Great! Let me know if you have any problems or questions.

**Comment by saravanakumar-periyasamy** [comment]
@taimir - where is the stale PR? I like to take a look into it.

**Comment by saravanakumar-periyasamy** [comment]
nvm, found it here - https://github.com/kubernetes/contrib/pull/1980

**Comment by dklyle** [comment]
I'm interested in completing the work for this PR, is it preferred to open a new issue or reopen this one. 

The approach I want to take is different from the stale PR to contrib that is referenced above. I prefer to build and simpler base solution that only relies on core OpenStack projects rather than Heat or Senlin which are less likely to be deployed.

**Comment by dklyle** [comment]
Given the timeline of the past issue I opened a new issue.

**Comment by mwielgus** [comment]
ok
