### ISSUE TITLE
Make cluster-autoscaler more extendable

### ISSUE THREAD

**Issue by pigletfly** [kubernetes/autoscaler#2369]
currently there is a `StaticAutoscaler`, I think there could be a interface that users can implement their own Autoscaler,so that they can have their own scale up and scale down strategy

/kind feature

**Comment by MaciekPytel** [comment]
StaticAutoscaler is pretty much the main class for autoscaler (the name 'StaticAutoscaler' is purely because of historical reasons). Most of the logic inside is not a strategy and is about reconciling the state of the cluster, error handling, etc.I don't think replacing the whole thing is a feasible approach for extending CA.

The part that chooses which nodegroup should be scaled up is called expander (https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/expander) and it is an easily swapped interface.
For more advanced customization we provide 'processors' (https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/processors) a set of generic programming hooks that allow injecting custom code into various parts of CA logic.

**Comment by pigletfly** [comment]
The user story is: it's too late for CA to scale up if there is a pending pod because of lacking resources. I want to reserve some resources as a buffer, if request resources exceed the buffered resources,then CA will do scale up.

**Comment by MaciekPytel** [comment]
Would https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-configure-overprovisioning-with-cluster-autoscaler help?

**Comment by pigletfly** [comment]
yeah,pause pod will help.But could we make overprovisioning a build-in feature, I mean if I want to configure overprovisioning of a cluster, I just have to config some flags of Cluster Autoscaler, perhaps it's `--overprovision-cpu` `--overprovision-memory`, Cluster Autoscaler does all the things underhood.It will simplify the overprovisioning process.

**Comment by MaciekPytel** [comment]
This was discussed on many issues in the past (there were also at least one PR with a proposal). The problem is that there is no single CPU or memory calculation in CA. How would you define the overhead? What if you have nodes with different sets of taints and labels? Is any empty space in the cluster good enough (even if it's on tainted nodes where most pods can't go)? We often recommend having a separate NodeGroup only for system pods, how would it interact with that?

Any implementation inside CA would likely need to somehow convert your flag values into a set of in-memory pods and inject those into CA simulation. And any choice of pod shapes we would make would likely be super arbitrary and only work for a limited number of people.

So far the end result of every discussion was that in order to have CA-supported overprovisioning you'd need to provide a full pod spec (likely via CRD). But if you have a full pod spec why not just run a pause pod? What's the benefit of this extra CRD?

**Comment by pigletfly** [comment]
thanks for your explanation.ref discussion (https://github.com/kubernetes/autoscaler/issues/735)
/close
