### ISSUE TITLE
Action required: Move to scheduler.New to instantiate a scheduler

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/autoscaler#2449]
Scheduler "factory" package will be deprecated in k8s 1.17. To instantiate a scheduler in the [simulator](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/simulator/predicates.go#L129-L160), please use [scheduler.New()](https://github.com/kubernetes/kubernetes/blob/f0e1d394f13560cd6094722ec0b3969b05830fd0/pkg/scheduler/scheduler.go#L250) instead.

Please let me know if you hav any questions.

**Comment by MaciekPytel** [comment]
I'm not sure if this works for us - scheduler.New() seems to do a whole lot more than just initialize informers. We explicitly don't use [scheduler cache](https://github.com/kubernetes/kubernetes/blob/f0e1d394f13560cd6094722ec0b3969b05830fd0/pkg/scheduler/scheduler.go#L263) and I'm pretty sure we don't want any [event handlers](https://github.com/kubernetes/kubernetes/blob/f0e1d394f13560cd6094722ec0b3969b05830fd0/pkg/scheduler/https://github.com/kubernetes/kubernetes/blob/f0e1d394f13560cd6094722ec0b3969b05830fd0/pkg/scheduler/https://github.com/kubernetes/kubernetes/blob/f0e1d394f13560cd6094722ec0b3969b05830fd0/pkg/scheduler/eventhandlers.go#L359) registered on informers.

The point is we need predicates to be stateless. They can't use any precomputations (unless we explicitly provide it), because we're possibly invalidating them between simulations (moving pods around, creating in-memory node objects, etc). None of those changes are reflected in informers, so the scheduler state won't be updated accordingly.
Can we have a version of this function that we can use to only pass informers and skip all the other initialization of scheduler?

**Comment by ahg-g** [comment]
> I'm not sure if this works for us - scheduler.New() seems to do a whole lot more than just initialize informers. We explicitly don't use [scheduler cache](https://github.com/kubernetes/kubernetes/blob/f0e1d394f13560cd6094722ec0b3969b05830fd0/pkg/scheduler/scheduler.go#L263) 

May be I am missing something, but the current version of CA instantiates schedulerCache indirectly when it calls [NewConfigFactory](https://github.com/kubernetes/autoscaler/blob/6485f9c9fc3a749cd5bfe3d82140a9cdf0e75b58/cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/scheduler/factory/factory.go#L223), how is that different from scheduler.New()?

> and I'm pretty sure we don't want any [event handlers](https://github.com/kubernetes/kubernetes/blob/f0e1d394f13560cd6094722ec0b3969b05830fd0/pkg/scheduler/https://github.com/kubernetes/kubernetes/blob/f0e1d394f13560cd6094722ec0b3969b05830fd0/pkg/scheduler/https://github.com/kubernetes/kubernetes/blob/f0e1d394f13560cd6094722ec0b3969b05830fd0/pkg/scheduler/eventhandlers.go#L359) registered on informers.
>

The link you put returns 404, but I [see here](https://github.com/kubernetes/autoscaler/blob/6485f9c9fc3a749cd5bfe3d82140a9cdf0e75b58/cluster-autoscaler/simulator/predicates.go#L159) that the simulator does register the handlers.
 
> The point is we need predicates to be stateless. They can't use any precomputations (unless we explicitly provide it), because we're possibly invalidating them between simulations (moving pods around, creating in-memory node objects, etc). None of those changes are reflected in informers, so the scheduler state won't be updated accordingly.
> Can we have a version of this function that we can use to only pass informers and skip all the other initialization of scheduler?

Well, this is actually better for us, if you need something completely stateless, then creating [a framework](https://github.com/kubernetes/kubernetes/blob/3ec5fe500d7a56be6ff6c15f916987eaa48c2e94/pkg/scheduler/framework/v1alpha1/framework.go#L120) is the way to go, the framework receives a configuration that allows specifying which plugins to run, including which pre-filters (i.e., precomputations) are required etc.

Creating a framework once:
```
import framework "k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1"

config := {...}
registry := NewDefaultRegistry(...) . // we can change RegistryArgs to not accept listers instead of SchedulerCache
fwk := framework.NewFramework(registry, config)
```

For each "simulation":
```
cycleState := framework.NewCycleState()
s1 := fwk.RunPreFilterPlugins(cycleState, ...)
status := fwk.RunFilterPlugins(cycleState, ...)
```

Note that in 1.17, we will have all predicates run through the framework: https://github.com/kubernetes/kubernetes/issues/83554

**Comment by ahg-g** [comment]
/assign @losipiuk

Łukasz can you please confirm that this will work for CA now? the freeze for 1.17 is next week.

**Comment by losipiuk** [comment]
> /assign Łukasz Osipiuk
> 
> Łukasz can you please confirm that this will work for CA now? the freeze for 1.17 is next week.

Yeah - thanks for reminder. Looks good with linked PR. I manually tested CA and seems fine.
