### ISSUE TITLE
Nodes are not getting any taints even if use is low

### ISSUE THREAD

**Issue by alfonso-presa** [kubernetes/autoscaler#2498]
We have an aws eks deployment where all of our nodes are used for the same type of pod (browsers of a selenium grid). Pods are not behind and specific service or deployment, they are bootstrapped just to be registered on the grid and eventually resolve user tasks (browser tests). We don't want them to be evicted by CA as they might be performing tests (we cannot use PDBs), but we only leave them live while lazy for 15 minutes, so eventually they will be changed by different pod instances.

In this scenario CA is performing nicely in scaling up when users requests big amounts of browsers, spinning up thents of nodes, but the problem is that when demand goes low requested browsers keep getting spread among all of the nodes.

In this situation we were expecting CA to be adding taints to some nodes to preferably avoid scheduling pods to them when they are not needed. As we will keep rotating pods when idle, those nodes would eventually get empty, being able to be removed without any need to evict any pod. Is there any way we can get CA follow this behaviour? Just tainting nodes to avoid pod scheduling even if pods inside do not qualify for eviction?

Thanks!

**Comment by alfonso-presa** [comment]
Just to be more specific, this is the taint we were expecting to appear in our nodes eventually (and did not): https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/utils/deletetaint/delete.go#L37

**Comment by MaciekPytel** [comment]
CA deletes nodes that continuously match a certain set of criteria for a predefined amount of time (by default 10 minutes). It will only taint a node that already matches the criteria, just not for long enough (ie. one that CA thinks is safe to delete right now, but it hasn't yet built enough confidence to delete it).
If a node is running a pod that can't be evicted it won't get tainted, because CA doesn't know this pod will finish soon. It may just as well be a database or a server that will run for weeks without restart. So CA concludes it won't be able to delete this node anytime soon.

To answer your question more directly - no way to do this without serious code changes. I'd recommend looking into scheduler configuration - IIRC you can make scheduler prefer tight packing rather than spreading out pods with a config change.

**Comment by alfonso-presa** [comment]
@MaciekPytel . Sorry for the delay, and thanks for the tips. We finally decided to deploy our own scheduler to use cost effective scheduling policy for the pods, so they tend to fill the nodes instead of spread around them. I still think that the feature of optionally tainting nodes even if pods cannot be evicted would be nice to have. I'll leave the issue opened just in case is something doable in th future.
