### ISSUE TITLE
vpa-recommender: Prometheus history provider doesn't work with large Prometheus/Kubernetes deployments

### ISSUE THREAD

**Issue by milesbxf** [kubernetes/autoscaler#2543]
Whilst working on a fix for #2508 I ran into another issue whilst testing the VPA recommender with the Prometheus history provider. On startup the history provider queries Prometheus for historical container CPU usage over 8 days. We run a fairly large cluster and this results in a non trivial amount of cardinality and large amount of data, which Prometheus sensibly rejects due to the query returning too much data:

```
1172 cluster_feeder.go:209] Cannot get cluster history: cannot get usage history: cannot get timeseries for cpu: retrying GetTimeseries unsuccessful: tried 10 times, last error: bad HTTP status: 400 Bad Request. Response text: {"status":"error","errorType":"bad_data","error":"exceeded maximum resolution of 11,000 points per timeseries. Try decreasing the query resolution (?step=XX)"}
```

Even if this limit wasn't present, a query of this magnitude can easily OOMKill a large enough Prometheus instance.

**What can we do to fix it?**

Given we already retrieve a list of pods/labels using Prometheus, we can use that to split up and shard the queries to retrieve and load a subset of data at a time. Alternatively, we could change the history provider so that instead of all data being retrieved in one go on startup, we could dynamically load historical data for each VPA object we observe added to the cluster. 

Separately, I think we should also switch to using the Prometheus client library rather than writing HTTP calls and marshalling to custom types. This will let us build up valid queries programmatically (rather than `fmt.Sprintf`) and use the built in Prometheus types. This isn't strictly related to the above, so I'm happy to raise a separate issue/PR if you think this would be a good idea.

What do you think? cc @bskiba

**Comment by milesbxf** [comment]
An easier alternative I've just thought of is to make the step resolution time configurable, e.g. going from 30s resolution to 1h resolution. This will impact the accuracy of the history, but be a lot cheaper to run

**Comment by bskiba** [comment]
Definitely support the idea to use Prometheus client libtrary.

For the cluster history being to big.
Sharding queries seems to be a reasonable idea.
Downsampling seems a bit risky, especially with memory but I guess downsampled data is better than no data at all.
You might also consider shortening the history horizon instead of downsampling - this will be better for jobs that have daily patterns. However this will still need to be a cluster-wide setting rather than per-workload one.
  
The idea to
> dynamically load historical data for each VPA object we observe added to the cluster.
seems interesting, might be a bit harder to implement though. 
It's sort of inline with the memory saver mode as well, implemented as part of #1868 where only samples for containers that are actually autoscaled are being kept in memory so maybe we could think of skipping bootstrapping from history on init when memory saver mode is on and fetch on an as-needed basis.

**Comment by milesbxf** [comment]
> might be a bit harder to implement though.

Yeah, you're definitely right about that 😅 didn't know about the "memory saver mode", that's a neat idea.

For now, I'll start working on something that sticks to loading all data on startup, but splits queries up and uses the Prometheus library. We can refactor later to support dynamically loading history.

**Comment by milesbxf** [comment]
> You might also consider shortening the history horizon instead of downsampling

This gave me a better idea, which is sharding by time. E.g. instead of doing a single 8 day query, it's much more efficient to do eight 1-day queries. This fits very well with how Prometheus actually stores and indexes data too.
