### ISSUE TITLE
[Cluster AutoScaler] Process stuck in Decreasing State with bad Arithmetic

### ISSUE THREAD

**Issue by djsly** [kubernetes/autoscaler#2594]
```
11/28/2019, 1:11:50.000 PM	E1128 13:11:50.405508 1 static_autoscaler.go:240] Failed to fix node group sizes: failed to decrease aks-linux-37536111-vmss: attempt to delete existing nodes targetSize:26 delta:-1 existingNodes: 26	
11/28/2019, 1:11:50.000 PM	I1128 13:11:50.405450 1 utils.go:514] Decreasing size of aks-linux-37536111-vmss, expected=26 current=25 delta=-1	
11/28/2019, 1:11:40.000 PM	E1128 13:11:40.357515 1 static_autoscaler.go:240] Failed to fix node group sizes: failed to decrease aks-linux-37536111-vmss: attempt to delete existing nodes targetSize:26 delta:-1 existingNodes: 26	
11/28/2019, 1:11:40.000 PM	I1128 13:11:40.301802 1 azure_manager.go:261] Refreshed ASG list, next refresh after 2019-11-28 13:12:40.301787203 +0000 UTC m=+671124.369921116	
11/28/2019, 1:11:40.000 PM	I1128 13:11:40.357439 1 utils.go:514] Decreasing size of aks-linux-37536111-vmss, expected=26 current=25 delta=-1	
11/28/2019, 1:11:30.000 PM	I1128 13:11:30.203219 1 utils.go:514] Decreasing size of aks-linux-37536111-vmss, expected=26 current=25 delta=-1	
11/28/2019, 1:11:30.000 PM	E1128 13:11:30.203299 1 static_autoscaler.go:240] Failed to fix node group sizes: failed to decrease aks-linux-37536111-vmss: attempt to delete existing nodes targetSize:26 delta:-1 existingNodes: 26	
11/28/2019, 1:11:19.000 PM	I1128 13:11:19.543331 1 utils.go:514] Decreasing size of aks-linux-37536111-vmss, expected=26 current=25 delta=-1
```

It's the fourth time I reach this state. The only way to fix it would be to restart the AutoSCaler. 

My initial guess is that this is related to the VMSS + CA integration in AKS.

/assign @feiskyer

**Comment by djsly** [comment]
AKS: 1.14.7
AutoScaler Version: 1.3.0_v0.0.5 (taken from my bet bet: image: aksrepos.azurecr.io/mirror/cluster-proportional-autoscaler-amd64:1.3.0_v0.0.5)

**Comment by djsly** [comment]
probably a duplicate of #2538

**Comment by Starblade42** [comment]
Isn't this where the issue is? https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/core/static_autoscaler.go#L500 It keeps saying that the Expected and Current node size is the same in the function `DecreaseTargetSize`, which refreshes the VMSS size/cache when appropriate:
`Decreasing size of vmss-agent-worker-11prodva7-ieoin, expected=15 current=14 delta=-1`

But `DecreaseTargetSize` is determinining that the current size and the expected size are the same:

`Failed to fix node group sizes: failed to decrease vmss-agent-worker-11prodva7-ieoin: attempt to delete existing nodes targetSize:15 delta:-1 existingNodes: 15`

It appears that the issue causing this error loop isn't the logic of DecreaseTargetSize, but of however it's determining `incorrectSize` and deciding that it needs to *call* `DecreaseTargetSize`

**Comment by feiskyer** [comment]
/assign @nilo19 

https://github.com/kubernetes/autoscaler/pull/2613 is working on the fix for this.
