### ISSUE TITLE
Question: Should nodes be deleted from kube after scale down?

### ISSUE THREAD

**Issue by francobellagamba** [kubernetes/autoscaler#27]
I'm writing a "cloud_provider" for Racspace, and while everything seems to be working _okay_, after a node is deleted it keeps in Kuebernetes as NotReady.

Is there anything my cloud provider should be doing to fire that node deletion?

Thanks!

**Comment by mwielgus** [comment]
@francobellagamba  Cool, happy to see a new cloud provider onboard. 

Cluster Autoscaler doesn't delete a node from K8S after it is deleted from cloud provider. It is the responsibility of K8S node controller. As the node is expected to report its status on regular basis, just after the node is removed from the cloud provider it gets to unready state and after a minute or so it should be completely gone. At least this is how it works on GCE.

Is Rackspace anyhow different? What happens if you remove the node manually on the cloud provider side?

**Comment by francobellagamba** [comment]
Hey, @mwielgus! Thanks for getting back :)
I am not part of Rackspace (just a user), and so, I have a minimal k8s installation, set up using kubeadm,
The thing is that when the node goes down, it gets flagged as NotReady, but it never disappears from K8s... 

Maybe there is something wrong with my k8s installation, if that's not a AS responsibility, perhaps I should look on that side?

Again
Thanks!

**Comment by francobellagamba** [comment]
Now that you pointed me to the node controller I'm seeing this there:
`Error determining if node kube-iad-minions-as1f265138 exists in cloud: Failed to find object`
So, I'll take a look over there!

Once I get this working I'm more than happy to contribute it back :)

**Comment by mwielgus** [comment]
Closing the issue. Please open a new one if you have any more problems/questions.
