### ISSUE TITLE
Question/support or possible feature request: separate configs/settings for separate node groups.

### ISSUE THREAD

**Issue by AXington** [kubernetes/autoscaler#2751]
We're running the CA on EKS and we're using a few different applications with different node types and AMIs and due to the nature of some of these applications we need to have alternate settings for these node groups. Primarily, we need to have separate settings for `--scale-down-utilization-threshold`. 

We attempted to run multiple autoscalers, but that seems like it's not supported, especially with an HA setup with leader elect enabled. 

Is this currently possible and is there anything on the roadmap for supporting this?

**Comment by AXington** [comment]
Oh, and the other setting or something really useful would be to have a different wait for terimation/scaleup/etc... so that if the nodes for one app scales down, and another group would trigger a scale down, have those on separate timers...

**Comment by MaciekPytel** [comment]
Currently all those are global options, you can't set them per-nodegroup. Running multiple CAs is not officially supported, but I talked with some people who made it work for them. In general you'd need to run CA per-namespace and make it so that every node can only run pods from a single namespace (so that each CA manages a disjoint set of both pods and nodes). Running in different namespaces should also solve leader election issues (you must pass --namespace to each CA).

Regarding support for per-nodegroup config: as far I'm aware no-one is working on this, so it probably won't happen anytime soon (unless you want to give it a go?). My feeling is it should be doable for flags that are related to node-level checks (ex. utilization threshold, scale-down-unneeded-time), though it would probably require quite a bit of re-structuring code. For global checks (ex. scale-down-delay-after-add) you'd probably need even more changes - I suspect it may not be worth the effort for those.

**Comment by MaciekPytel** [comment]
With #3789 CA now has a mechanism to set scale-down-uneeded-time and thresholds for each nodegroup. However, to actually use it requires a provider-specific implementation of how the values are configured (since the best way to do it is likely to differ between providers).
