### ISSUE TITLE
TemplateNodeInfo has an extra kube-proxy

### ISSUE THREAD

**Issue by JulienBalestra** [kubernetes/autoscaler#2891]
Regarding the current codebase, when building a node template we inject a kube-proxy with a cpu request [here in gcp for example](https://github.com/kubernetes/autoscaler/blob/1c17cb3eae6f6681605acafbbbd3e75065f5d625/cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go#L336).

In our setups, we have cluster with a kube-proxy as daemonset instead of a static pod, in some others we use cilium as replacement of kube-proxy.

In both cases, this default kube-proxy is not needed. I was wondering why we have this included by default.

**Comment by MaciekPytel** [comment]
> I was wondering why we have this included by default.

Because, AFAIK, static pod remains a default way of running kube-proxy. TemplateNodeInfo is really based on a ton of guesswork and it's generally not very precise. There is no way (that I know of) to predict if static pod kube-proxy will be running on a node or not.
Feel free to add a flag to skip adding the kube-proxy to node template (though it will have to be a per-provider flag). Unless you have a better idea to address that?
