### ISSUE TITLE
cluster-autoscaler:  cluster expansion slow

### ISSUE THREAD

**Issue by ytcisme** [kubernetes/autoscaler#2947]
The version of cluster-autoscaler I used is 1.15.4.
If there are some pods configured podAntiAffinity, the cluster can only expand one node at a time. That is too slow for me. Is there any way to change it?
Thanks.

**Comment by bmcstdio** [comment]
We're using CA 1.14.6 and we are also observing this behaviour while using EKS. We need to scale from, say, 3 nodes to 24 nodes and back to 3 nodes based on a schedule, and to achieve that we use a `Deployment` with pod anti-affinity rules which we scale up and down. However, when scaling up, CA only creates one node at a time, which makes the process very slow. Is there a way to make it launch more than one node at a time?

**Comment by MaciekPytel** [comment]
It's a longstanding known issue (details: https://github.com/kubernetes/autoscaler/issues/257). It should be fixed/mitigated with scheduler and autoscaler migrating to scheduler framework in 1.18. Note that SF migration was a complete rewrite of large part of autoscaler internals and so there is no way to port it to older versions. 

My main recommendation is: don't use anti-affinity unless there is absolutely no other way (and probably not even then). For @bmcstdio case - if it's not a security issue using a hostport in your deployment is one trick to enforce placing each pod on a different node; otherwise I recommend using placeholder pods that request 1 node worth of resources as documented here: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-configure-overprovisioning-with-cluster-autoscaler.

Even in 1.18 scheduler framework only fixes some of issues with pod anti-affinity - it remains prohibitively expensive computationally (because of reflective nature and arbitrary label matching) and I very much doubt it will ever work reasonably well in large clusters. Pod Topology Spreading (https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/) seems to be a replacement for anti-affinity that is not broken by design, but it's not yet supported well by autoscaler. Personally I expect it to become the way to go in all use-cases currently involving pod anti-affinity once it's fully integrated, but it's not going to happen at least until 1.20.

**Comment by bmcstdio** [comment]
@MaciekPytel thank you very much for the explanation, as well as for the recommendation. Using a host port (which in our case is fine I guess as we don't actually listen on said port) worked like a charm. 🎉

**Comment by TBBle** [comment]
I was looking at [Pod Topology Spread Constraints](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/), and I'm not sure it provides a full replacement for pod self-anti-affinity, i.e. the thing for which `hostPort` is a workaround. If I understand correctly, you can only set the maximum _skew_. This means that if there is one instance of the pod on each acceptible node, the constraint allows putting a second pod on one of the nodes, rather than leaving it unschedulable in order to trigger Cluster Autoscaler.

Or is the idea that Cluster Autoscaler will actively get involved in this mechanism, and redirect such a request into a new-node scale-up?

The use-case I hit this with is NGINX Ingress on EKS behind an AWS Network Load Balancer, with `sourceTrafficPolicy: Local` set.

In this case, the NLB distributes traffic equally across *nodes* (only the ones with NGINX Ingress Pods). So if two NGINX Ingress Pods are on the same node, they will share one node's worth of traffic, because the NLB won't know to send more traffic to that node. This means adding pods fails to actually reduce the average load on each Pod, and the Horitzontal Pod Autoscaler is totally bamboozled.

**Comment by MaciekPytel** [comment]
There is no special integration between pod topology spreading and CA and I think your prediction as to what will happen is correct. Unfortunately it turns out pod topology spreading brings other problems too, especially when using zone topologyKey - it can lead to one at a time scale-up similar to pod antiaffinity and, while it guarantees even spread between zones it also prevents fallback from one zone to the other (which in most cases defeats the purpose of spreading pods between zones in the first place). 

It seems I was overly optimistic in my comment above :(.

**Comment by TBBle** [comment]
It might be possible to implement the pod-level antiAffinity beaviour with extended resources instead. It would require a new controller, but it seems like it'd be feasible to have one that recognises a particular extended resource name patter, and then adds a single one to all nodes that match the other constraints (`nodeSelector`, `tolerations`, other resources). This _almost_ makes sense for the `externalTrafficPolicy: Local` case, since it expresses the idea that an NLB is only going to see one destination per pod.

It feels like this is working around an issue in CA though, so I guess the best solution is still to actually implement #257 (using predicateMetadata during binpacking, if I'm following it correctly.)

**Comment by MaciekPytel** [comment]
The extra resource solution would run into the same problem as GPUs do:
1. A pod is pending which triggers scale-up.
2. A new node becomes ready. It doesn't have the custom resource yet (since the controller haven't reacted yet). 
3. The pod is still pending and CA triggers another scale-up, because it doesn't know that custom resource capacity will soon be added to the new node.

With GPUs we solve it by making CA aware that a pod with some specific label is expected to have GPU and the node is not really ready until some GPU capacity shows up (the label is hard-coded for each provider). You'd need a similar type of hack in CA for your custom resource to avoid unnecessary additional scale-ups.

Re: #257 - it should no longer be necessary with scheduler framework; cluster snapshot provides an alternative way of injecting all relevant information into scheduler simulations. The original issue of node scaling-up one by one should be fixed in 1.18. Pod antiaffinity is still computationally expensive though, so it's likely to make CA very slow in large clusters (hundreds of nodes).

**Comment by TBBle** [comment]
Ah, great. It wasn't clear from the bug report and discussion whether the 1.18 changes had actually solved this problem, or simply allowed the problem to be solved.

**Comment by TBBle** [comment]
/remove-lifecycle rotten

That said, do we consider this fixed by the 1.18 release.

**Comment by ericandrewmeadows** [comment]
> With GPUs we solve it by making CA aware that a pod with some specific label is expected to have GPU and the node is not really ready until some GPU capacity shows up (the label is hard-coded for each provider). You'd need a similar type of hack in CA for your custom resource to avoid unnecessary additional scale-ups.

@MaciekPytel Is this available somewhere?  It is driving me up a wall that it goes so slow!

**Comment by MaciekPytel** [comment]
@ericandrewmeadows Not sure what you're asking about? Some sort of custom resource based solution? If so it is not and I don't think anyone is working on that (and, frankly, it seems more like a DIY/fork type of solution given that it would require a custom controller to manage the resource in the first place).

For 1 pod per node case hostport hack is still probably the easiest way to do this. Pod antiaffinity should work better in 1.18 than in earlier versions, but I haven't actually tested it so I don't know for sure. The improvement (if any) is a result of a large internal refactor and there is no way to backport it to older version.
