### ISSUE TITLE
"Pod … marked as unschedulable can be scheduled on existing node" ignores Affinity

### ISSUE THREAD

**Issue by pdbogen** [kubernetes/autoscaler#2977]
CA is reporting that a pod is schedulable on any of several nodes, but none of these nodes satisfy the pod's PodAntiAffinity. As a result, the pod is stuck in Pending.

It seems like in this case CA should realize that none of the nodes satisfy the pod's affinities, and provision a new node.

We're currently using CA 1.17.0-alpha.1. I'll start the process of upgrading to 1.17.1, if that seems likely to be related.

**Comment by MaciekPytel** [comment]
IIRC there were indeed some last minute problems we found in 1.17 integration with scheduler. Those should be fixed in stable release.

CA relies on directly importing scheduler internals and as scheduler code changes it sometimes break CA. The purpose of -alpha and -beta builds of CA is mostly to test for this kind of issues and we fairly often find those issues in them. I would very much recommend using those builds only for testing and never in any sort of production environment.

**Comment by pdbogen** [comment]
Understood.

Is it the case that we should be matching CA major/minor (e.g., 1.13) with kube version? (Which we _weren't_ doing, but which I implemented on our UAT clusters yesterday.)

**Comment by MaciekPytel** [comment]
> Is it the case that we should be matching CA major/minor (e.g., 1.13) with kube version?

Probably yes. CA works by importing scheduler code to check if scheduler would be able to schedule pending pods if more nodes were added. If scheduler code embedded in CA ever disagrees with scheduler running in cluster, you'll get incorrect autoscaling decisions.
Each CA version uses scheduler code from corresponding k8s version (so 1.13 CA imports 1.13 scheduler, 1.14 CA imports 1.14 scheduler, etc) and running matching versions is the only setup we test.

That being said, relevant logic in scheduler is not changing all that much (at least before 1.18). In most practical scenarios you're _probably_ going to be fine using a newer CA version if you really need a feature that was only added in later version. No-one is going to give you any guarantees though (and the larger the version skew the more risky it becomes).

**Comment by pdbogen** [comment]
Thanks; I'll check in again if we encounter this issue using supported versions of CA.
