### ISSUE TITLE
Create e2e test for PodAntiAffinity in Cluster Autoscaler Scaler Up

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/autoscaler#30]

**Comment by davidopp** [comment]
@bsalamat can suggest a good scenario to test

**Comment by bsalamat** [comment]
I haven't looked at the Cluster Autoscaler (CA) yet, but given an issue we have seen recently, I wonder if CA handles the following scenario correctly:
1. There are N pending pods in the cluster.
2. CA determines that the N pods need a total of X amount of resources and M additional nodes will provide the X amount of resources. (M < N)
3. CA simulates the addition of M nodes and finds out that the N pods still won't fit due to PodAntiAffinity rules.

Does CA try increasing M up to N to check whether more nodes can fit the pending pods?

**Comment by mwielgus** [comment]
We use binpacking to estimate the number of needed nodes. We sort the pods by decreasing amount of requested resources and try to put the pods on by one to the "new" nodes. If none of the nodes is able to accommodate the pod then a new node is added. We use the full set of predicates that the scheduler has.

**Comment by bsalamat** [comment]
> If none of the nodes is able to accommodate the pod then a new node is added.

Based on this statement and IIUC, the autoscaler should never give up growing the cluster for anti-affinity on the hostname, because it should keep adding new nodes until anti-affinity on the hostname is satisfied. In the worst case scenario, this happens when as many nodes as the pending pods are added to the cluster. So, the test scenario that I described earlier should always pass.

**Comment by mwielgus** [comment]
Yes, if all pods are in the same anti-affinity domain then the number of new nodes will equal to the number of pods.

**Comment by mwielgus** [comment]
Done with https://github.com/kubernetes/kubernetes/issues/47854
