### ISSUE TITLE
CA should check the VMSS provisioning state before scaling up

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/autoscaler#3018]
Because of various reasons, the VM provisioning may need a long period and hence VMSS scaling requests would time out.

On such cases, the following scaling requests should check the provisioning state and only continue to scale after it has been finished. If the VMSS is still under updating, then CA should log an error.

/kind bug
/area provider/azure

**Comment by marwanad** [comment]
If VMSS receives another scale request to the same resource, the VMSS goal resolvers will resolve the request to a new goal state and the older request will be pre-empted. If we block those requests, then it would take subsequently longer to scale to the right target size.

Is this referring to the `context deadline exceeded` errors? I think the reason the context timeouts is because of a bug in azure autorest where it doesn't respect the infinite timeout for a background context so the context times out after 15 minutes. Those errors are just logged and no action is taken by CA on those because we don't send back to CA core. The only case where a scale operation would "time-out" and back-off the node group is if there are still upcoming nodes after the 15 minutes decided by `MaxNodeProvisionTime`.

**Comment by feiskyer** [comment]
@marwanad No, it's not related with context daedline exceeded issue. VMSS goal state won't be preempted if the previous operation has been finished yet, hence we need to ensure no more requests are sent to VMSS if it is still under scaling. In this case, longer time for scaling is expected.

**Comment by marwanad** [comment]
@feiskyer It would either get pre-empted or a different goal state would be detected and it would move towards - in the majority of cases, its the latter. I guess that would depend on if an update operation has been sent to the fabric or not.

I don't think we should add another one of those "log the error and continue" . It's still a registered scale up request in CA and CA will be expecting some nodes to come up as a result of that. If anything, send the error back so CA can backoff scaling that nodegroup. Again, this would make scaling slower for certain scenarios. 

Take the following scenario:
If you have a single nodegroup, and abruptly add 5k pods, the first scale decision would probably be not what make all the pods schedulable. Next loop comes and you can't scale because you're waiting for the first operation and depending how backed-off you are, it would take longer to get the pods schedulable again.
