### ISSUE TITLE
CA is ignoring priority expander configuration

### ISSUE THREAD

**Issue by lukczarnota** [kubernetes/autoscaler#3026]
Hi,

we have ocp cluster configured with autoscaler v1.15.5 and Kubernetes Version: v1.11.0+d4cacc0.

Our current config:

apiVersion: v1
data:
  priorities: |-
    50:
      - .*Spot.*
kind: ConfigMap

Troubleshooting:

- Scalling down all compute instances and autoscaler pods.

- Scale up autoscaler pods

- Check logs and new nodes

Our intention is to have only spot instances running.

Some logs from CA:

I0406 12:15:49.379231       1 priority.go:118] Successfully loaded priority configuration from configmap.
W0406 12:15:49.379271       1 priority.go:91] Priority expander: node group cf-eng-ocp-1-node-scale-group-App-a-1584997822-OCPNodeASG-BBBY5KMF0FVM not found in priority expander configuration. The group won't be used.
W0406 12:15:49.379290       1 priority.go:91] Priority expander: node group cf-eng-ocp-1-node-scale-group-App-b-1584997822-OCPNodeASG-11KHHB2XLY59Q not found in priority expander configuration. The group won't be used.
W0406 12:15:49.379304       1 priority.go:91] Priority expander: node group cf-eng-ocp-1-node-scale-group-App-c-1584997822-OCPNodeASG-4CINZVQA19PT not found in priority expander configuration. The group won't be used.
I0406 12:15:49.379321       1 priority.go:167] priority expander: cf-eng-ocp-1-node-scale-group-Spot-Compute-a-1584997822-OCPNodeASG-HR4GMXZNQEQB chosen as the highest available
I0406 12:15:49.379331       1 priority.go:167] priority expander: cf-eng-ocp-1-node-scale-group-Spot-Compute-b-1584997822-OCPNodeASG-1MU8NRSNI1VM2 chosen as the highest available
I0406 12:15:49.379334       1 priority.go:167] priority expander: cf-eng-ocp-1-node-scale-group-Spot-Compute-c-1584997822-OCPNodeASG-HS4EBALFNRSV chosen as the highest available

It loaded properly priority expander config but then it's ignoring it and scaling up App and Spot ASG instead of Spot only.

I0406 12:15:49.379503       1 scale_up.go:525] Splitting scale-up between 6 similar node groups: {cf-eng-ocp-1-node-scale-group-Spot-Compute-b-1584997822-OCPNodeASG-1MU8NRSNI1VM2, cf-eng-ocp-1-node-scale-group-App-a-1584997822-OCPNodeASG-BBBY5KMF0FVM, cf-eng-ocp-1-node-scale-group-App-b-1584997822-OCPNodeASG-11KHHB2XLY59Q, cf-eng-ocp-1-node-scale-group-App-c-1584997822-OCPNodeASG-4CINZVQA19PT, cf-eng-ocp-1-node-scale-group-Spot-Compute-a-1584997822-OCPNodeASG-HR4GMXZNQEQB, cf-eng-ocp-1-node-scale-group-Spot-Compute-c-1584997822-OCPNodeASG-HS4EBALFNRSV}
I0406 12:15:49.379520       1 scale_up.go:533] Final scale-up plan: [{cf-eng-ocp-1-node-scale-group-Spot-Compute-b-1584997822-OCPNodeASG-1MU8NRSNI1VM2 0->1 (max: 6)} {**cf-eng-ocp-1-node-scale-group-App-a-1584997822-OCPNodeASG-BBBY5KMF0FVM** 0->1 (max: 6)}]

All App and Spot node groups have this same tag  node-role.kubernetes.io/compute: true

**Comment by MaciekPytel** [comment]
The problem is the line "Splitting scale-up between 6 similar node groups" - this is the balancing logic that happens after the expander is run. Basically expander picks a node group, but after that the scale-up is split between this group and all other 'similar' groups. This is intended to keep the number of nodes in different zones identical, but in your case it doesn't distinguish between spot/non-spot (it considers those to be different 'zones'). 
What you need to do is either disable balancing logic (--balance-similar-node-groups=false) or add some kubernetes label to all spot nodes (node groups producing nodes with different set of labels are no longer considered similar).

**Comment by cliles** [comment]
I also have a similar issue where it is perceived that the priority expander is ignored.

I would be curious to understand how other spot adopters are handling priority. In my use I would like to leverage the priority expander to provide "backup" on-demand node groups for spot instance based node groups. Since all groups share the same set of tags, the cluster-autoscaler considers them similar for balancing.
