### ISSUE TITLE
High CVE's in cluster autoscaler

### ISSUE THREAD

**Issue by Disgruntled** [kubernetes/autoscaler#3128]
Specifically versions 1.15.5 and 1.15.6 tested 

A container image vulnerability scan by such tools as Jfrog Artefactory Xray and AWS ECR show that there are several "High" and even more low/informational CVE's in the cluster-autoscaler container. While these CVE's are not linked to cluster autoscaler itself, it's making a bit of pain for security teams and certainly introduces some risk at some level.

Even if there is no code path to execute any of the Highs, I am sure this is creating pain for developers and security personnel out there. There is certainly a large amount of toil when something is setting off so many alarm bells.

High's listed from 1.15.5:

CVE-2019-12900
CVE-2018-6485 
CVE-2018-1000001
CVE-2019-9169
CVE-2017-14062
CVE-2017-12424 
CVE-2016-2779 

Please take a look and remediate.

**Comment by MaciekPytel** [comment]
Those come from the base image we use. It is fixed in 1.16+ which migrated to distroless base image. Unfortunately this required significant changes (including to our dependencies) and I don't think we can backport it to 1.15. Also - technically speaking - as per Kubernetes policy [1] 1.15 is no longer officially supported. We're more relaxed about this policy than the rest of k8s and we will be releasing at least one more patch of 1.15 (and possibly more), but I'd rather avoid making very large changes like this.

We're currently using k8s.gcr.io/debian-base:v1.0.0 image in 1.15 - I see there is 1.0.1 version of it available and I can bump it in 1.15.7. Can you run the scanners you mentioned on this image and see if it helps with any of the issues you listed?

FWIW I don't believe CA uses any of the affected libraries or offers any other attack surface that would expose those vulnerabilities. But I certainly do get your point about alerts causing pain and increasing risk of missing a truly critical alert. 
 
[1] https://kubernetes.io/docs/setup/release/version-skew-policy/#supported-versions

**Comment by Disgruntled** [comment]
Yeah once 1.15.7 is published I'll put it through the scans again.

And thanks, I am sincerely appreciative for your quick response.

Noted on the  1.15 support. I work for a large enterprise and it takes us more than a moment to increment the k8s version. We'll get upgraded eventually, but if we can tackle this issue immediately it would still be vastly beneficial.

Thank you again

**Comment by Disgruntled** [comment]
Actually, I got a little out of my own way and pushed the v1.0.1 base image to ECR for scanning. Only one CVE was remediated , still shows 6 high (was 7 in cluster-autoscaler:v1.15.6).

Thus I would say it is safe to stand down on this issue and at least for my own purposes there's no need to increment the base image and re-release.

Though I would like to really thank you again for your reply. Your actions and that bit of information have directly helped set us on the right course.
