### ISSUE TITLE
Pods are not getting recreated in AUTO mode

### ISSUE THREAD

**Issue by soorya79** [kubernetes/autoscaler#3199]
i have created a deployment with VPA mode as "AUTO" im trying to check whether the pods are getting recreated .But its only happening for the first recommendation . Later the pods are not getting recreated even after the recommendation is changing.

**Comment by bskiba** [comment]
You can take a look at vpa-updater logs to see why the pods are not getting updated. Can you share what your recommendations is and what requests the pods have? Updater is quite conservative with updating pods, since it requires a restart and not every change of recommendation will cause a recreate.

**Comment by soorya79** [comment]
Okay... i'll attach a screenshot of the updater logs...
<img width="960" alt="VPA" src="https://user-images.githubusercontent.com/40618507/83849889-bc230500-a72d-11ea-879b-8aef84a651e0.PNG">

**Comment by soorya79** [comment]
i was trying out this example which i found online ...https://livewyer.io/blog/2019/06/24/vertical-pod-autoscaling/

And so i'am generating load to the pods ... i'am getting recommendation as the load gets increased but its not evicting the pods inorder to create pods with the new recommendation.

**Comment by bskiba** [comment]
The "not updating short-lived pod ... request within recommended range" indicate what is going on.

VPA generates three numbers as part of recommendation: Target, Upper bound and Lower Bound. Target is the actual recommendation. Upper bound and lower bound are sort of indicators of confidence of the recommendation. The more usage samples VPA gathers, the closer upper bound and lower bound will be to the Target. 
Short-lived pods are AFAIR those that have been running <24h. For those, we only restart pods for new recommendation if current request is outside (lower bound, upper bound) range. 

In general you should not expect very fast actions from VPA, it is more suited to following general trends in usage than reacting quickly. For quick reaction to spikes you should take a look at Horizontal Pod Autoscaler.

**Comment by soorya79** [comment]
but the upper limit seems to be the maximum capacity of my node in which the pod is running ...

**Comment by bskiba** [comment]
It might be even bigger. As I said, the upper bound it's going to slowly grow lower towards the target, it might take hours. How old is the pod?

**Comment by soorya79** [comment]
> It might be even bigger. As I said, the upper bound it's going to slowly grow lower towards the target, it might take hours. How old is the pod?

it's just 2 hours...

**Comment by soorya79** [comment]
Can you please tell me how the target value is being created?
So i have created a deployment and ran it for a while the vpa had suggested me the recommendations... i deleted that deployment and recreated it again .

**Comment by soorya79** [comment]
can you please explain how the recommendation target is being generated?
Because , firstly i created a deployment with a vpa ... the pods got reacreated for the first recommendation later the recommendation changed and i had waited for the pods to take up the new recommendation ... as it didnt happen i deleted the deployment along with vpa and deployed both of them again ... the first recommendation i got for the newly created deployment is the very last recommendation i received for the one i deleted earlier

**Comment by mig4** [comment]
We've just encountered this as well, I'm reopening to get some feedback cause something doesn't seem right and I'd like to find out if we should be doing something differently.

We're orchestrating deployments of multiple Prometheus servers each one monitoring a different cluster, and we're using VPA to manage requests/limits because each of those clusters is different in terms of metrics is exposes which in turn translates to different memory requirements for the responsible Prometheus server. We set requests and limits to the same value to avoid over-provisioning.

This has been working OK mostly, sometimes we do see churn with newly provisioned servers and it takes them a bit to settle, but not too long.

This time though this doesn't seem to be happening, I've got a pod that's < 2h old, the recommendations are:

- lower: 1.9 GB
- target: 4.9 GB
- upper: 8.4 GB

But the pod seems to be stuck with the previously recommended request/limit of 3.4 GB and it's been trying to start ~15 times now but it gets to a point when Prometheus allocates 3.4 GB of RAM (this usually takes ~10 minutes) at which point it gets OOM killed and the cycle repeats.

The only thing I see in the VPA updater log is the message like OP mentioned: `not updating a short-lived pod foo/prometheus-foo-0, request within recommended range`.

A couple of questions:

1. does this sound like expected behaviour and so just something we need to take into account?
2. what's the reasoning behind the _short-lived_ pod and 24 hours?
3. can we tweak any parameters to let VPA go through this cycle quicker?

/reopen
/remove-lifecycle rotten
