### ISSUE TITLE
Add vSphere support

### ISSUE THREAD

**Issue by heroku-miraheze** [kubernetes/autoscaler#3208]
vSphere is not supported in Cluster Autoscaler and i need to use vSphere as a provider to autoscale clusters, with Tanzu Kubernetes Grid.

**Comment by detiber** [comment]
@heroku-miraheze you could use the [clusterapi provider](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/clusterapi) for cluster-autoscaler, you will likely need https://github.com/kubernetes/autoscaler/pull/3203 in order to support providing separate kubeconfigs for the management and workload cluster, though.

Happy to help if you run into any issues, I'm currently working on testing the upstream Cluster API equivalent of this configuration.
