### ISSUE TITLE
CA setting scaleDownForbidden as true.

### ISSUE THREAD

**Issue by nomis-rzp** [kubernetes/autoscaler#3409]
CA did find some unneeded nodes to scale down but it's not scaling down because the scaleDownForbidden is getting set to true without much information in logs. There are was no recent scale down activities also.  Its on EKS cluster 1.16 with CA version 1.16.6. 

```
I0805 05:19:47.988924       1 static_autoscaler.go:429] ip-10-21-102-89.ap-south-1.compute.internal is unneeded since 2020-08-05 04:53:12.002288375 +0000 UTC m=+51587.265756422 duration 26m35.877236357s
I0805 05:19:47.988939       1 static_autoscaler.go:429] ip-10-21-103-44.ap-south-1.compute.internal is unneeded since 2020-08-05 04:45:37.471909594 +0000 UTC m=+51132.735377647 duration 34m10.407615132s
I0805 05:19:47.988950       1 static_autoscaler.go:429] ip-10-21-102-37.ap-south-1.compute.internal is unneeded since 2020-08-05 04:51:20.731638244 +0000 UTC m=+51475.995106292 duration 28m27.147886487s
I0805 05:19:47.988964       1 static_autoscaler.go:429] ip-10-21-102-201.ap-south-1.compute.internal is unneeded since 2020-08-05 05:02:17.680748004 +0000 UTC m=+52132.944216053 duration 17m30.198776726s
I0805 05:19:47.988975       1 static_autoscaler.go:440] Scale down status: unneededOnly=true lastScaleUpTime=2020-08-05 04:51:50.93377746 +0000 UTC m=+51506.197245562 lastScaleDownDeleteTime=2020-08-04 14:33:47.371005812 +0000 UTC m=+22.634473862 lastScaleDownFailTime=2020-08-04 14:33:47.37100589 +0000 UTC m=+22.634473948 scaleDownForbidden=true isDeleteInProgress=false scaleDownInCooldown=true
```
I enable V1 logs and CA logs it showed "No unschedulable pods" . Below part of the code
```
if len(unschedulablePodsToHelp) == 0 {
                scaleUpStatus.Result = status.ScaleUpNotNeeded
                klog.V(1).Info("No unschedulable pods")
```

Have any of you experienced this issue with autoscaler? Please help

Thanks.

**Comment by nomis-rzp** [comment]
Im still not able to figure it out.. Can anyone please help ?

**Comment by MaciekPytel** [comment]
The most likely reason is that CA blocks scale-down if it sees any pods that are pending, but can be scheduled on existing nodes. The reason for that is CA doesn't know where scheduler will place those pods and, rather than risk races, it waits until all the scheduling is done.

The symptoms you see are most likely to happen if CA disagrees with scheduler: CA thinks a pod can be scheduled in the cluster, while the scheduler thinks it can not. This would be signified by logs like this (or similar to this, depending on exactly how CA reached this conclusion):
```
"Pod <pod> marked as unschedulable can be scheduled on node <node>
```
It's perfectly normal if this happes for a loop or two, but if you see those logs for the same pod showing over and over that would indicate the problem I described. If it is the case the way to follow-up would be to:
1. Make sure you're using the version of CA that matches cluster version (ex. CA 1.16 with k8s 1.16, CA 1.17 with k8s 1.17, etc) and that you're not using any custom scheduler configuration, extensions, etc.
2. If none of the above is the case, the way to debug would be to try and figure out if it's scheduler or CA that is wrong. It's pretty much impossible to figure it out from the logs. Probably the best way is to look at the pod and node named in CA logs and try to figure out if the pod can indeed be scheduled on that node. 
2.1. If it can, my guess would be a corrupted scheduler cache which can be fixed by restarting scheduler. 
2.2. Otherwise it may be a bug in CA. But to have any chance of debugging it I'd need more data - ideally `kubectl describe` output for both pod and node logged by CA.

**Comment by ajcann** [comment]
Hi @MaciekPytel - I believe we're running into this as well and my understanding is this is a CA bug. In our case we had a pod pending with a toleration only a specific ASG/nodegroup could provide (The ASG is tagged with taint so I'm fairly sure CA is aware of it), this ASG could not scale up due to lack of instance availability. During this time our cluster scaled out a few other node groups (a few hundred nodes of various instance types) and these nodes were not able to be scaled down until I manually fixed the pending workload. Quite costly for us, unfortunately.

Is it correct to say that CA will never scale down *any* node groups so long as there is a pod pending even if it could never be scheduled on those nodes?

**Comment by nomis-rzp** [comment]
@ajcann My issue was different. We had another custom scheduler running in the cluster and that was preventing one of our pod from scheduling. Once we fixed that, CA started to scale down nodes..

**Comment by MaciekPytel** [comment]
Sorry for late reply, but addressing comment by @ajcann - ongoing scale-up in any nodegroup will completely block scale-down of the entire cluster. A pending pod which can't trigger scale-up (ie. one for which NoTriggerScaleUp events are emitted) will not block scale-down.

In case of lack of instance availability the impact will likely depend on specific cloudprovider - if a particular provider is able to quickly return [OutOfResources errors](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/cloud_provider.go#L229) than a particular nodegroup should be "backed off' as soon as those errors are returned, which will unblock scale-down in the rest of the cluster. If the provider doesn't implement this functionality and relies on 15 minutes scale-up timeout than scale-down will be blocked for significant part of the time (after 15 minutes timeout where scale-down is blocked nodegroup will go into 5 minute backoff where scale-down is enabled; subsequent backoffs will be longer, but even at maximum backoff duration of 30 minutes scale-down will be blocked for significant percentage of time).

GCE is the only provider that I know for sure implements OutOfResources errors. For other providers we'd need to ask their owners if they do.

**Comment by akloss-cibo** [comment]
This behavior is prone to creating deadlock-like behavior when scale-up limits are reached.  The scenario that just happened is that we hit the spot CPU limit for our account in AWS, which then caused pods to be unschedulable because the cluster couldn't scale up.  However, even when the workload that was using all the CPUs finished, the Pending pods couldn't be scheduled on the existing nodes due to various nodeSelectors, etc. so the cluster refused to scale down, and couldn't scale up.
