### ISSUE TITLE
Is Cluster autoscalar supported in VMSS worker nodes of Standard_HC44rs VMs

### ISSUE THREAD

**Issue by Sanghamitra-BEAGILE** [kubernetes/autoscaler#3410]
Hi Team,

We are using Kubernetes on Azure VMs which has its autoscaler is part of AKS Engine that is developed and supported via  Opensource https://github.com/Azure/aks-engine.

Our K8s version : v1.15.7

1. We tried to deploy VMSS + Clusterautoscalar (Helm version 7.3.2,7.3.3 & 7.3.4) on Standard_HC44rs VMs as worker nodes , we are getting errors in cluster autoscalar logs "Unable to build proper template node for nodes00-scaleset: instance type "Standard_HC44rs" not supported”  
 
Could you please let me know about it.

Is it that Standard_HC44rs VMs doesn't support Clusterautoscalar ?

Thanks,
Sanghamitra

**Comment by marwanad** [comment]
The instance type was added in K8s 1.19. I can help prepare cherry-picks for earlier releases up to 1.16. 

I'm not sure if we will be rolling out more patches for K8s 1.15 since it's going out of support soon.

@MaciekPytel Are we going to have more patch release for 1.15 sometime in the future? This is for back-porting https://github.com/kubernetes/autoscaler/pull/3311

Maybe we should evaluate building off SKUs API.

/area provider/azure

**Comment by Sanghamitra-BEAGILE** [comment]
Hi Marwanad,

Thanks for the information.

You mean Standard_HC44rs VMs are added in Kubernetes Version 1.19. or Cluster Autoscalar version 1.19.?

Thanks,
Sanghamitra

**Comment by marwanad** [comment]
Cluster Autoscaler 1.19. We can for sure backport the support back until1.16. 1.15 is a maybe.

**Comment by marwanad** [comment]
I've prepared the backports for all versions up and until 1.16.

I don't think 1.15 is possible since K8s has dropped support for that.

**Comment by Sanghamitra-BEAGILE** [comment]
Hey,

Thanks for the update.
