### ISSUE TITLE
calico-typha preventing scaling down

### ISSUE THREAD

**Issue by carpemonf** [kubernetes/autoscaler#3417]
Hi, I have `cluster-autoscaler` (tried v1.16-v.1.18) installed on OpenShift (v4.4.11). Scale up works well but I got the following error at the evaluation stage for scaling down:

```
I0807 10:35:02.518053       1 scale_down.go:462] Node 10.165.110.30 - cpu utilization 0.142967
I0807 10:35:02.518095       1 scale_down.go:462] Node 10.165.110.39 - cpu utilization 0.172379
I0807 10:35:02.518112       1 scale_down.go:462] Node 10.165.110.42 - cpu utilization 0.192839
I0807 10:35:02.518390       1 scale_down.go:511] Finding additional 3 candidates for scale down.
I0807 10:35:02.518506       1 cluster.go:93] Fast evaluation: 10.165.110.30 for removal
I0807 10:35:02.518774       1 cluster.go:248] Evaluation 10.165.110.39 for calico-system/calico-typha-6858d7ccdd-z6mz4 -> GeneralPredicates predicate mismatch, reason: node(s) didn't have free ports for the requested pod ports
I0807 10:35:02.518794       1 cluster.go:248] Evaluation 10.165.110.6 for calico-system/calico-typha-6858d7ccdd-z6mz4 -> GeneralPredicates predicate mismatch, reason: node(s) didn't have free ports for the requested pod ports
I0807 10:35:02.518809       1 cluster.go:248] Evaluation 10.165.110.42 for calico-system/calico-typha-6858d7ccdd-z6mz4 -> GeneralPredicates predicate mismatch, reason: node(s) didn't have free ports for the requested pod ports
I0807 10:35:02.518821       1 cluster.go:129] Fast evaluation: node 10.165.110.30 is not suitable for removal: failed to find place for calico-system/calico-typha-6858d7ccdd-z6mz4
I0807 10:35:02.518832       1 cluster.go:93] Fast evaluation: 10.165.110.39 for removal
I0807 10:35:02.518846       1 cluster.go:107] Fast evaluation: node 10.165.110.39 cannot be removed: pod with local storage present: ibm-cloud-provider-ip-169-50-105-34-78448bd686-9gpzf
I0807 10:35:02.518854       1 cluster.go:93] Fast evaluation: 10.165.110.42 for removal
I0807 10:35:02.518868       1 cluster.go:107] Fast evaluation: node 10.165.110.42 cannot be removed: non-daemonset, non-mirrored, non-pdb-assigned kube-system pod present: vpn-658b79b6c6-8tx4b
I0807 10:35:02.518883       1 scale_down.go:548] 3 nodes found to be unremovable in simulation, will re-check them at 2020-08-07 10:40:00.251125209 +0000 UTC m=+428.886803303
```

`calico` comes integrated in OpenShift and `calico-typha` is running in each of my worker nodes. `cluster-autoscaler.kubernetes.io/safe-to-evict` annotation is set to `true` and tried with both `--skip-nodes-with-system-pods=false` and `--skip-nodes-with-system-pods=true` without solving the issue.

The only difference I can see is that calico components are set by default for this OpenShift cluster in a `calico-system` namespace. I have seen that they are defined in the `kube-system` namespace at https://github.com/projectcalico/calico/blob/master/_includes/charts/calico/templates/calico-typha.yaml and that some `pod.Namespace == "kube-system"` are hard-coded in `cluster-autoscaler`. Do you think this might be causing this issue? If so, is there any configuration I can apply for fixing that?

EDIT: adding that calico was installed with the Tigera operator that installs resources in the calico-system namespace by default (https://docs.projectcalico.org/getting-started/kubernetes/quickstart)

**Comment by MaciekPytel** [comment]
safe-to-evict: true overrides any checks related to kube-system namespace, so it shouldn't be a problem. 

Fundamentally CA's job is to make sure all pods can be scheduled. CA will only ever delete a node if all pods running on this node will be able to schedule on other nodes in the cluster. In case of your calico-typha pods, only one of those can run on each node (due to port conflict). So if you run one of those on every node CA will never scale-down. You can't change this with any of the existing CA flags.

If you intent to run those pods on every node my recommendation is to use daemonset instead of deployment. DS pods don't block scale-down the way other pods do.

**Comment by Lovejeets** [comment]
Hi Everyone, this is an expected behavior when the node counts is 3 or less.

Reason being, by default, calico typha requires 3 replicas, and there can't be more than 1 calico typha pod in 1 node, so you’ll need at least 3 nodes in the system + user pools to make it work – otherwise CAS won’t scale down as it has no place to put the pod.
