### ISSUE TITLE
How to prevent node from scale down process 

### ISSUE THREAD

**Issue by anjanitsip** [kubernetes/autoscaler#3554]
I am using EKS Cluster and following below link to deploy CA.. 
  
https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html

I have added cluster-autoscaler.kubernetes.io/safe-to-evict="false" annotation on CA deployment.
--skip-nodes-with-system-pods=true
(Node - single m5.xlarge) 

I have statefulsets of postgreSQL with master and slave node. I don't want to reschedule db  pods on other nodes . Added PDB to sts. But still db pods are getting reschedule on other node.

 

Below configuration is also not working for me --
 "cluster-autoscaler.kubernetes.io/scale-down-disabled": "true"  
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-prevent-cluster-autoscaler-from-scaling-down-a-particular-node

**Comment by Unichron** [comment]
If you really added the "cluster-autoscaler.kubernetes.io/scale-down-disabled": "true" annotation to the node correctly (please double check) then it's probably not a CA problem. If the node in question is part of an autoscaling group, it could be caused by an AZ Rebalance event, which can be disabled in the aws console.
