### ISSUE TITLE
cluster-autoscaler-chart chart 1.0.5 and 1.1.0 releases are missing

### ISSUE THREAD

**Issue by pierluigilenoci** [kubernetes/autoscaler#3605]
Ref: 
`wget https://kubernetes.github.io/autoscaler/index.yaml`

**Comment by pierluigilenoci** [comment]
@bskiba could you please take a look?

**Comment by Kydybets** [comment]
same for me

**Comment by ygrosu** [comment]
same here

**Comment by pierluigilenoci** [comment]
@tghartland @displague @Ladicle could you please help?

**Comment by pierluigilenoci** [comment]
@mwielgus or @maciekpytel maybe you?

**Comment by prios-peter-olivo** [comment]
I am having this issue as well :(

**Comment by gjtempleton** [comment]
For future reference, I'm currently the best person to tag on any issues with the CA's Chart as per the [Chart directory's OWNERS file.](https://github.com/kubernetes/autoscaler/blob/master/charts/OWNERS)

I've just raised the PR to add these as #3617 -  due to the branch protection enforced on this repo the automated push to the gh-pages branch method used by the Helm chart releaser action fails when attempting the second part of the action. This is a known issue, and at the moment means that we have to follow up releases with manual pull requests as here meaning that the versions accessible to helm may lag behind the published artifacts - I'll raise a PR to make this clearer in the chart docs going forward.

**Comment by gjtempleton** [comment]
Closing as #3617 has been merged and validated fetching both `1.0.5` and `1.1.0` locally.

/close

**Comment by pierluigilenoci** [comment]
Thank you!
