### ISSUE TITLE
Cluster autoscaler patch releases

### ISSUE THREAD

**Issue by benmoss** [kubernetes/autoscaler#3611]
With the latest CAPI changes that have landed in the cluster autoscaler, can we have a set of patch releases for 1.17, 1.18, and 1.19?

`<copy-pasta from #3317>`
Tagging all cloudprovider owners for visibility:
cc: @ringtail @Jeffwan @jaypipes @feiskyer @marwanad @nilo19 @hello2mao @frobware @enxebre @elmiko @hardikdr @detiber @ncdc @andrewsykim @MorrisLaw @tghartland @mwielgus @gjtempleton @MaciekPytel 
`</copy-pasta>`

**Comment by MaciekPytel** [comment]
Sorry for the delay. I'm planning to build Cluster Autoscaler patch releases for all active branches on Monday 2020-11-02. 
If you have any other bugfix cherry-pick PRs you want included, please leave a comment here.

Tagging all cloudprovider owners for visibility (the list seems to have grown since #3317):
cc: @ringtail @Jeffwan @jaypipes @feiskyer @marwanad @nilo19 @hello2mao @frobware @enxebre @elmiko @hardikdr @detiber @ncdc @andrewsykim @MorrisLaw @tghartland @mwielgus @gjtempleton @RainbowMango @kevin-wangzefeng @d-mo @deitch @displague @gianarb (once again, really sorry if I missed anyone)

**Comment by detiber** [comment]
Backport PRs for the Packet (Metal Equinix) Provider: https://github.com/kubernetes/autoscaler/pull/3654, https://github.com/kubernetes/autoscaler/pull/3655, https://github.com/kubernetes/autoscaler/pull/3656

**Comment by MaciekPytel** [comment]
I've released 1.19.1. I'll continue with other releases tomorrow. Please let me know if I missed something or got something wrong in release notes and I'll fix it.

**Comment by MaciekPytel** [comment]
Released 1.16.7, 1.17.4, 1.18.3 and 1.19.1. Once again - please let me know if there are any corrections required in release notes.
