### ISSUE TITLE
Local cluster scaling based on Wake-on-Lan

### ISSUE THREAD

**Issue by scsinke** [kubernetes/autoscaler#3614]
Besides cluster scaling by cloud providers, maybe people like to see a way to run this locally?

**Comment by miguescri** [comment]
Apparently adding new providers is difficult right now due to lack of maintainers. See #3204

**Comment by muvaf** [comment]
I can take a shot at this if it's something maintainers would want to merge upstream. I am not familiar with the codebase so what I have in mind could be very off.

I'm thinking of using a `ConfigMap` in `kube-system` as data store that has the information to issue Wake-on-LAN signals like MAC and broadcast mask. Shutdown could be implemented by issuing a `shutdown` command to the machine assuming autoscaler has SSH access to the machines.

Alternatively, we can have a shim in autoscaler that just makes changes to a custom resource whose controller is installed by the user. So, instead of talking to Cloud Provider API, it'd talk to Kubernetes API and manipulate the CRs of that controller which has everything it needs to manage the machines and released separately (maybe even replaced by different community controllers as long as CRD schema is respected)

**Comment by migueleliasweb** [comment]
I'm after a solution for this as well. I have a home lab that I would love to add this kind of functionality. I reckon once 
https://github.com/kubernetes/autoscaler/issues/3644 is merged it becomes a matter of time (not much for a simple-ish autoscaler) to get this working.

**Comment by ryanpeach** [comment]
Cool, now I wonder if anyone's written a plugin?

**Comment by LaneaLucy** [comment]
Could this be used for nodes, that are already provisioned and only need to be started/stoped?
