### ISSUE TITLE
Cut off k8s.io/kubernetes dependencies

### ISSUE THREAD

**Issue by sttts** [kubernetes/autoscaler#368]
This repo has quite a number of k8s.io/kubernetes dependencies which probably should not exist. E.g. the `schedulercache.NodeInfo` is an internal of the scheduler and should not leak into other repos. 

Hence, I suggest to proactively cut off these dependencies, either by copying them here or by promoting the relevant k8s.io/kubernetes code to k8s.io/client-go or k8s.io/api.

**Comment by MaciekPytel** [comment]
Cluster Autoscaler works by simulating how would scheduler behave if we added or removed some nodes from the cluster. In other words we directly run scheduler predicates (but not priorities) against internally simulated nodes, which involves plenty of creating, copying and modifying of schedulercache.NodeInfo.

We don't want to copy scheduler code over to this repo, because our goal is to accurately predict scheduler behavior and so we want to stay in sync with scheduler code as much as possible. In the end of the day, what we want to do is to run some internals of scheduler shipped with current k8s version inside autoscaler. So to remove dependencies to k8s.io/kubernetes we'd need to have half of scheduler code (kubernetes/plugin/pkg/scheduler/algorithm/ and everything it depends on) in client-go.

**Comment by mwielgus** [comment]
Closing as not-fixable.
