### ISSUE TITLE
Packet Autoscaler Scale up error

### ISSUE THREAD

**Issue by justgotthis** [kubernetes/autoscaler#3710]
Scaled up my deployment and eventually received this error for some pods:

  Warning  Failed     11m (x5 over 14m)     kubelet, ca-k8s-worker01  Failed to pull image "nginx": rpc error: code = Unknown desc = Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
  Warning  Failed     11m (x4 over 14m)     kubelet, ca-k8s-worker01  Error: ErrImagePull
  Normal   BackOff    4m51s (x26 over 14m)  kubelet, ca-k8s-worker01  Back-off pulling image "nginx"

Takes about 10 minutes to scale up one node up to three nodes to accomodate. In that timeframe, I received the error above so maybe put in some logic to prevent this from happening?

**Comment by paranoidsp** [comment]
This does not seem to be a scale up error, this is because you seem to have hit rate limits on dockerhub for pulling your docker image.

**Comment by justgotthis** [comment]
Thanks for getting back to me. Just to clarify, i scaled up my deployment
and since the scaling took 10 minutes, i suppose it kept trying to pull the
image repeatedly which caused this error? Is there any best practice for
this besides just upscaling more in a piecemeal fashion? Shouldn't the pods
that don't have a home stay pending and not try to download the image
repeatedly?

**Comment by detiber** [comment]
> Thanks for getting back to me. Just to clarify, i scaled up my deployment
and since the scaling took 10 minutes, i suppose it kept trying to pull the
image repeatedly which caused this error? Is there any best practice for
this besides just upscaling more in a piecemeal fashion? Shouldn't the pods
that don't have a home stay pending and not try to download the image
repeatedly?

The only pods that would be attempting to download the image are ones that are already scheduled.

I suspect there may be something else that is delaying the scale up, but 10 minutes does not seem like an unreasonable amount of time to bootstrap the 2 additional instances

**Comment by detiber** [comment]
Ah, I think I understand the scale up issue a bit more now after seeing https://github.com/kubernetes/autoscaler/pull/3720, it appears that pods that are currently in backoff from a previous scale up event will prevent additional scale up events from happening, it looks like this is currently by design in cluster-autoscaler core currently.

**Comment by justgotthis** [comment]
Thanks for the explanation. It's still confusing how the pods still
received the image pull error.

These were my steps:

- Spun up 1 master/1 worker Kubernetes cluster
- Scaled my deployment from 5 replicas to 500 replicas
- Cluster scaled 2 additional nodes but I noticed some pods had the image
pull error (reached docker limit)

My question is, I'm assuming that the pods that were in Pending state did
not land on any nodes as of yet so not sure why it was trying to download
images repeatedly when the pods did not have a home yet as the cluster was
being scaled.

Thanks for your help,
-Luis.

**Comment by detiber** [comment]
@justgotthis I don't believe the error is caused by yet to be scheduled pods, but by pods that were already scheduled and in ImagePullBackOff. Depending on the number of layers in the image and the pull policy on the pods I wouldn't be surprised if it was relatively easy to hit the docker api limits pretty quickly during large scale up events

**Comment by justgotthis** [comment]
Makes sense, maybe I scaled up too fast which made me hit the limit. Thanks!

**Comment by detiber** [comment]
@justgotthis I'm going to close out this issue for now, feel free to re-open if there are additional issues related to this.
/close
