### ISSUE TITLE
NodeGroup specific resource limiter

### ISSUE THREAD

**Issue by Kafei59** [kubernetes/autoscaler#3726]
Hello the cluster-autoscaler team,
I am benchmarking and testing your solution to autoscale nodes for a cloud provider solution.

I had no issue implementing our provider to your code, although, I found something quite strange and I'd rather talk to one of you before trying to code something up :)

I did not find any way to specity to a NodeGroup its own resource limit.
In a way, I would like to specify the cpu/mem limits for ONE particular node group (returned by the cloud provider resource).

For example: our customers may need to expose a specific limits to 80-90% cpu on non-mandatory instances in a NodeGroup but 60% max on a mandatory group for its cluster.

Here, limits are only customizable in the auto-scaler global options, did I miss something ? Or why is it this way ?
Are you interested if I create a pull-request to add these new optional data in the NodeGroup structure ?

Have a nice day and thanks for you work !

**Comment by MaciekPytel** [comment]
There is some general discussion about being able to configure various options per-nodegroup in  https://github.com/kubernetes/autoscaler/issues/3583. This is a fairly popular request and I'd like to get on it very soon.

It's not entirely clear to me what you mean by "resource limits" though? Do you mean `--scale-down-utilization-threshold`? If so this is already very much in scope of #3583. 

If you mean ResourceLimiter than I don't see how it would be useful at NodeGroup level. ResourceLimiter is basically a cluster-wide equivalent of NodeGroup min/max size. If you have dozens of NodeGroups, specifying min/max for each doesn't really give you much control over the total size of cluster (since CA can just go and scale-up a different NodeGroup after maxing the first one). To address this you can use ResourceLimiter to define max size of the entire cluster (ie. scale whichever nodepool makes most sense, but don't go over 1000 CPUs in the whole cluster). I don't think this is what you meant in your comment?

**Comment by Kafei59** [comment]
Hello @MaciekPytel , thanks for you answer.
Indeed, `--scale-down-utilization-threshold` per NodeGroup is exactly what we need.

What I was trying to explain was if there would be a way to have also something like `--scale-up-threshold` per NodeGroup ?
In fact, we are exposing cpu mim/max and mem min/max per node group API objects on our side and I just wanted to know if there will be usable.

If so, this issue can be tagged as closed, and if you need any help in the development of the option, I will be glad to help you :)

**Comment by Kafei59** [comment]
I created a pull-request to show what could be useful to do and add comments for the proposal above #3728

**Comment by MaciekPytel** [comment]
Yeah, the interface in the PR is roughly what I have in mind in #3583. The list of fields I have in mind is slightly different and I'd like to wrap it in an interface, but the general idea is exactly the same. My plan is to implement this in December. 

I have no idea what you mean by --scale-up-threshold though. I don't think there is any such concept in CA (scale-up is based purely on binpacking simulation of pending pods and it doesn't involve any thresholds that I can think of).

**Comment by Kafei59** [comment]
Thanks for your answers @MaciekPytel, I'm thrilled to see what you will implement then !
I tag this issue and the linked PR as closed since you got all covered ;)
