### ISSUE TITLE
[VPA]  provides recommendation for nonexistent containers in given pod

### ISSUE THREAD

**Issue by surajnarwade** [kubernetes/autoscaler#3732]
I have statefulset pod for which there were 4 containers and VPA was providing a recommendation for them, let's say they are A, B, C & D

Now I updated the pod manifests and now there are 3 containers in a pod, A, B, E (we have removed C & D)

but if we look at VPA recommendation, it gives a recommendation based on A, B, C, D & E resulting in errors like:

```
create Pod test-0 in StatefulSet test failed error: pods "test-0" is forbidden: maximum memory usage per test is 115Gi, but the limit is 257015544173
```

is it a known issue?  I think ideally VPA should consider containers which are present in the pod currently

**Comment by surajnarwade** [comment]
more details on this issue:

here's the VPA recommendation:

```
 Recommendation:
    Container Recommendations:
      Container Name:  config-reloader
      Lower Bound:
        Cpu:     10m
        Memory:  23309947
      Target:
        Cpu:     11m
        Memory:  23574998
      Uncapped Target:
        Cpu:     11m
        Memory:  23574998
      Upper Bound:
        Cpu:           73m
        Memory:        157228529
      Container Name:  prometheus
      Lower Bound:
        Cpu:     378m
        Memory:  16585653500
      Target:
        Cpu:     1101m
        Memory:  19266383159
      Uncapped Target:
        Cpu:     1101m
        Memory:  19266383159
      Upper Bound:
        Cpu:           2477m
        Memory:        34393750524
      Container Name:  rules-configmap-reloader
      Lower Bound:
        Cpu:     10m
        Memory:  11479066
      Target:
        Cpu:     11m
        Memory:  11500k
      Uncapped Target:
        Cpu:     11m
        Memory:  11500k
      Upper Bound:
        Cpu:           21m
        Memory:        21981012
      Container Name:  thanos-sidecar
      Lower Bound:
        Cpu:     34m
        Memory:  6424737588
      Target:
        Cpu:     143m
        Memory:  9616998332
      Uncapped Target:
        Cpu:     143m
        Memory:  9616998332
      Upper Bound:
        Cpu:           624m
        Memory:        17172087037
      Container Name:  prometheus-config-reloader
      Lower Bound:
        Cpu:     10m
        Memory:  11479066
      Target:
        Cpu:     11m
        Memory:  11500k
      Uncapped Target:
        Cpu:     11m
        Memory:  11500k
      Upper Bound:
        Cpu:     21m
        Memory:  21981012
```

total memory request = 23574998+19266383159+11500k+9616998332+11500k ~= 28929956489 bytes (28.92 Gi)  

whereas limitrange for namespace is set to `115Gi`

whereas I am seeing the following error:


```
create Pod prometheus-sre-1 in StatefulSet prometheus-sre failed error: pods "prometheus-sre-1" is forbidden: maximum memory usage per Pod is 115Gi, but limit is 1293066334739
```

**Comment by bskiba** [comment]
Could you paste your deployment request and limit values as well? VPA sets limit proportional to request according to the proportion from the deployment so it would help with pinpointing the issue and reconciling the numbers.

@jbartosik I think part of the issue is proportional limit calculation in presence of containers that were removed. Could you take a look at the code to see what happends if we have recommendations for containers that are no longer present?

We do have an issue were deleted container recommendations linger (forever). We did have discussions about removing those after some time but never got around to doing this.
The trick with deciding what containers are still there is that some containers may be injected by webhooks, so containers listed in a deployment may not be the full list.

**Comment by jbartosik** [comment]
/remove-lifecycle stale

I want to work on this
