### ISSUE TITLE
[Question][VPA][Cluster autoscale] do we plan/already support scale underlying node? 

### ISSUE THREAD

**Issue by jichenjc** [kubernetes/autoscaler#3741]
A use case for us is we need increase the pod's cpu/memory on the fly due to workload increase
but the scale up of the container might in the end require a scale up of a node
has this been enabled or some links can be provided if there is restrictions on such scenario?

**Comment by bskiba** [comment]
This is not currently supported in the open source VPA. Since the feature is very provider dependent as it needs support from underlying infrastructure, you can try to find it in the specific providers. 
As an example, GKE provides integration with cluster autoscaler to provide different shape of node if VPA resize makes it necessary: https://cloud.google.com/kubernetes-engine/docs/concepts/verticalpodautoscaler#overview

**Comment by jichenjc** [comment]
@bskiba thanks :) , I will take a look~
