### ISSUE TITLE
Scale-up a cluster with a new node group

### ISSUE THREAD

**Issue by koef** [kubernetes/autoscaler#3764]
Hello. 

Let's assume that I have a cluster with node group "one". I want to keep the group "one" unchanged and scale the cluster by non-existed groups in the cluster, which include servers with another configuration.

As I can see, before scale-up, Cluster-Autoscaler checks is [bestOption.NodeGroup exists](https://github.com/kubernetes/autoscaler/blob/0fb897b83992787fd75f262499c71b8ff3bfd14c/cluster-autoscaler/core/scale_up.go#L476), and if it's not, creates it.

But Cluster-Autoscaler gets options with node groups to scale-up, by processing CloudProvider.NodeGroups(), which should return only existed groups.

Could you please clarify, is there any way to scale-up/scale-down the cluster with a new node group?

**Comment by MaciekPytel** [comment]
There isn't. The code you mentioned is a leftover from when GKE did a PoC of feature like this. You can find more details in https://github.com/kubernetes/autoscaler/issues/1916#issuecomment-484923391, but tl;dr is that the PoC only covered GKE. After it turned out to not be portable to other providers and require an ever growing number of GKE-specific changes to core autoscaler logic the PoC in this repo was abandoned and GKE ended up [implementing it](https://cloud.google.com/kubernetes-engine/docs/how-to/node-auto-provisioning) on their own.

**Comment by koef** [comment]
Thanks for the answer.
