### ISSUE TITLE
What does no.scale.down.node.no.place.to.move.pods mean and how can I debug it?

### ISSUE THREAD

**Issue by danielyaa5** [kubernetes/autoscaler#3813]
Hello, Im having trouble understanding why my nodes aren't scaling down. When I look at the autoscaling logs I see

```
noDecisionStatus: {
   measureTime: "1610496328"    
   noScaleDown: {
    nodes: [
     0: {
      node: {
       cpuRatio: 7        
       memRatio: 2        
       mig: {…}        
       name: "gke-creative-vis--pl-vob-playground-p-fdasf-0kqj"        
      }
      reason: {
       messageId: "no.scale.down.node.no.place.to.move.pods"        
      }
     }
    ]
    nodesTotalCount: 1     
   }
  }
```

I looked at the docs and don't really see any helpful debugging information with regards to this scale down reason. Theres some info here https://justin.palpant.us/tuning-cluster-autoscaler-on-gke/ but I don't really understand the explanation.

**Comment by MaciekPytel** [comment]
Disclaimer: This log event is specific to GKE fork of Cluster Autoscaler and not part of codebase in this repo, so this is probably not the best place for this question. However, the logic behind this reason applies to CA in general.

CA will only remove a node if it believes all pods running on this node will be able to schedule on other nodes in the cluster. To check if node N can be removed CA creates an in-memory cluster with node N removed from it and asks embedded scheduler code to check if all pods previously running on N can schedule in this in-memory cluster. 
This message means that the scheduler was unable to schedule all the pods in the simulation above and so CA believes removing that node will result in at least one pod currently running on it going pending.

**Comment by danielyaa5** [comment]
@MaciekPytel Thanks for the explanation, tbh it was really well worded but Im still having trouble really understanding beyond, scheduler doesn't think it can fit all other pods on other nodes. For my case this also bewilders me because there is plenty of room on the other node running. How would you go about debugging this.

**Comment by MaciekPytel** [comment]
Space (cpu/memory) is just one dimension. The pod may not be able to schedule due to constraints such as nodeSelector/nodeAffinity not matching pod labels, taints, pod(Anti)Affinity, various storage-related constraints, pods per node limit and so on. 

If you can make changes to your env (or you have a test env where you can replicate) you could debug by either:
 * Creating one more copy of the pods running on the node in question. The expectation would be for those pods to remain pending and you can look at FailedScheduling event (available via kubectl describe pod) to see what reason the scheduler is giving for why it can't schedule pod.
 * Try to manually remove the node in question. Some of the pods running on that node should remain pending and you can again look at FailedScheduling events for reason (note: this will obviously cause downtime for your workload, so probably not a great idea in prod).
 
I would usually debug this sort of issue by looking at the node and pod in question and looking for all the constraints I mentioned above - do labels match selectors? are there any taints on the node? etc. I realize this is not very helpful if you're not familiar with Kubernetes scheduling, but it may be the only way if the ideas above are not an option.
