### ISSUE TITLE
Linode Cloud Provider is breaking the CA build

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/autoscaler#3849]
cc: @dbonfigli

From https://travis-ci.org/github/kubernetes/autoscaler/jobs/756329057
```
# k8s.io/autoscaler/cluster-autoscaler/cloudprovider/linode [k8s.io/autoscaler/cluster-autoscaler/cloudprovider/linode.test]
cloudprovider/linode/linode_cloud_provider.go:48:17: cannot use ng (type *NodeGroup) as type cloudprovider.NodeGroup in assignment:
	*NodeGroup does not implement cloudprovider.NodeGroup (missing GetOptions method)
cloudprovider/linode/linode_cloud_provider.go:64:4: cannot use ng (type *NodeGroup) as type cloudprovider.NodeGroup in return argument:
	*NodeGroup does not implement cloudprovider.NodeGroup (missing GetOptions method)
FAIL	k8s.io/autoscaler/cluster-autoscaler/cloudprovider/linode [build failed]
```

Please fix the build ASAP or we will have to roll back #3790.

**Comment by dbonfigli** [comment]
I'll look into it now

**Comment by dbonfigli** [comment]
this #3850 fixes it.

**Comment by dbonfigli** [comment]
Basically what happened is that the travis build for PR #3790 was done at the time of the latest commit for the feature branch, shortly after commit a8ee048 introduced the new NodeGroup method GetOptions and implemented it on that commit for any provider except the linode one because it was not yet merged.

**Comment by mwielgus** [comment]
Hopefully fixed now.
