### ISSUE TITLE
Cluster autoscaler custom resource evaluation

### ISSUE THREAD

**Issue by innovate-invent** [kubernetes/autoscaler#3852]
Currently the autoscaler evaluates only memory and cpu requests. I propose that a configuration option be added that accepts a mapping of [extended resource names](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#node-level-extended-resources) to denominator values to be included in the scoring equation:
https://github.com/kubernetes/autoscaler/blob/b470c62bfa6269ed185d21d47dadc339353deb68/cluster-autoscaler/estimator/binpacking_estimator.go#L136

My specific use case requires that 'time' be a evaluation metric as my cluster schedules thousands of very short jobs. Currently the autoscaler just provisions the maximum pool size, the jobs are spread over the pool, and then the nodes see a couple seconds of activity before idling until shut down. I would like to be able to assign that a node has a time capacity equal to the minimum ready time of a new node, plus its maximum idle time before termination. Containers are then assigned a `.requests.time` value based on the estimated amount of time the work will take.

I think it would also be more appropriate for the score equation to be along the lines of `cpu_sum/node_cpus * mem_sum/node_mem * mult(sum(container.requires[name] for each container in pod)/config_map[name] for each name in config_map)` Having a geometric relationship between each dimension.

The config option could be replaced by assigning these values to the node classes.

**Comment by MaciekPytel** [comment]
Cluster autoscaler actually takes into account all resource requests. Binpacking iterator doesn't calculate (in the sense of using formula) how many nodes are needed, it implements a greedy binpacking algorithm that uses embedded scheduler code to check if a pod would fit on a node. That way it automatically takes into account anything the real scheduler would look at (*). 

The "score" you linked is just a heuristic used to roughly sort pods from largest to smallest before binpacking. We're trying to emulate [First Fit Decreasing binpacking algorithm](https://en.wikipedia.org/wiki/Bin_packing_problem#First_Fit_Decreasing_(FFD)), but it's unclear how important the packing is in practice given that:
* The pods have many dimensions (cpu, memory, gpu, ...) and discrete constraints (nodeAffinity, podAffinity, ...). There is no ordering that would take all of those into account.
* Binpacking too well would actually be bad as the scheduler (which only looks at one pod at a time) would be extremely unlikely to be able to achieve the same result.

So I don't believe it's particularly important for the pod score to capture every possible resource or even to be a particularly well though out value. Estimator should take them all into account anyway.

**Comment by innovate-invent** [comment]
Ah, I suppose I do not fully understand how the autoscaler works. Just to confirm, it does actually consider extended resources in its calculation? If so I am concerned that setting a time resource will prevent long running tasks from being assigned to any node. Is it possible to set as a soft request?

Sorry, the scheduler is a bit of a black box to me, I would appreciate any help.

**Comment by MaciekPytel** [comment]
Yes, autoscaler will consider all resources listed under pod's request. On the implementation side resources are really just a map string->quantity. Pod can schedule on a node iff for each key in its request the node has >= free allocatable. 
One autoscaler specific limitation is that the node must start with all the resources already set. You can't add your extended resource after the node starts, it must be already set when the node first becomes ready. Otherwise when scaling-up autoscaler will see the new node doesn't have the extended resource it expected and immediately trigger another scale-up.

There are no soft resource requests and any 'soft' scheduling constraints (ex. preferredDuringScheduling nodeAffinity) are completely ignored by autoscaler. All we promise in autoscaling is that a pod will get a node where it can schedule, not that it will be the node the pod would prefer.

---

As to your original problem - if I understand correctly you want to limit scale-up? I don't see how adding an extra resource could help with that. Autoscaler treats a node as an n-dimensional box and pods as n-dimensional objects where n is the number of different resource types. It keeps adding nodes until it can fit all the pods. Adding an extra dimension to the picture will not make the box larger in existing dimensions - it's just one more constraint. All you can ever achieve by adding extended resource is to get CA to scale-up more, not less.

I don't think there is any mechanism to do what I think you want to do (other than setting lower maximum size for your node group). There is no notion of time in k8s scheduling and CA is designed to make enough nodes so all pods can run in parallel. It may be easier to solve this by only creating your pods when you want them to run. 
Otherwise you may need to build a custom autoscaler and, possibly, scheduler.

**Comment by RealHarshThakur** [comment]
Hey @MaciekPytel , I am looking to scale up nodes based on disk capacity on each node. Ideally, I would like to point cluster-autoscaler to the external metric(size of disks on particular node)  to start scaling from. 

* Would it be possible for cluster-autoscaler to take in custom metrics like that?
or 
* Are the components from the project re-usable to enable such a use-case?

**Comment by innovate-invent** [comment]
Closing in place of #3916
