### ISSUE TITLE
Linode cluster-autoscaler error: Provider cannot convert ProviderID

### ISSUE THREAD

**Issue by Static-Flow** [kubernetes/autoscaler#3854]
**Which component are you using?**: cluster-autoscaler for linode

cluster-autoscaler for linode

**What version of the component are you using?**:

Component version: built from master branch using these instructions https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/linode#development
Image is here: https://hub.docker.com/repository/docker/staticflow2280/scaler

**What k8s version are you using (`kubectl version`)?**: 1.18

</pre></details>

**What environment is this in?**: linode LKE

**What did you expect to happen?**: For autoscaler to remove unused nodes

**What happened instead?**: Autoscaler scanned all nodes but was unable to determine their status because of this error.

`E0127 13:37:51.498672       1 static_autoscaler.go:271] Failed to get node infos for groups: Cannot convert ProviderID "" to linode istance id (must be of type linode://<integer>)`

**How to reproduce it (as minimally and precisely as possible)**:
1. Create LKE cluster
2. Launch autoscaler using the example template at https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/linode/examples/cluster-autoscaler-autodiscover.yaml
3. Launch pod that cannot be scheduled  

**Anything else we need to know?**:

Tagging @dbonfigli  only because he might be able to help.

full error with context:
```
I0127 13:37:51.495463       1 linode_manager.go:84] LKE node group after refresh:
I0127 13:37:51.495734       1 linode_manager.go:86] node group ID g6-standard-2 := min: 3, max: 500, LKEClusterID: 17815, poolOpts: {Count:1 Type:g6-standard-2 Disks:[]}, associated LKE pools: { poolID: 22112, count: 1, type: g6-standard-2, associated linodes: [ID: "22112-60111ed9a860", instanceID: 24323757] }, [..redcated more nodes..]{ poolID: 22115, count: 1, type: g6-standard-2, associated linodes: [ID: "22115-60111edac144", instanceID: 24324125] }, { poolID: 22121, count: 1, type: g6-standard-2, associated linodes: [ID: "22121-60111edc50ba", instanceID: 24323790] }, { poolID: 22069, count: 1, type: g6-standard-2, associated linodes: [ID: "22069-60111ec1fcc0", instanceID: 24323780] }, { poolID: 22120, count: 1, type: g6-standard-2, associated linodes: [ID: "22120-60111edbe4ca", instanceID: 24323930] }, { poolID: 22135, count: 1, type: g6-standard-2, associated linodes: [ID: "22135-60111ee09bb2", instanceID: 24323897] }
E0127 13:37:51.498672       1 static_autoscaler.go:271] Failed to get node infos for groups: Cannot convert ProviderID "" to linode istance id (must be of type linode://<integer>)
```

**Comment by dbonfigli** [comment]
Hi @Static-Flow, this is interesting, it means that one of your node has no Spec.ProviderID value, can you report the output of 
`kubectl get node -o yaml` and what region you are using?

**Comment by Static-Flow** [comment]
So I am using the Dallas region, and sadly I've taken down the cluster so I can't get you that output. It only seems to happen when I try to scale out to a lot of nodes. This might be a misunderstanding of how best to use k8s. My workload I am trying to do is a batch process split amongst 250 shards. So I create 250 job yaml files and apply them. The jobs are setup to request an amount of resources so each job is on 1 node which might be the cause of all this. Below are the relevant portions of the config files. 

cluster-autoscaler-secret
```
    defaut-min-size-per-linode-type=1
    defaut-max-size-per-linode-type=500

    [nodegroup "g6-standard-2"]
    min-size=3
    max-size=500
```

job.yaml
```
        resources:
          requests:
            memory: "3Gi"
```

Autoscaler will process the scale up requests but then the whole cluster grinds to a halt and the autoscaler issues start to happen. It seems like 250 nodes shouldn't be putting that much strain on the cluster but that might be my lack on understanding of k8s.

**Comment by dbonfigli** [comment]
Do you confirm than that at least for < 100 nodes the cluster-autoscaler works and only with high numbers the problem arise?

I know from a contact in Linode that 126 nodes is the limit in LKE, but I have never hit it nor this limit is reported in the Linode documentation so I don't know what happen then, it seems for what you are saying that using g6-standard-2 that provides 4 GB of memory and submitting 250 pods with 3 GB each could very well go beyond that number and then LKE could start to fail and not completely set up a node, for example not adding spec.providerID field to a node.

Anyway, the real interesting thing here is that you have nodes with no spec.providerID value, this value is needed for each node to let cluster-autoscaler select a node to be delete and more. If you can reproduce the error then please check if a node has not such a value and report back here. Also, try to wait some minutes to understand if LKE eventually add the spec.providerID. You can do that with the command I reported on my previous comment or with something more specific like `kubectl get node -o jsonpath='{range .items[*]}{"\n"}{.metadata.name}{" "}{.spec.providerID}{end}''`, to list for each node the name and providerID, if you see a row with no providerID that is the problem. Also, if that happen, confirm that if you just manually remove the nodes without spec.providerID then the cluster-autoscaler starts to work again.

Some of the other providers have implemented some logic to skip a node without spec.providerID, for example azure and aws, for them this was necessary since with some configuration with virtual nodes (e.g. fargate or vmss) spec.providerID is not there, most of the other providers `NodeGroupForNode()` returns an error in case this filed has no value, I have never seen an LKE node without spec.providerID, if there is a legit scenario where providerID is missing for a node we can easily provide a PR but if it is a problem in LKE then this patch would not be ideal because you will simply ignore that node and I don't think one would want it.

**Comment by Static-Flow** [comment]
Hmm the limit is interesting, I did not know about that. The autoscaler works perfectly fine in low node configurations. When I stand up my cluster I use the autoscaler to scale out my elasticsearch instance to 4 nodes successfully. Would this limit happen if I rolled my own k8s cluster instead of using LKE?

**Comment by dbonfigli** [comment]
The cluster-autoscaler linode cloud provider works only with LKE, so if you build your own cluster it will not work, you could explore the cluster API implementation.

I cannot confirm the limit on nodes myself, please ask the official linode support.

The way forward here is reproducing the problem and confirm the hypothesis (check if a node has not the spec.providerID value), and if so get in touch with the linode support to see with them why there are missing providerID fields for nodes / eventual limits of LKE.

Also, after you confirm that, report here so we can document the problem and close this issue.

**Comment by Static-Flow** [comment]
The issue appears to be the linode cap on LKE clusters at 126. Closing this issue.

```
Hey there,

I just wanted to follow up with you, as I've discussed this with our LKE team. LKE supports up to 126 nodes per cluster. It looks like by deploying 250 nodes per cluster, you're running into some resource limitations that are causing the cluster to become unresponsive.

By keeping the number of nodes to 126 or less, you should be able to avoid this issue going forward.

Thanks for your patience while we looked into this. If you have any other questions or concerns, be sure to let us know. We're happy to help however we can.

Regards,
Linode Support Team
```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
