### ISSUE TITLE
What is the correct chart version ?

### ISSUE THREAD

**Issue by eddycharly** [kubernetes/autoscaler#3899]
I see releases vith version 2.0.0 (https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-chart-2.0.0) and the same release with version 9.5.0 (https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-chart-9.5.0).

Which one should i use ? What is the difference ?

**Comment by damscott** [comment]
There is an explanation in [the chart's readme](https://github.com/kubernetes/autoscaler/tree/master/charts/cluster-autoscaler#previous-helm-chart), but I'm even more confused after reading it.

The explanation reads as if it went from legacy 9.x versioning, to 1.x versioning, then back to 9.x versioning. Now there's also a 2.x release that's not mentioned in that explanation. At the time of writing this, the master branch is using 9.x versioning in Chart.yaml.

**Comment by eddycharly** [comment]
Ping @gjtempleton can you help us understanding the current versioning scheme ?

**Comment by gjtempleton** [comment]
Hey,

I guess we need to clear that wording up if it's confusing people.

The chart was migrated from its previous home under the stable Helm org where it had reached a 8.X release, at the time of migration it had to be renamed due to limitations with the helm chart releaser Github action we use from `cluster-autoscaler` to `cluster-autoscaler-chart` and had its versioning reset to `1.X`. Once these limitations had been overcome it was renamed once again, and to address the concerns of some existing users of the chart, moved to a 9.X release to prevent version collision with the previous releases when it had been hosted under the helm stable org. The `cluster-autoscaler-chart` named version was marked deprecated as of the `2.0.0` release to prevent it showing up in Artifact hub searches and causing confusion. This can be seen here: https://artifacthub.io/packages/helm/cluster-autoscaler/cluster-autoscaler-chart

Hope this helps clear things up!

**Comment by eddycharly** [comment]
Thanks for clearing it up !
If I understand correctly, the recommendation should be to use the `cluster-autoscaler` chart with `9.X` version.

This is fine, maybe adding those infos somewhere in the `README` of the repository will help others too.
