### ISSUE TITLE
AKS: scale down behavior (does it delete specific node or just scales down VMSS)

### ISSUE THREAD

**Issue by kamilzzz** [kubernetes/autoscaler#3936]
What is the scale down behaviour of CA?

When there is an unneeded node, does CA issues a request to cloud provider to delete this specific node or it just issues a request to scale down VMSS?

I am having a VMSS spanning 3 availability zones and if it is CA who decides which node should be deleted then there is a higher chance than availability zones will be unbalanced. If CA just issues a request to scale down VMSS then VMSS will try to balance zones at best effort.

**Comment by marwanad** [comment]
CA deletes a particular node because it needs to identify nodes that are "unneeded" based on utilization and attempt to reschedule pods (if needed) to satisfy the scheduler constraints. The recommendation is to use 1 VMSS per zone and enable `--balance-similar-node-groups` via the autoscaler profile.
