### ISSUE TITLE
Cluster autoscaler creates new instances, but new nodes are not joining the cluster

### ISSUE THREAD

**Issue by MiguelLucas** [kubernetes/autoscaler#3953]
**Which component are you using?**:

Cluster-autoscaler

**What version of the component are you using?**:

1.14.8

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:32:32Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:

AWS

**What did you expect to happen?**:

Using cluster-autoscaler in auto-discovery mode, new instances created should join the cluster

**What happened instead?**:

New instances are being created in EC2, but these new nodes are not joining the cluster, staying stuck in "unregistered node present". If i SSH into every one of them and use `kubeadm join`, they do join successfully, but this process should be automatic. What am I doing wrong?

I am not using EKS, nor do I want to use it.

**How to reproduce it (as minimally and precisely as possible)**:

Created IAM role with all necessary permissions.
Setup an autoscaling group with relevant tags and assigned IAM role to all instances. Use `kubeadm init` to create new cluster in one of the created instances, then create cluster-autoscaler deployment with the exact same tags.

**Anything else we need to know?**:

This is the result of running `kubectl logs -f deployment/cluster-autoscaler -n kube-system`
```
I0318 11:30:07.394912       1 static_autoscaler.go:138] Starting main loop
I0318 11:30:07.395437       1 static_autoscaler.go:206] 3 unregistered nodes present
I0318 11:30:07.395461       1 static_autoscaler.go:293] Filtering out schedulables
I0318 11:30:07.395560       1 static_autoscaler.go:310] No schedulable pods
I0318 11:30:07.395584       1 scale_up.go:263] Pod default/test-1 is unschedulable
I0318 11:30:07.395590       1 scale_up.go:263] Pod default/test-2 is unschedulable
I0318 11:30:07.395630       1 scale_up.go:300] Upcoming 3 nodes
I0318 11:30:07.395924       1 scale_up.go:408] No need for any nodes in ClusterAutoScalerTest
I0318 11:30:07.395932       1 scale_up.go:416] No expansion options
I0318 11:30:07.395944       1 static_autoscaler.go:365] Calculating unneeded nodes
I0318 11:30:07.395952       1 utils.go:543] Skipping ip-172-31-38-67 - no node group config
```

**Comment by gjtempleton** [comment]
Hi, 

Thanks for raising the issue. The cluster autoscaler is only responsible for scaling the node groups it discovers and manages up and down, it isn't responsible for the behaviour and registration to the cluster of the new nodes it creates. More details on its behaviour on scaling up and down can be found here: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-does-scale-up-work

The responsibility for ensuring that newly created nodes register themselves to the cluster when they come into existence due to scaling by the cluster autoscaler lies with the cluster provisioning tooling you use. In your case, as kubeadm doesn't automatically configure this, you could configure your ASG(s) to automatically run `kubeadm join` at boot time via a userdata script.

Hope this helps!

**Comment by MiguelLucas** [comment]
Thanks for answering!

We eventually followed that solution you described, and things seem to work for now. 

Cheers!

**Comment by gjtempleton** [comment]
Glad to hear it!

/close
