### ISSUE TITLE
VPA: invalid memory recommedation unit

### ISSUE THREAD

**Issue by gaurav1086** [kubernetes/autoscaler#3965]
**Which component are you using?**:
vertical pod scaler

**What version of the component are you using?**:
v0.9.2

Component version: v0.9.2

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:30Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"clean", BuildDate:"2021-02-17T12:33:08Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What environment is this in?**:
linux

**What did you expect to happen?**:

The manifest contains:

```
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 512Mi
```

**What happened instead?**:

The current usage stats:

```
$kubectl -n app-namespace describe pod my-pod-name

    Restart Count:  0
    Limits:
      cpu:     25390m
      memory:  731815514666m
    Requests:
      cpu:      2539m
      memory:   548861636
```

The limit memory units is showing with suffix 'm' (731815514666**m**) . As per the kubernetes doc, the memory resource is measured in bytes. You can express memory as a plain integer or a fixed-point integer with one of these suffixes: E, P, T, G, M, K, Ei, Pi, Ti, Gi, Mi, Ki. (https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/#Memory%20units) . Is the 'm' suffix valid ?

**How to reproduce it (as minimally and precisely as possible)**:

Create a deployment and have it do a vpa-opt-in.

**Anything else we need to know?**:

**Comment by sibucan** [comment]
I've been doing some experimentation, and I think this happens when the ratio between the original memory requests/limits on the Deployment is a floating point number, instead of an integer. The admission controller is supposed to take the recommendation from the VPA, and calculate the limit based on the aforementioned ratio. That calculation is performed here:
https://github.com/kubernetes/autoscaler/blob/02985973c6001dbd650b940eef893e4f03db15db/vertical-pod-autoscaler/pkg/utils/vpa/limit_and_request_scaling.go#L124-L143

When the ratio produces an integer (e.g.: 200Mi limit / 100Mi request = ratio of 2), the calculated limit is correct as seen here: https://play.golang.org/p/chAar3VNkSt

When the ratio produces a floating point number (e.g.: 200Mi limit / 150Mi request ~= ratio of 1.33), the calculated limit is expressed in millivalues, (https://play.golang.org/p/dR4SaXRBGmB) which is valid for CPU values, but not necessarily for memory values.

According to the Kubernetes spec, [memory values](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-memory) without an unit are meant to be interpreted as bytes, which aren't divisible into milli values, unlike the CPU values, where "0.1" will be converted by the API to "100m".

I think this behavior can be changed if the suggested memory limit can be transformed from a milli value into a normal value. I think a good place to do that would be here: https://github.com/kubernetes/autoscaler/blob/02985973c6001dbd650b940eef893e4f03db15db/vertical-pod-autoscaler/pkg/utils/vpa/limit_and_request_scaling.go#L60

**Comment by grosser** [comment]
This is till an issue afaik, just @gaurav1086 no longer cares about it ... so can reopen.

**Comment by alexbowers** [comment]
This is still an issue, please can it be reopened
