### ISSUE TITLE
priority expander should have mutually exclusive node group

### ISSUE THREAD

**Issue by DanielAmmar** [kubernetes/autoscaler#4098]
Our EKS cluster have 4 node groups: 2 for gpu instances and 2 for general work instances.
Within each, we have a node group for spot instances and another node group for on-demand instances (as fallback)

After reading [this](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/expander/priority/readme.md):
`If there are multiple node groups matching any of the regular expressions with the highest priority, one group to expand the cluster is selected each time at random`
It came to my knowledge that on-demand fallback will not always work unless the priority configmap have mutually exclusive autoscaling groups.

```
data:
  priorities: |-
    10: 
      - ^((?!spot).)*$
    50: 
      - .*spot*
```
In the above example if the lowest priority 10 is changed to `- .*` (catch-all regex), a situation can be built that the same spot will be chosen again and again (due to the random choice)

**Comment by krzysztof-bronk** [comment]
Which version of CA are you using? This sounds like the bug fixed in 1.20.0+, where if a group matched 2 priorities, it could pick the lower one randomly rather than the highest one. While this fix was backported to 1.19.1, there was no release with this fix.

I think there is another problem with the "on-demand fallback" I see described on blog posts and in the official docs - those examples only ever talk about 2 node groups. In such case, if the spot group cannot scale for some reason, yes, the on-demand fallback will kick in.

However, realistically you're going to have more than 2 node groups (as is recommended especially for spot instance types or AZ balancing).
I understand CA correctly, if you have 10 spot node groups, and 1 on-demand with lower prio, then if one or more spot ones fail to scale, CA will likely keep selecting other spot groups, waiting for the max-provision-time every time, potentially causing application disruptions, and never really "fall back", or at least not in time.
This is because the node group selection has nothing to do with the expander and is not configurable in the same way. Expander gets a premade list to choose from.
