### ISSUE TITLE
what is the use of vertical pod autoscaler “auto” mode

### ISSUE THREAD

**Issue by saeid93** [kubernetes/autoscaler#4155]
As far as I understand from the VPA documentation the vertical pod autoscaler stop/restart the pod based-on the predicted request/limit's lower/upper bounds and target. In the "auto" mode it says that the pod will be stopped and restarted, however, I don't get the point of doing a prediction and restarting the pod while it is still working because although we know that it might go out of resource eventually it is still working and we can wait to rescale it once it has really gone out of memory/cpu. Isn't it more efficient to just wait for the pod to go out of memory/cpu and then restart it with the new predicted request?

Is recovering from a dead container more costly than stopping and restarting the pod ourselves? If yes, in what ways?

**Comment by jbartosik** [comment]
A few reasons for that:

* Pod will not die because it wants to use more CPU than it's allowed to. So if you want to update pods when they hit CPU limit then you need something else to restart pods.
* When container OOMs pod might not get recreated, only container will restart (so VPA can't apply recommendation).
* This allows for gradual update, respecting PDB. If you wait for pods to OOM they might do that all at the same time (for example load increases some pods die, then other pods receive more load and also die all at the time when you have more load so it's more important for things to work smoothly).

Please reopen if you have more questions about this.
