### ISSUE TITLE
Cannot pull latest addon_resizer 1.8.13, image not found

### ISSUE THREAD

**Issue by tanvp112** [kubernetes/autoscaler#4178]
image: k8s.gcr.io/addon-resizer:1.8.11 can be pulled but this version is one year ago.

Trying the latest version resulted to image pull error.

`image: k8s.gcr.io/addon-resizer:1.8.13`

What is the image uri for the latest addon_resizer?

**Comment by gjtempleton** [comment]
The community Docker registry paths have changed since the infrastructure was migrated from Google to the community. You can [read more about that here](https://github.com/kubernetes/k8s.io/blob/main/k8s.gcr.io/Vanity-Domain-Flip.md).

The image you're looking for can be found as `k8s.gcr.io/autoscaling/addon-resizer:1.8.13`, and the old images have also been migrated to these new paths, so you can find old tags under the same image registry paths.

Can I ask if there's somewhere you saw referring to `k8s.gcr.io/addon-resizer:1.8.13` as a valid image?

**Comment by tanvp112** [comment]
Thanks a lot for the pointer. I got the broken link from [addon-resizer readme.md](https://github.com/kubernetes/autoscaler/tree/master/addon-resizer#addon-resizer).
