### ISSUE TITLE
Rename all references of Packet to Equinix Metal

### ISSUE THREAD

**Issue by ipochi** [kubernetes/autoscaler#4286]
Which component hosted in this repository is this a feature for? cluster-autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

Since Equinix's acquisition of Packet, other repositories and projects are being renamed from Packet to Equinix Metal in code, config and documentation.

I'd like this to happen for `cluster-autoscaler/cloudprovider/packet` as well.

**Describe the solution you'd like.**:

All references are correctly renamed from Packet to Equinix Metal.

**Comment by displague** [comment]
One approach to this would be to persist the `packet` name and docs while all `go` packages reside in an Equinix Metal namespace.  The API code would be identical since there is a common API backing the service regardless of what API URL (api.packet.net vs api.equinix.com/metal/v1) is used.  Arguments and environment names, some debug messages or errors would need to use templates to provide the correct product description or variable prefix.

On the other hand, `cp -a packet equinixmetal` + `sed` isn't so terrible.  Actually, I think we can get this change in much quicker.  I'll PR something.

**Comment by displague** [comment]
> On the other hand, cp -a packet equinixmetal + sed isn't so terrible. Actually, I think we can get this change in much quicker. I'll PR something.

I went stale on this branch. It looks like I ran into problems with the codegen. I don't see myself picking this branch back up anytime soon.

**Comment by displague** [comment]
The path I took in the branch above was to create a second provider called `equinixmetal`. The thought was to copy all Packet provider work into an Equinix Metal provider with `s/PACKET/METAL/,s/packet/equinixmetal/,s/Packet/EquinixMetal` changes applied.

With https://github.com/kubernetes/autoscaler/pull/4274 already in released, the Packet provider now honors `equinixmetal://`. In order to proceed with my branch, the `equinixmetal` provider would need to take ownership of the `equinixmetal://` prefix, introduce the new `METAL` prefixes (env vars), and honor the legacy Packet prefixes since these can be combined with the `equinixmetal://` prefixes today.

I think a new branch or set of branches targeting this issue should be focused within the existing Packet provider:
* Make "Packet" -> "Equinix Metal" text changes and "packet.(com|net)" -> "*.equinix.com" changes
* Add support for `METAL` env prefixes (continuing to support the Packet prefixes, potentially deprecating them)
*  Rename the `packet/` directory to `equinixmetal/` (and rename the files, package, and functions in that directory)

The third point introduces Go API changes in an importable path. Are we ok with that?  From the projects that GitHub reveals taking a dependency on this project, none seem to import the provider paths directly.
