### ISSUE TITLE
Is it possible to make autoscaler prioritize scale down node/nodes based on AWS health events

### ISSUE THREAD

**Issue by oguzhanaygn** [kubernetes/autoscaler#4388]
Hi,
There is a case in my hand, AWS marked one of my prod EKS nodes for retirement schedule. My instance will be retired 1 week later. I can drain the node and then remove it but since cluster-autoscaler is used heavily in all scale up/down processes (as it's supposed to be) I don't want to mess with cluster-autoscaler's work. I want to make cluster-autoscaler handle this issue. I didn't find any configuration option/annotation to implement. If there is not any, maybe the workflow below for cluster-autoscaler can be useful;

```
Check if there is any EC2 Health Issues for any instances registered to cluster -> if yes; mark/prioritize it for draining/deleting for next scale-down process, if no; continue to normal workflow.
```

CA version : 1.18.2
EKS Version : 1.18

**Comment by bitva77** [comment]
@oguzhanaygn that's correct.

Here's my story:  I was going through a K8s upgrade and so I added a second nodegroup that I wanted my pods to get scheduled on to as I drained and removed nodes from the old nodegroup.  So I made this second nodegroup to be the same size as the original.  Well, I didn't turn off the cluster-autoscaler and so it started spinning those EC2 instances down until it hit the nodegroup minimum because they weren't needed.  lol.

Funny you mention cluster-autoscaler draining/removing nodes based on other events:  That's what brought me here.  I was wondering if cluster-autoscaler could actually follow and set instance lifetime policies.  It doesn't appear so.

However, in K8s 1.21 there is a new feature for graceful node removal:

https://kubernetes.io/docs/concepts/architecture/nodes/#graceful-node-shutdown

That may end up being huge when it comes to dealing with events happening outside of the autoscaler.

But, having instances be managed by autoscaler itself would be better in my opinion.  I might put a Feature request in for this.  I put a similar feature request in for eksctl and it's managing of nodegroups.
