### ISSUE TITLE
Documentation about the Historical Data

### ISSUE THREAD

**Issue by mtavaresmedeiros** [kubernetes/autoscaler#4476]
Hi guys,

I don't find any documentation about the historical data with VPA Recommender, I have a simple question, Can I have historical information with the only metric server?  without need to install the Prometheus? if yes, how long this historical information can be?

Thank you.

**Comment by jbartosik** [comment]
Hi,
VPA will always collect and store history while it's running. With Prometheus VPA can load history from before it started.

For example lets say that:
* On day 0 you create a cluster, in the cluster you create deployment `A`.
* On day 8 you start VPA in the cluster, create a `VerticalPodAutoscaler` object with deployment `A` as its target.

Without loading history from Prometheus:
* On day 8 recommendation VPA provides for deployment `A` is based on <1 day of history.
* On day 9 the recommendation is based on ~1 day of history.
* On day 16 and later the recommendation is based on 8 days of history (VPA discards older data).

With loading history from Prometheus:
* From day 8 recommendation is based on 8 days of history.

There is some nuance what happens if you start VPA in the cluster on day 0 but don't create any VPA objects until day 8. I think in that case VPA gathers all data so it's likely to provide recommendation based on 8 days of data if you create a `VerticalPodAutoscaler` object on day 8. But I think it only saves data associated with a `VerticalPodAutoscaler` object in checkpoints, so it might have less data if vpa recommender pod is restarted in the meantime.

Please reopen if this doesn't answer your question.
