### ISSUE TITLE
Cluster autoscaler should support fully computing all details from ASG instead of caching node info

### ISSUE THREAD

**Issue by PaulFurtado** [kubernetes/autoscaler#4793]
**Which component are you using?**: cluster-autoscaler

**What version of the component are you using?**:

Component version: 1.21

**What k8s version are you using (`kubectl version`)?**: 1.21

**What environment is this in?**: AWS

**What did you expect to happen?**: cluster autoscaler should be able to scale up an ASG despite some nodes from the ASG being tainted

**What happened instead?**: cluster autoscaler produces NotTriggerScaleUp events because a few nodes in an ASG have a taint

**How to reproduce it (as minimally and precisely as possible)**: Taint a few nodes in an ASG in AWS and try to trigger a scaleup

**Anything else we need to know?**:
I understand that the cluster autoscaler's caching of node info using the nodes produced by an ASG is a useful feature for some clusters, however, we go very far out of our way to ensure that our ASGs used by the cluster autoscaler have every tag it needs to operate so that scale from zero works flawlessly across any ASG. What I would like to see is an option where the autoscaler only ever honors the computed node info from the ASG and never caches info it learns from actual nodes in the cluster.

**Comment by drmorr0** [comment]
I think the issue here is that Cluster Autoscaler requires all the nodes in a particular node group to be identical across all possible dimensions that could impact scaling.  In the situation that you describe, if some nodes in an ASG (that is, a node group) have a taint and other nodes do not, even if Cluster Autoscaler scans and stores data for all nodes instead of a single representative, CA _still_ has no idea whether the next node that scales up will have the taint or not.  This fundamentally breaks how Cluster Autoscaler works, because it would lead to either CA scaling up when pods could not fit, or not scaling up when pods could fit.

**Comment by PaulFurtado** [comment]
> ven if Cluster Autoscaler scans and stores data for all nodes instead of a single representative, CA still has no idea whether the next node that scales up will have the taint or not

I am actually suggesting that the autoscaler should have a mode where it never ever looks at a real node in the cluster. We configure our ASGs to have all of the metadata the cluster autoscaler could ever need to be able to scale up from zero. Using that metadata, it knows exactly what taints to expect from scaling up the ASG. The problem is that it then goes and looks at active nodes in the kube API, which have since evolved to be tainted. I want 100% predictable behavior where it always honors the ASG tags and doesn't replace the node information with one from a random node that happened to be created by that ASG.
