### ISSUE TITLE
What is the best way to update VPA

### ISSUE THREAD

**Issue by AhmadMS1988** [kubernetes/autoscaler#4820]
How can I update vpa without the need for ./hack/vpa-down.sh and ./hack/vpa-up.sh
Because this will delete the existing vpa rules.
Thank you

**Comment by aleksrosz** [comment]
If I'm correct you can edit file before you do ./vpa-down.sh https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/hack/vpa-process-yamls.sh 
delete this crd from this file.
ACTION=$1
COMPONENTS="**vpa-v1-crd-gen** vpa-rbac updater-deployment recommender-deployment admission-controller-deployment"
case ${ACTION} in
delete|diff|print) COMPONENTS+=" **vpa-beta2-crd**" ;;
esac

because it is responsible for where data are stored. Then you can do ./vpa-up.sh with newer version of VPA.  

Of course if there is no new changes in CRD between versions of VPA.


I'm not responsible for this project so please to be sure wait for @jbartosik . I tested it myself and I think it works properly but maybe there are some other dependencies somewhere.

**Comment by aleksrosz** [comment]
@jbartosik  I checked again, and between vpa-release-0.10 and vpa-release-0.11 I don't see changes in CRD which are in file vpa-v1-crd-gen.yaml so IMHO, it is possible to do modifications like I mentioned above and migrate from 0.10 to 0.11 without losing rules and CPU, mem usage history.

Maybe can I create PR to this readme about this https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/README.md ?

**Comment by jbartosik** [comment]
#5061 is updating Readme?
