### ISSUE TITLE
Support explicitly tagging a node for safe eviction and removal

### ISSUE THREAD

**Issue by MarcPow** [kubernetes/autoscaler#5109]
**Which component are you using?**:
cluster-autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

Periodically, we encounter nodes in our Kubernetes clusters that have become non-functional for some reason specific to the cloud provider.   Our typical solution to that problem is to replace the node, usually by marking it unusable and allowing the cluster-autoscaler to replace it.

Today, the easiest way to do this is to mark the node with a NoExecute taint.   That will drive the node to empty via taint-based eviction.

But that 'eviction' is harsh.  It does not respect PodDisruptionBudgets or safely evict the pods as the auto-scaler itself would if it identified a node as a candidate for down-scale, independently.

**Describe the solution you'd like.**:

The autoscaler should recognize a new label:

cluster-autoscaler.kubernetes.io/scale-down-requested-with-eviction=(gracefulEvictionTimeoutSeconds)

The auto-scaler should 
1. Immediately include the node, when detected into the scale-down candidate set, storing the deadline by which the eviction should take place.  EvictionDeadline=<now>+<gracefulEvictionTimeoutSeconds>.
2. Begin a graceful eviction attempt of all the pods on the node
3. If the pods have not been fully evicted by the eviction deadline, force delete all the pods on the node.
4. Remove the node.

**Describe any alternative solutions you've considered.**:

**Additional context.**:

**Comment by liuxintong** [comment]
Hi Marc, I agreed this is a good idea to have the safe node eviction feature in the native cluster autoscaler, so I just go ahead and implement it in #5187.

However, there are some minor changes in my implementation.
* Instead of using a new label, I inclined to use the annotation, which is being used in other scenarios, like `scale-down-disabled`, `safe-to-evict`, etc.
* I didn’t add the graceful eviction timeout seconds as a parameter, because it already has a similar global one `max-graceful-termination-sec`.

Regarding the following point, I think the node is most likely being blocked by a restricted PDB. It seems to be another new feature in cluster autoscaler to support PDB violation.
> If the pods have not been fully evicted by the eviction deadline, force delete all the pods on the node.

**Comment by MarcPow** [comment]
> I didn’t add the graceful eviction timeout seconds as a parameter, because it already has a similar global one max-graceful-termination-sec.

@liuxintong I suspect consumers of this feature may want to specify a per-node drain interval that might conflict with the more conservative global.  I certainly think that's true in my case...

**Comment by liuxintong** [comment]
@MarcPow That sounds reasonable. Fine-grained graceful termination control sounds like a nice feature. I'll try to make it in the next week.

**Comment by parispittman** [comment]
hi @MarcPow @liuxintong - has this been discussed at a previous sig-autoscaling meeting? if not, I can request it on the agenda. curious as to the status.

**Comment by liuxintong** [comment]
Reopening as I'm currently working on it.
/reopen
