### ISSUE TITLE
Saving VPA checkpoints for DRP

### ISSUE THREAD

**Issue by matthyx** [kubernetes/autoscaler#5146]
**Which component are you using?**:
VPA

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:
We use gitops to manage all our deployments.
We are using VPA to reduce CPU and memory requests based on real usage.
It means that VPA recommendations are almost always lower than resource requests in git.
In case of DRP, all historical data of VPA in checkpoints are lost.
We cannot simply re-apply all workloads according to git, because without data VPA won't alter resource requests, and pods cannot fit in the cluster with default resource requests.

**Describe the solution you'd like.**:
Find a way to backup/restore checkpoints for seeding our DRP cluster's VPA.

**Describe any alternative solutions you've considered.**:
Use external cache (redis or mongo) to persist current recommendations, until enough data is present in the new cluster to take over.

**Additional context.**:

**Comment by voelzmo** [comment]
I think a commonly described 'good practice' is to regularly write back the current VPA recommendations to the actual requests in your Pod-owners (i.e. Deployments, StatefulSets, etc). This also helps in the cases where your VPA might be down for some reason.

If you feel you need to recover the VPACheckpoints explicitly: How are you doing backup/restore of other resources/configuration for your clusters? Can you elaborate how/why VPACheckpoints are different than any of the resources you're already doing backup/restore for?

**Comment by matthyx** [comment]
> I think a commonly described 'good practice' is to regularly write back the current VPA recommendations to the actual requests in your Pod-owners (i.e. Deployments, StatefulSets, etc). This also helps in the cases where your VPA might be down for some reason.

Agreed this is the ideal case, however this is evolving over time and not all dev teams have enough time to check all their workloads on all clusters.

> How are you doing backup/restore of other resources/configuration for your clusters?

We don't backup as everything is already in git... except for the VPACheckpoints. Ideally we would rely on Prometheus instead of them, but in case of DRP we also lost metrics as they were stored inside the cluster.

This is why I suggested this idea to have an external cache for recommendations. Do you understand my motivations now?

**Comment by jbartosik** [comment]
What does DRP stand for here?

From what you wrote is sounds like something happens and you loose all data that was in the cluster.

I'm not sure how much storing just recommendations would help. VPA will relatively quickly have enough data to feel confident in its recommendation and overwrite whatever you applied when recreating the cluster. For example [full-vpa end to end tests](https://github.com/kubernetes/autoscaler/blob/65e7776613a4c94cefe897f96333a8e96458fd24/vertical-pod-autoscaler/e2e/v1/full_vpa.go#L96) time out after [15 minutes](https://github.com/kubernetes/autoscaler/blob/65e7776613a4c94cefe897f96333a8e96458fd24/vertical-pod-autoscaler/e2e/v1/common.go#L51).

How much time VPA will take to apply recommendations will depend on details of the situation. I think that the closer initial request is to the recommendation VPA makes the longer it will take (but also the less it matters because change is smaller). If my intuition is correct I'm not sure if it's worth the extra complication - requests will be the same with copying just recommendations and without that quickly.

You could copy whole VPA checkpoint out of cluster, then copy it back to the cluster so VPA will have data backing up recommendations too it would help more (new data will change recommendation at usual pace). This would help even if you restore checkpoint that's ~ 1/ day old (IIRC the most recent day of data has as much weight as the other 7 days of data VPA stores).

Did something like this happen? Can you check how long would it take for requests to get back to levels from before cluster went down? Is it feasible to start cluster bigger then scale it down as requests go down? Or wait for some pods to get lower requests before all start?

**Comment by matthyx** [comment]
> What does DRP stand for here?

Yes lost everything and redeploy via gitops.

> VPA will relatively quickly have enough data to feel confident in its recommendation and overwrite whatever you applied when recreating the cluster. For example [full-vpa end to end tests](https://github.com/kubernetes/autoscaler/blob/65e7776613a4c94cefe897f96333a8e96458fd24/vertical-pod-autoscaler/e2e/v1/full_vpa.go#L96) time out after [15 minutes](https://github.com/kubernetes/autoscaler/blob/65e7776613a4c94cefe897f96333a8e96458fd24/vertical-pod-autoscaler/e2e/v1/common.go#L51).

Interesting... it never happened because VPA in this cluster were set on "initial". Maybe I should conduct a test with "automatic" and be confident enough the killing will only happen when there is too much difference between the actual and recommended values.

> You could copy whole VPA checkpoint out of cluster, then copy it back to the cluster so VPA will have data backing up recommendations too it would help more (new data will change recommendation at usual pace).

Yes, initial tests prove that. I was afraid restoring VPACheckpoints would fail because data is stored inside the status, but it worked.

I think we will make a full scale test with "automatic" and if that works I'll close this issue.
Thanks @jbartosik and @voelzmo for your ideas!

**Comment by matthyx** [comment]
Real "at scale" test will be next Thursday...

**Comment by matthyx** [comment]
For the record restoring VPACheckpoints works, but you need to ensure VPA pods are stopped when you perform the restore.
