### ISSUE TITLE
Cluster autoscaler improvements for AI workloads

### ISSUE THREAD

**Issue by asm582** [kubernetes/autoscaler#5170]
**Which component are you using?**:
Cluster autoscaler component which scales Kubernetes cluster

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

We see that the current cluster autoscaler (CA) reacts to pending pods, this may not work well for AI/HPC workloads, we outline the scenarios below:

- CA reacts to pending pods, When a large number of pods are being co-scheduled it can wait tens of minutes with pending pods before triggering scale-up, stressing the control plane.
- When multiple AI/HPC workloads are submitted to the cluster, none of the jobs may progress even after scale-up by CA due to its inability to understand gang scheduling.
  - Example: user submitted 10 AI/HPC jobs (with 10 * N pods), based on N pending pods, lets's assume CA scaled to 10 nodes, and worst case only the head nodes of all the jobs got scheduled, such partial jobs will cause no user workloads to make progress.
- CA reactive scaling can hamper cluster scale-up when a user does not have sufficient quota to create pods in a namespace.
- CA performs termination based on traditional compute (i.e. CPU and memory ) utilization threshold which may not work for AI workload(s).
  - AI workload which uses GPU with large GPU memory may cause low CPU and memory utilization on the node which could lead to premature termination.
  - Setting the termination threshold to a very low value will cause CA to not evict any nodes.
- CA terminates nodes one at a time, scaling down a cluster that uses tens or hundreds of nodes will take time.
- Selection of Machineset(s) to scale cluster is random (or complex via expander) and periodically it causes over-provisioning.

**Describe the solution you'd like.**:

Looking for feedback on a better solution to have holistic autoscaling for large AI/HPC workloads

**Describe any alternative solutions you've considered.**:

We have not encountered any alternative solution yet, please share if you have a solution to above shortcomings.

**Additional context.**:

I had opened the same issue here: https://github.com/kubernetes/community/issues/6840 which will be closed.

**Comment by x13n** [comment]
Thanks for creating this issue, I believe this is an important use case Cluster Autoscaler should support. Some of the pain points you're raising require fundamental changes to how CA operates, but some should already work properly with the right setup. Let me go through them one by one:

> * CA reacts to pending pods, When a large number of pods are being co-scheduled it can wait tens of minutes with pending pods before triggering scale-up, stressing the control plane.

Why does CA wait for tens of minutes in this scenario? CA runs iterations of the main loop using a fixed interval, so I guess this has something to do with [coscheduling plugin](https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/pkg/coscheduling) holding pods from reaching CA? This plugin isn't really compatible with CA, which is one of the reasons why it wasn't moved to in-tree plugins, see discussion in https://github.com/kubernetes/kubernetes/issues/105802 

> * When multiple AI/HPC workloads are submitted to the cluster, none of the jobs may progress even after scale-up by CA due to its inability to understand gang scheduling.

I think this is one of the reasons behind https://github.com/kubernetes-sigs/kueue We should make sure it works well with CA.

> * CA reactive scaling can hamper cluster scale-up when a user does not have sufficient quota to create pods in a namespace.

Yup, no way around that without making CA understand some pods should be grouped.

> * CA performs termination based on traditional compute (i.e. CPU and memory ) utilization threshold which may not work for AI workload(s).

I don't think this one is true. GPU nodes are evaluated based on GPU utilization, not cpu/memory utilization:

https://github.com/kubernetes/autoscaler/blob/4ff4903f6839882550d05b6b2a8eae7f813c9fdc/cluster-autoscaler/core/scaledown/eligibility/eligibility.go#L158-L168

> * CA terminates nodes one at a time, scaling down a cluster that uses tens or hundreds of nodes will take time.

CA *drains* nodes one at a time, empty nodes (i.e. containing only daemonsets) are removed in bulk. Parallel drain is WIP though, this is tracked in https://github.com/kubernetes/autoscaler/issues/5079

> * Selection of Machineset(s) to scale cluster is random (or complex via expander) and periodically it causes over-provisioning.

There are multiple expanders to choose from, so yes, this can be complex (except for a managed setting where CA flags are fine-tuned already). However, even random expander shouldn't cause overprovisioning. If that happens, it's could be due to a bug in the cloudprovider-specific code.

I think the most CA-friendly way of addressing the fundamental CA compatibility problem is through some new k8s API representing a group of pods. If CA understood such API, it could trigger a scale up for all of them in a single go (or error out, e.g. due to lack of quota). https://github.com/kubernetes/enhancements/pull/3371 looks promising, but autoscaling support hasn't been fully fleshed out yet.

**Comment by kerthcet** [comment]
Some supplements:

> Why does CA wait for tens of minutes in this scenario? CA runs iterations of the main loop using a fixed interval, so I guess this has something to do with [coscheduling plugin](https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/pkg/coscheduling) holding pods from reaching CA? This plugin isn't really compatible with CA, which is one of the reasons why it wasn't moved to in-tree plugins, see discussion in https://github.com/kubernetes/kubernetes/issues/105802

We just proposed a KEP https://github.com/kubernetes/enhancements/issues/3521 to make scheduling switchable, I think it also helps.

> When multiple AI/HPC workloads are submitted to the cluster, none of the jobs may progress even after scale-up by CA due to its inability to understand gang scheduling.

This also looks like the capacity of gang-scheduling, we have the coscheduling plugin, and further, a new pod group api is on design, see https://github.com/kubernetes/enhancements/pull/3371 . 

> I think this is one of the reasons behind https://github.com/kubernetes-sigs/kueue We should make sure it works well with CA.

And yes, k-sigs/kueue is also helpful in job queueing with limited resources. Closely integration with autoscaling is one of our goals.

**Comment by Luke-Smartnews** [comment]
We had the same issue, in our case our users are deploying more than 2k spark pods on k8s at the same time which costs CA about 20m to scale out.
I think the issue is [here](https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-release-1.25/cluster-autoscaler/core/equivalence_groups.go#L65), CA is only using ownerReference UID to group pods. in our case the spark pods don't have the same owner UID.

We use a [workaround](https://github.com/smartnews/k8s-autoscaler/pull/3) by using another UID from the pod labels.
I hope CA can support some custom labels to identify extra ownerReference.

**Comment by x13n** [comment]
I think instead of custom labels, CA should just use a hash of all relevant Pod fields. Today there's a comparison function: 

http://go/k8s.io/autoscaler/blob/e8d3e9b1d986d540a21913b756cb2b47ffddb918/cluster-autoscaler/utils/utils.go#L64-L101

It should be quite straightforward to calculate a hash in a similar manner instead of relying on owner refs as hints for similarity. That'd also have an extra optimization benefit of considering identical pods as similar even if they belong to completely different controllers.
