### ISSUE TITLE
Please add a proper release tag for vpa 0.12

### ISSUE THREAD

**Issue by DebakelOrakel** [kubernetes/autoscaler#5197]
**Which component are you using?**: vertical-pod-autoscaler

**What version of the component are you using?**: 0.11

Component version: 

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What environment is this in?**:

**What did you expect to happen?**: A proper release tag for the new version.

**What happened instead?**: no release tag, so our renovate failes to update our downstream deployment.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by jbartosik** [comment]
There are  [vertical-pod-autoscaler-0.12.0](https://github.com/kubernetes/autoscaler/tree/vertical-pod-autoscaler-0.12.0) and [vertical-pod-autoscaler/v0.12.0 ](https://github.com/kubernetes/autoscaler/tree/vertical-pod-autoscaler/v0.12.0) tags. VPA 0.11.0 had similar tags.

Should there be another one?

**Comment by jbartosik** [comment]
Looking at timestamps I think that you opened this issue before I created [VPA 0.12.0 release](https://github.com/kubernetes/autoscaler/releases/tag/vertical-pod-autoscaler-0.12.0) and before I created tags associated with it.

I cut the branch some time ago but then I had to delay actually creating VPA release for a while because I noticed that we should update dependencies some more and needed to test the changes.

Since I think the tags are there and it's just that there was some time between creation of VPA 0.12 release branch and actually creating 0.12.0 release I'm closing the issue.

Please reopen it if you think something is wrong with tags or you have more questions.
