### ISSUE TITLE
The vpa updater modifies the limit resources of the container, resulting in a very large cpu and memory. What is this based on? It is a bit unreasonable?

### ISSUE THREAD

**Issue by AllenZMC** [kubernetes/autoscaler#5217]
**Which component are you using?**:

vertical-pod-autoscaler
**What version of the component are you using?**:
0.9.0

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What environment is this in?**:
openshift 4.10

**What did you expect to happen?**:

**What happened instead?**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
The vpa updater modifies the limit resources of the container, resulting in a very large cpu and memory. What is this based on? It is a bit unreasonable?

**Comment by jbartosik** [comment]
VPA will set resource request based on its recommendation. If pod has limit set it will also change the limit so that ratio (limit / request) is the same after it applies its changes as it was before.

For example if VPA sees a pod that has:

- 100m CPU request
- 200m CPU limit (so incoming (limit/request) ratio is 2)
- 500m CPU target recommendation
- there are no restrictions that affect what CPU request and limit VPA can set

VPA will set:

- 500m CPU request (same as target recommendation)
- 1000m CPU (1 CPU) limit (original ratio was 2, current request is 500m so to keep the ratio the same we need 2 * 500m CPU)

It will behave the same for memory (keeping ratio limit/request the same after update as it was before the update).

This is intended behavior. In particular we want to support keeping limit and request equal, so that pod is covered by SLO.

**Comment by AllenZMC** [comment]
@jbartosik   Can the (limit/request) ratio be customized?

**Comment by jbartosik** [comment]
Yes. The ratio will be the same after VPA modifies the pod as it was before the modification. So you control the ratio when you create pod and set it limit and request.

For example if you create a pod:

- If it has 100m CPU limit and 100m CPU request the ratio is 1:1. When VPA sets CPU request the limit will be equal to the limit.
- If it has 2Gi memory limit and 1 Gi memory request then the ratio is 2:1. When VPA sets memory request the limit will be 2x the request.
- If it has 1 CPU limit and 100m CPU request then the ratio is 10:1 ....

**Comment by jbartosik** [comment]
One more thing. You can tell VPA that it should only change requests of containers and leave limits as they are by setting [`ResourcePolicy VerticalPodAutoscaler.Spec.ContainerPolicies [].ControlledValues`](https://github.com/kubernetes/autoscaler/blob/e206ae2a29606a1ea25d7c4b45b753d2a48c73c1/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go#L184) to [`RequestsOnly `](https://github.com/kubernetes/autoscaler/blob/e206ae2a29606a1ea25d7c4b45b753d2a48c73c1/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go#L214).

Then VPA will not change limits. It will change requests. Note that as a result VPA won't be able to set request higher than the limit you configured (because request must be equal to or less than limit and it can't change the limit).
