### ISSUE TITLE
Cluster autoscaling w/ podAffinity rules

### ISSUE THREAD

**Issue by jbreed** [kubernetes/autoscaler#5238]
**Which component are you using?**:

helm chart - cluster autoscaler

**What version of the component are you using?**:

helm chart cluster-autoscaler-9.21.0 APP VERSION 1.23.0

Component version:

**What k8s version are you using (`kubectl version`)?**:

1.22

</pre></details>

**What environment is this in?**:

EKS

**What did you expect to happen?**:

I have a pod that gets deployed that has a label, which other pods must schedule on the same node to leverage the multus bridge adapter. This initial pod has a node affinity to set it on a specific node group. I then have several other pods that have podAffinity rules matching the label of this particular pod. I expected the original pod to be evicted and re-scheduled on a new node if the current resources (with linked pods) can not be met on that initial host.

**What happened instead?**:

When resources was full on the host with the original pod assigned, the pods with podAffinity rules linking to said pod get stuck in a pending state due to insufficient CPU while the other nodes show affinity rules not permitting it.

**How to reproduce it (as minimally and precisely as possible)**:

Have a group of 5 different pods you are deploying. Set resource requirements that will require an increase in nodes to scale. Set labels for these pods. Create a deployment for each that has podAffinity matching one of the initial pods with resources requested. If the original pods all reside on the same host, they don't get evicted onto new nodes to meet the new requirements of the pods with affinity rules requiring they run on the same node although if the nodes increased in size and moved groups between them there would be plenty of resources.

**Anything else we need to know?**:

If this isn't a feature, then could we look into making it a feature request? The only option I am currently seeing is making my own pod scheduler to determine where to schedule pods and manually move them when the autoscaler adds new nodes to the cluster.

**Comment by jbreed** [comment]
I added annotations for safe-to-evict to true, but this didn't resolve this issue or moving pods to other nodes that need to be grouped together.

**Comment by drmorr0** [comment]
I understand the problem here, but I am not sure that cluster autoscaler is the right place to solve it.  The only time cluster autoscaler will evict pods is during scaledown, if it detects that the pods running on a node can be moved somewhere else and the node can be terminated.  I think it would be a significant change in responsibilities (and a lot of work!) if cluster autoscaler were to start watching the state of the cluster and shuffling things around to satisfy unmet scheduling constraints.

My recommendation here is to write an [operator](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/) for your workload.  The operator can be responsible for watching the resources for the node your initial pod is on, and if that node doesn't have sufficient resources to schedule your remaining pods, the operator can evict the pod (maybe with a taint applied so it doesn't get immediately rescheduled to the same node?) and let the scheduler try again.

Your other option might be to look at a custom scheduler for your cluster such as [volcano](https://volcano.sh/en/docs/), which may do a better job of scheduling your workloads than the default kubernetes scheduler.

**Comment by jbreed** [comment]
@drmorr0 

Thanks. Yeah, I would prefer to not have to write my own scheduler; however, seems it may be the only option at this time.

For affinity rules, it appears requiredduringexecution is not currently implemented. Once this is implemented, it may handle the use-case I am mentioning.

**Comment by jbreed** [comment]
@drmorr0 

I think given the scheduler currently doesn't have a way for keeping affinity during execution implemented, I may have a work around that will possibly work although not resource efficient.

I am thinking of testing using pod anti-affinity rules for the main pods that have other pods linked via pod affinity rules. If these all schedule onto separate nodes, then the follow-on nodes will have enough resources given this node group only has these particular pods scheduled onto them. I would then likely need to adjust the node sizes deployed as right now I believe groups of possibly 2-3 fit onto one node whereas I will be allowing only 1 group per node. I think this will work as long as the autoscaler can add a new node based on the anti-affinity rule.
