### ISSUE TITLE
Are there any plans to fix the CVE-2021-25741 in the version 1.21.x

### ISSUE THREAD

**Issue by zhouke1991** [kubernetes/autoscaler#5255]
The autoscaler image on version 1.21.0 contains high vulnerabilities [CVE-2021-25741](https://avd.aquasec.com/nvd/2021/cve-2021-25741/). The kubernetes community fixed it after 1.21.4 ([changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md#changelog-since-v1214)). There are no fixed versions of 1.21.x in the autoscaler.
Are there any plans to fix it?
If not, can I use the CA-1.22.2 in my kubernetes environment whose version is 1.21.x? Are they compatible?

**Comment by jdumars** [comment]
Hi @mwielgus! Could you help us with this question, or direct us to someone who can?  Thanks

**Comment by YanzhaoLi** [comment]
I just have a look at how kubernetes fixes this CVE: https://github.com/kubernetes/kubernetes/pull/104253.
Thus, I think it's because autoscaler import the [k8s.io/mount-utils](http://k8s.io/mount-utils) 1.21.1-rc0 library:https://github.com/kubernetes/autoscaler/blob/c95c261d130c9c1c468da89536f6d2f5c21341fc/cluster-autoscaler/go.mod#L91 that brings this cve alert.
So the fix should be upgrading the mount-utils to 1.21.5 or later

**Comment by YanzhaoLi** [comment]
Or can experts like @mwielgus  help confirm whether autoscaler really uses the `k8s.io/mount-utils` library ? If not, I think don't need worry about this CVE.

**Comment by Bryce-Soghigian** [comment]
https://github.com/kubernetes/autoscaler/pull/5257 This Is a quick pull request updating the versions so we don't have the version with the CVE. Will touch up a bit.
