### ISSUE TITLE
CA Does not Scale Down Empty Node

### ISSUE THREAD

**Issue by fifthpostulate** [kubernetes/autoscaler#5337]
**Which component are you using?**:
cluster-autoscaler

**What version of the component are you using?**:
v1.23.0

Component version:

**What k8s version are you using (`kubectl version`)?**:
1.22

**What environment is this in?**:
AWS

**What did you expect to happen?**:
CA should scaled down empty node.

**What happened instead?**:
CA does not scale down empty node:
```###.compute.internal is not suitable for removal - memory utilization too big (0.000000)```

**How to reproduce it (as minimally and precisely as possible)**:
Set the following args for CA:
scale-down-utilization-threshold: 0
ignore-daemonsets-utilization: true

Drain node ignoring daemonsets.

**Comment by gregth** [comment]
@mjsprojects In the logs you provided notice that:
1.  `scaleDownInCooldown=true` indicates that the cluster autoscaler will not attempt any scale-down (it is cool-down). Why?
2. Well, it seems you had a scale-up very recently `lastScaleUpTime=2022-12-12 03:48:25.127779202`  
3. The autoscaler will put scale-down in cooldown for a duration indicated by the `--scale-down-delay-after-add` flag (default 10 minutes) after the scale-up.  
4. So, since that duration has not elapsed yet, no scale-down will be attempted.

**Comment by gregth** [comment]
@fifthpostulate the cluster autoscaler will consider underutilized any node that has **utilization < threshold** (note the strict inequality).

Since you have set `--scale-down-utilization-threshold: 0`, any node shall have utilization < 0, which is impossible. 
You should try a greater and more reasonable amount.

**Comment by mjsprojects** [comment]
Just to clarify the behavior we were seeing, CA was scaling our node groups out to the "maximum" value, even when each node was only being used about 10% and had 8 pods running in a node group with a maximum of 20 nodes, the other nodes had pods running such as cloudwatch-agent and cloudwatch-fluent-bit but no application pods, and I was passing the ignore-daemonsets-utilization flag.

**Comment by fifthpostulate** [comment]
> 

Hi @gregth, thank you for your response.

From reading the documentation, the behavior of scaling down an underutilized node and an empty node are different. An underutilized node will not be terminated until the scale-down-unneeded-time is exhausted, while an empty node can be terminated immediately. That is the desired behavior.

Regarding the scale-down-utilization-threshold, please see this from the FAQ documentation [here](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-prevent-cluster-autoscaler-from-scaling-down-non-empty-nodes):

"How can I prevent Cluster Autoscaler from scaling down non-empty nodes?
CA might scale down non-empty nodes with utilization below a threshold (configurable with --scale-down-utilization-threshold flag).

To prevent this behavior, set the utilization threshold to 0."

That implies that the autoscaler will scale down an empty node with scale-down-utilization-threshold set to 0.

**Comment by gregth** [comment]
@fifthpostulate your comment is right, thanks for mentioning these details that I had overlooked.

I believe that, for some reason that the node you are referring to, is not considered empty from the cluster autoscaler. A node is considered **empty** if the node runs only DamemonSet Pods, and no other Pod on the node exists. 

Does the node you consider empty run only DS Pods?

**Comment by fifthpostulate** [comment]
Hi @gregth, yes this is after running `kubectl drain --delete-emptydir-data --ignore-daemonsets`. Only DamemonSet Pods remain on the node.

**Comment by yhrunyk** [comment]
I use CA 1.23.1 and constantly see such logs `scale_down.go:448] Node ***.ec2.internal - memory utilization 0.000000`. The interesting thing is that after CA shows such a log it stops evaluating the node memory, though it still continues to evaluate CPU e.g `cpu utilization 0.545455`.

I'm wondering how it is possible that a node can have 0.0000 memory usage(actually it is  if there are at least some DaemonSets running on the node (I don't use --ignore-daemonsets-utilization flag).

**Comment by gregth** [comment]
With regards to the initial report: indeed, what you observed can be explained in `cluster-autoscaler-release-1.22` release branch:
1. The main loop of the CA calls `UpdateUnneededNodes()` to update the internal state of the autoscaler with the nodes that are not needed in the clusters (i.e., nodes with low utilization, for which the Pods can be moved elsewhere, etc).
https://github.com/kubernetes/autoscaler/blob/1f9b4e0e4648f358b631a9fc2dfadf4c5bbe63fc/cluster-autoscaler/core/static_autoscaler.go#L499-L502
2. `UpdateUnneededNodes()` will call `checkNodeUtilization()` to check if the utilization is below threshold:
https://github.com/kubernetes/autoscaler/blob/1f9b4e0e4648f358b631a9fc2dfadf4c5bbe63fc/cluster-autoscaler/core/scale_down.go#L491
3. In case the current utilization is 0 **and** the threshold is set to 0, the node will be considered to be *above* utilization threshold:
https://github.com/kubernetes/autoscaler/blob/1f9b4e0e4648f358b631a9fc2dfadf4c5bbe63fc/cluster-autoscaler/core/scale_down.go#L650-L653 and thus, it will be considered as unremovable: https://github.com/kubernetes/autoscaler/blob/1f9b4e0e4648f358b631a9fc2dfadf4c5bbe63fc/cluster-autoscaler/core/scale_down.go#L438-L446 and thus unremovable
4. Then, during the scale-down, `TryToScaleDown()` will fetch nodes to consider for removal from the pool of *unneeded* nodes:
https://github.com/kubernetes/autoscaler/blob/1f9b4e0e4648f358b631a9fc2dfadf4c5bbe63fc/cluster-autoscaler/core/scale_down.go#L828  and will pass them as `candidateNames` to `getEmptyNodes()`: https://github.com/kubernetes/autoscaler/blob/1f9b4e0e4648f358b631a9fc2dfadf4c5bbe63fc/cluster-autoscaler/core/scale_down.go#L926 

So, some notes:
1. Setting the threshold to 0, will definitely not work. In my view, this arises because of the strict `utilization >= threshold` condition, which defines a node as unremovable. Setting a slightly bigger threshold close to zero would do the trick. 
2. The code walk-through I provide depicts the rationale for the 1.22 release. Since then, the autoscaler has gone through major restructuring wrt scale-down, and I have not confirmed if the behavior still exists.
3. Let's wait for the input from the upstream team to confirm whether this was a design choice or a corner case bug.

**Comment by gregth** [comment]
1. First let's note that when it comes to utilization, the autoscaler will:
    1. Calculate & log, only the GPU utilization, if the node has GPU
    2. Otherwise, the max between CPU and Memory
https://github.com/kubernetes/autoscaler/blob/1f9b4e0e4648f358b631a9fc2dfadf4c5bbe63fc/cluster-autoscaler/simulator/cluster.go#L220-L250
2. The main loop of the autoscaler repeatedly evaluates the utilization of the various nodes of the cluster, and logs it: https://github.com/kubernetes/autoscaler/blob/1f9b4e0e4648f358b631a9fc2dfadf4c5bbe63fc/cluster-autoscaler/core/scale_down.go#L448. So, the logs you see should be normal.
3. The utilization is based on the `requests` of the containers, as you rightly stated.
4. If the `--ignore-daemonsets-utilization` is set to `false` (default value), then the CA removes the DaemonSet Pods requests from the node's allocatable:
https://github.com/kubernetes/autoscaler/blob/1f9b4e0e4648f358b631a9fc2dfadf4c5bbe63fc/cluster-autoscaler/simulator/cluster.go#L298
 That may be a bit tricky, but ultimately the utilization is:
a) **Case A - Do not ignore DS**: All_pod_requests / NodeAllocatable
b) **Case B - Ignore DS**: NonDaemonSetPodRequests / (NodeAllocatable - DaemonSetPodRequest)
5. Do your DaemonSet containers request any resources? If they do not, your utilization will be 0.

**Comment by rentseen** [comment]
> With regards to the initial report: indeed, what @fifthpostulate observer can be explained in `cluster-autoscaler-release-1.22` release branch:
> 
> 1. The main loop of the CA calls `UpdateUnneededNodes()` to update the internal state of the autoscaler with the nodes that are not needed in the clusters (i.e., nodes with low utilization, for which the Pods can be moved elsewhere, etc).
>    https://github.com/kubernetes/autoscaler/blob/1f9b4e0e4648f358b631a9fc2dfadf4c5bbe63fc/cluster-autoscaler/core/static_autoscaler.go#L499-L502
> 2. `UpdateUnneededNodes()` will call `checkNodeUtilization()` to check if the utilization is below threshold:
>    https://github.com/kubernetes/autoscaler/blob/1f9b4e0e4648f358b631a9fc2dfadf4c5bbe63fc/cluster-autoscaler/core/scale_down.go#L491
> 3. In case the current utilization is 0 **and** the threshold is set to 0, the node will be considered to be _above_ utilization threshold:
>    https://github.com/kubernetes/autoscaler/blob/1f9b4e0e4648f358b631a9fc2dfadf4c5bbe63fc/cluster-autoscaler/core/scale_down.go#L650-L653
>     and thus, it will be considered as unremovable: https://github.com/kubernetes/autoscaler/blob/1f9b4e0e4648f358b631a9fc2dfadf4c5bbe63fc/cluster-autoscaler/core/scale_down.go#L438-L446
>     and thus unremovable
> 4. Then, during the scale-down, `TryToScaleDown()` will fetch nodes to consider for removal from the pool of _unneeded_ nodes:
>    https://github.com/kubernetes/autoscaler/blob/1f9b4e0e4648f358b631a9fc2dfadf4c5bbe63fc/cluster-autoscaler/core/scale_down.go#L828
>      and will pass them as `candidateNames` to `getEmptyNodes()`: https://github.com/kubernetes/autoscaler/blob/1f9b4e0e4648f358b631a9fc2dfadf4c5bbe63fc/cluster-autoscaler/core/scale_down.go#L926
> 
> So, some notes:
> 
> 1. Setting the threshold to 0, will definitely not work. In my view, this arises because of the strict `utilization >= threshold` condition, which **renders the node as unremovable**, and thus will not be considered as an empty node to remove. Setting a slightly bigger threshold close to zero would do the trick.
> 2. The code walk-through I provide depicts the rationale for the 1.22 release. Since then, the autoscaler has gone through major restructuring wrt scale-down, and I have not confirmed if the behavior still exists.
> 3. Let's wait for the input from the upstream team to confirm whether this was a design choice or a corner case bug.

Hi, @gregth , will empty nodes be scaled down in latest CA version?
