### ISSUE TITLE
Don't block scale down on pods owned by custom controllers

### ISSUE THREAD

**Issue by x13n** [kubernetes/autoscaler#5387]
**Which component are you using?**:

/label cluster-autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

As the k8s ecosystem grows, a hardcoded list currently used by CA is not going to work with custom controllers. In https://github.com/kubernetes/autoscaler/blob/ee667550c081d99924e7b1100f0c1596551be3d6/cluster-autoscaler/utils/drain/drain.go#L76, only a few controllers are handled. We could extend CA to treat all ownerReferences with `controller: true` as replicated. In case of controllers that do not recreate evicted pods, existing annotations could be used (`cluster-autoscaler.kubernetes.io/safe-to-evict`: `false` or `cluster-autoscaler.kubernetes.io/daemonset-pod`: `true`) to prevent CA from evicting such pods.

**Describe the solution you'd like.**:

Just look at `controller` field in owner references and treat all controller-owned pods as replicated by default.

**Describe any alternative solutions you've considered.**:

Add some extension mechanism (CRD?) allowing CA to know how to handle specific controllers. This might be useful in the long term, but will require much more work.

**Additional context.**:

**Comment by Bryce-Soghigian** [comment]
Could i pick this up?

**Comment by Bryce-Soghigian** [comment]
@vadasambar Are you still planning an approach for this or can I pick it up?

**Comment by vadasambar** [comment]
> @vadasambar Are you still planning an approach for this or can I pick it up?

Thank you for noticing I was looking at this issue. I am new to cluster-autoscaler code. I have an understanding of the problem. I am trying to solidify my approach which goes something like this:
1. Add a map of `Kind` to `Lister` in [`ListerRegistry`](https://github.com/kubernetes/autoscaler/blob/c127763a4529d7d07961102856afe0ba8781f8ee/cluster-autoscaler/utils/kubernetes/listers.go#L38-L49) called `GenericListerMap` (<- the name can change)
2. Every time we encounter a pod owner reference that doesn't reference in-built types like `Deployment`. `StatefulSet` etc., (for which we already have Listers), we add a new lister entry to `GenericListerMap`. I want to leverage the [`dynamiclister`](https://pkg.go.dev/k8s.io/client-go@v0.26.0/dynamic/dynamiclister) library here

As of now, I am trying to figure out a way to do 2 in a nice way. If you have any feedback on the approach, I would love to know more (I am not sure if my approach is the best way to solve the problem). 

As for the ticket, if this ticket needs to be worked on urgently (or you are stuck because of it), feel free to pick it up. I might continue looking at it in the background to see if my solution matches yours in the end (not necessarily for raising a PR but more for understanding).

**Comment by vadasambar** [comment]
> Using a lister is an extra layer of safety - to ensure not just that the pod is owned, but also that the owner didn't disappear in the meantime.

That makes sense. Thank you for the feedback! 

> P.S.: I don't think we will need listers at all. I might have misunderstood the problem. We just need to treat anything with owner reference as replicated.

This doesn't sound true anymore. Having a generic lister does have value. It makes sense to use the listers and query for owners like our existing code does but for a wider range of owner types (not limited to the built-in types like Jobs, Statefulsets, Deployments etc.,)
