### ISSUE TITLE
[Question] - Can we have long term confidence in the "safe-to-evict" annotation?

### ISSUE THREAD

**Issue by netzere** [kubernetes/autoscaler#5458]
Hi!

We have some workload that runs as k8s Jobs on GKE and we **cannot allow to evict them until they finish, no matter what**. 
Currently, this workload runs on a "static" nodepool without autoscaling for that reason.
We'd like to move this to a nodepool with autoscaling,  while adding the `"cluster-autoscaler.kubernetes.io/safe-to-evict": "false"` annotation.
For this specific workload, we don't care about costs at all, we just want to have some guarantee that they won't be evicted.

(Yes, we are aware that these pods can be terminated at any time because of node/hardware failure etc)

Main question here:
[**_We run on GKE_**] - can we have a longterm confidence that this annotation is here to stay and there won't be any implementation changes in that area?

Thanks!

**Comment by gregth** [comment]
@netzere this functionality has been around for a long time, since 2018, so in my view, there should not be any reason for this to be removed.

However, if you need to be super confident that the Pod won't be evicted, why don't you configure it with the proper PodDisruptionBudget (`minAvailable: 1`), see https://kubernetes.io/docs/tasks/run-application/configure-pdb/.

The cluster autoscaler respects the PDB and takes them into consideration in its simulations, but most importantly the API Server enforces that a Pod will not be evicted if the PDB does not permit it. In that way, you will not rely solely on the cluster autoscaler that might take a wrong decision (quite unlikely) or dropping the safe-to-evict feature; the API Server will safeguard your Pod.
