### ISSUE TITLE
VPA: The admission controller does not apply recommendations to pods when deploying using Argo Rollouts

### ISSUE THREAD

**Issue by kodmaskinen** [kubernetes/autoscaler#5598]
**Which component are you using?**:
vertical-pod-autoscaler

**What version of the component are you using?**:
Component version: 0.13 (same issue in 0.11)

**What k8s version are you using (`kubectl version`)?**:
1.23.14

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.17", GitCommit:"953be8927218ec8067e1af2641e540238ffd7576", GitTreeState:"clean", BuildDate:"2023-03-01T02:23:41Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.14-eks-ffeb93d", GitCommit:"96e7d52c98a32f2b296ca7f19dc9346cf79915ba", GitTreeState:"clean", BuildDate:"2022-11-29T18:43:31Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:
AWS

**What did you expect to happen?**:
When deploying using Argo Rollouts, with a VPA (that have a recommendation) targeting the Rollout, I expect the VPA admission controller to patch the pod with the provided resource recommendations.

**What happened instead?**:
The admission controller can’t find a VPA matching the pod. 

This only occurs when deploying a new version, adding an annotation to the pod template etc. If we wait a while and only scale up the Rollout or delete a pod, then the newly launched pod will be patched correctly.

**How to reproduce it (as minimally and precisely as possible)**:
- (Deploy Argo Rollouts in cluster.)
- Create a Rollout object (using blue/green strategy).
- Create a VPA object referencing the Rollout.
- Update the rollout.
- The newly launched pods will not have the recommendations applied and the admission controller will log “No matching VPA found”.

**Anything else we need to know?**:
I don’t think so, it’s pretty easy to reproduce.

My guess is that it has something to do with the fact that the `rollouts-pod-template-hash` label has a new value on the launching pod when a new version is deployed. This is not the case when pod launch is triggered by scaling up or deleting a pod.

**Comment by voelzmo** [comment]
Hey @kodmaskinen, I tried to reproduce this, but couldn't.
Here's what I did:
* used my 1.24.10 k8s cluster running VPA 0.13.0
* installed argo rollouts as [described in the docs](https://argo-rollouts.readthedocs.io/en/stable/)
* modified the [VPA hamster example](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/examples/hamster.yaml) from `Deployment` to `Rollout` as [described in their docs](https://argo-rollouts.readthedocs.io/en/stable/migrating/)
* used a blue/green strategy, because you mentioned that explicitly
* added two services for the *active* and *preview* `ReplicaSet`
* Deployed it once, saw that the Pods were getting recommendations and updated accordingly by VPA
* Modified the hamster Pod's startup args (changed the times from `0.5` to `0.9`) and re-deployed
* Saw that a blue-green rollout happened: a new ReplicaSet was created with two additional Pods. The Pods had the additional label you mentioned (`rollouts-pod-template-hash`), which was different between the ReplicaSets and was being used by the Service to decide which Pods to point to
* During this time, the `/scale` subresource of the `Rollout` object still pointed to the old Pods
```
k get rollout hamster --subresource=scale -oyaml
apiVersion: autoscaling/v1
kind: Scale
metadata:
  creationTimestamp: "2023-04-05T08:23:41Z"
  name: hamster
  namespace: default
  resourceVersion: "6876431"
  uid: c32c42bc-f297-4a33-b4bb-22aeb48ecbef
spec:
  replicas: 2
status:
  replicas: 2
  selector: app=hamster,rollouts-pod-template-hash=76cf6d9f8c
```
* After the 120 seconds waiting period before auto-promotion was over, the service was switched to the new `rollouts-pod-template-hash` and the `/scale` subresource in the Rollout object as well
```
k get rollout hamster --subresource=scale -oyaml
apiVersion: autoscaling/v1
kind: Scale
metadata:
  creationTimestamp: "2023-04-05T08:23:41Z"
  name: hamster
  namespace: default
  resourceVersion: "6880972"
  uid: c32c42bc-f297-4a33-b4bb-22aeb48ecbef
spec:
  replicas: 2
status:
  replicas: 2
  selector: app=hamster,rollouts-pod-template-hash=74d4fbbc7f
```
* I saw that the new Pods are getting updated by VPA and that the VPA object does *not* indicate that it is not matching any Pods
```
k get pods hamster-74d4fbbc7f-5lf5w -oyaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    vpaObservedContainers: hamster
    vpaUpdates: 'Pod resources updated by hamster-vpa: container 0: cpu request, memory
      request'
(...)
```

<details><summary>Here's my resulting configuration</summary>
<code>
# This config creates a deployment with two pods, each requesting 100 millicores
# and trying to utilize slightly above 500 millicores (repeatedly using CPU for
# 0.5s and sleeping 0.5s).
# It also creates a corresponding Vertical Pod Autoscaler that adjusts the
# requests.
# Note that the update mode is left unset, so it defaults to "Auto" mode.
---
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: hamster-vpa
spec:
  # recommenders field can be unset when using the default recommender.
  # When using an alternative recommender, the alternative recommender's name
  # can be specified as the following in a list.
  # recommenders: 
  #   - name: 'alternative'
  targetRef:
    apiVersion: "argoproj.io/v1alpha1"
    kind: Rollout
    name: hamster
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 100m
          memory: 50Mi
        maxAllowed:
          cpu: 1
          memory: 500Mi
        controlledResources: ["cpu", "memory"]
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hamster
spec:
  selector:
    matchLabels:
      app: hamster
  replicas: 2
  template:
    metadata:
      labels:
        app: hamster
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534 # nobody
      containers:
        - name: hamster
          image: registry.k8s.io/ubuntu-slim:0.1
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
          command: ["/bin/sh"]
          args:
            - "-c"
            - "while true; do timeout 0.9s yes >/dev/null; sleep 0.9s; done"
  strategy:
    blueGreen: 
      # activeService specifies the service to update with the new template hash at time of promotion.
      # This field is mandatory for the blueGreen update strategy.
      activeService: rollout-bluegreen-active
      # previewService specifies the service to update with the new template hash before promotion.
      # This allows the preview stack to be reachable without serving production traffic.
      # This field is optional.
      previewService: rollout-bluegreen-preview
      # autoPromotionEnabled disables automated promotion of the new stack by pausing the rollout
      # immediately before the promotion. If omitted, the default behavior is to promote the new
      # stack as soon as the ReplicaSet are completely ready/available.
      # Rollouts can be resumed using: `kubectl argo rollouts promote ROLLOUT`
      autoPromotionEnabled: true
      autoPromotionSeconds: 120
---
kind: Service
apiVersion: v1
metadata:
  name: rollout-bluegreen-active
spec:
  selector:
    app: hamster
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: rollout-bluegreen-preview
spec:
  selector:
    app: hamster
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
</code>
</details>

So at this point in time it seems to me that VPA works fine with argo Rollouts and there might be something specific to your setup? Here's what you could do
* verify that VPA *without* argo Rollouts is working correctly in your env
* verify that the yamls I pasted above using argo Rollouts are working in your env like I described

Hope that helps!

**Comment by kodmaskinen** [comment]
Thank you, @voelzmo! I'll have another look at this as soon as I can.

**Comment by kodmaskinen** [comment]
Sorry for the delay. I just tested this again, using your configuration, and I saw the exact same issue. 

When updating the Pod's startup args, the new pods are created without any `vpaUpdates` annotation and the admission controller logs `No matching VPA found for pod default/hamster-74d4fbbc7f-%`.

If I wait a while, the updater will evict the pods, and at that point the admission controller do find the VPA and will patch the pods. The same thing happens if I manually evict/terminate the pods a couple of seconds after they are first launched (the new pods are then patched properly). So it seems like it takes a while for the admission controller to "see" that the pods belong to the Rollout specified in the VPA config.

I see the same behavior both on EKS (1.23 and 1.24) and locally with a Minikube cluster (1.24).

**Comment by voelzmo** [comment]
@kodmaskinen Thanks for getting back to this one! I think I might have misunderstood the problem you're seeing here when I first investigated it. So what I'm understanding now is that after updating the `Rollout` object, the Pods of the new version are assigned the _default_ resources, which come from the template inside the `Rollout` – not the resources which the VPA already computed for the previous version Pods. You traced this back to the admission controller not being able to find a matching VPA for these new version Pods. Does that sound right?

I'll try to look into this today and see what's happening.
