### ISSUE TITLE
CA to support via registry.k8s.io for Kubernetes version 1.23

### ISSUE THREAD

**Issue by imoisharma** [kubernetes/autoscaler#5714]
**Which component are you using?**:
Cluster Autoscaler version 1.23

EKS

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

Starting April 3, 2023, the Kubernetes project will stop publishing community-owned images (known as community images) to the old image registry `[k8s.gcr.io](http://k8s.gcr.io/)` as announced in the following blog [1]. The `[k8s.gcr.io](http://k8s.gcr.io/)` registry will be frozen. No further images for Kubernetes and related sub-projects will be pushed to the registry. If deemed necessary, the Kubernetes project reserves the right to remove existing community images from the old registry. EKS clusters by default are not dependent on images hosted in the community-owned registry. If your applications are configured to use community-owned images from the legacy registry, you may experience availability issues. You can avoid the issue by updating your application and its dependencies to pull images from the new image registry: `[registry.k8s.io](http://registry.k8s.io/)`. The new registry contains all the community images and image tags from the old registry. 

What is the problem?
On November 28, 2022, the Kubernetes project announced that it would move community images from the `[k8s.gcr.io](http://k8s.gcr.io/)` registry to a new community owned registry: `[registry.k8s.io](http://registry.k8s.io/)` [2]. This new registry spreads load across multiple cloud providers and regions, functioning like a content delivery network (CDN) for Kubernetes container images. This change reduces the project's reliance on a single entity and provides a faster download experience for users. While the Kubernetes project changed the default to the new image registry, the old registry was still supported. Starting April 3, 2023, the old `[k8s.gcr.io](http://k8s.gcr.io/)` registry will be frozen. The Kubernetes project will stop publishing community images to the old registry. Existing community images in the registry could be removed in the future. Your applications may carry availability risks if your deployments are dependent on images hosted in the old `[k8s.gcr.io](http://k8s.gcr.io/)` registry.

**Describe the solution you'd like.**:
Point the CA image for v1.23 -> new registry i.e. registry.k8s.io

**Comment by Shubham82** [comment]
Hi @imoisharma 
This issue is already resolved by the following PR: #5494
similar to issue:  #5491

**Comment by imoisharma** [comment]
Hi @Shubham82, can you clarify this to me? I have download CA version 1.23 and its image is referred to as` v1.21.0` and https://github.com/kubernetes/autoscaler/releases?q=1.23&expanded=true shows `k8s.gcr.io/autoscaling/cluster-autoscaler:v1.23.0`image not `registry.k8s.io/autoscaling/cluster-autoscaler:v1.23.0`
<img width="1510" alt="Screenshot 2023-05-02 at 07 46 16" src="https://user-images.githubusercontent.com/30807347/235537245-8569c36f-fffd-4aa6-af63-74405df33795.png">

**Comment by Shubham82** [comment]
Hi @imoisharma 
These changes are done in the previous release in k8s v1.27 and corresponding CA v1.27 (which is going to release soon). So these changes are reflected in the CA v1.27 or master branch. That's why it is not reflected in the previous version of the Cluster Autoscaler. 

And the screenshot you mentioned above is related to the aws cloud provider, In CA there is inbuilt support for multiple cloud provider which has their own example files to test CA on their cloud provider, they have their own owners to maintain those files. So sometimes it is missed, so we can update it in future releases because this is only for testing CA on the particular cloud provider.

See this file is now updated to the latest one of CA:
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-run-on-control-plane.yaml

**Comment by Shubham82** [comment]
@imoisharma, if your query is resolved so can we close this issue?
