### ISSUE TITLE
AWS secuiry scans Critical CVE-2021-3538 - github.com/satori/go.uuid

### ISSUE THREAD

**Issue by kannamr** [kubernetes/autoscaler#5716]
**Which component are you using?**: Cluster-autoscaler

 Cluster-autoscaler

**What version of the component are you using?**: 1.25.1, 1.26.2

Component version: 1.25.1

**What k8s version are you using (`kubectl version`)?**: 1.25.8

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version: 1.25.8

</pre></details>

**What environment is this in?**: KOPS

**What did you expect to happen?**: I want 0 vulnerabilities in the AWS scans

**What happened instead?**: the scans show 1 Critical and 1 Medium

![Screenshot 2023-04-27 at 1 45 36 PM](https://user-images.githubusercontent.com/73130996/234948599-50b0368f-5432-4488-b5a6-284899bc63d7.png)

**Comment by Shubham82** [comment]
At present `github.com/satori/go.uuid` is used only in alicloud provider. It is used in the sdk package of it, see this: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/sdk/utils/utils.go#L38

So we have to fix it there. Previously it was also in magnum and kamatera cloud providers but it was resolved for them. Here is the issue: #5218. and lots of other issues previously opened for it but closed now due to no work. Here are the following issues: #4715 and #4068.

**Comment by Shubham82** [comment]
cc @ringtail @IrisIris
PTAL!

**Comment by Shubham82** [comment]
Hi @ringtail @IrisIris

Could you please take a look?

**Comment by ringtail** [comment]
@Shubham82 sure. @IrisIris is working on it.

**Comment by Shubham82** [comment]
The corresponding PR #5749 is closed with the [comment](https://github.com/kubernetes/autoscaler/pull/5749#issuecomment-1719679276).

So closing this issue, please reopen it if it is still needed.
