### ISSUE TITLE
[Q&A][Azure] No "Cluster-Autoscaler" pod is running after enable CA in an AKS cluster

### ISSUE THREAD

**Issue by xuanhai266** [kubernetes/autoscaler#5726]
I enabled cluster autoscale in 2 node pools of my AKS cluster (using Azure Portal). It works well.  
But I check running pods in kube-system namespace and there is no pod with name "cluster-autoscaler".  
How does cluster autoscaler work in AKS cluster?  
As my understanding, it should deploy a pod with name "cluster-autoscaler-XXX" in kube-system namespace.  
Could you please explain to me?

**Comment by Bryce-Soghigian** [comment]
In Azure Kubernetes Service (AKS), autoscaling is handled directly by Azure, not a cluster-autoscaler pod like in self-managed Kubernetes. When you enable autoscaling for an AKS node pool, Azure manages the scaling automatically based on your workloads. That's why you don't see a "cluster-autoscaler" pod in the kube-system namespace in AKS.
