### ISSUE TITLE
Autoscaler unable to reallocate itself or contact DNS after scale down

### ISSUE THREAD

**Issue by DaveTaddei-CR** [kubernetes/autoscaler#582]
The autoscaler occasionally triggers a scale down which involves reallocating itself and kube-dns pods.  This has resulted in a deadlock situation whereby the remaining nodes are over-requested but a new node cannot start because no autoscaler is running.  A similar problem exists with kube-dns pods whereby the autoscaler is unable to communicate with AWS ASGs while the kube-dns is down, again resulting in a cluster which is unable to scale up.

Attempted resolutions:
* PodDisruptionBudget - no effect on small clusters (1-4 nodes)
* Allocated autoscaler to master - successful in keeping autoscaler alive but does not help DNS pods

**Comment by johanneswuerbach** [comment]
We worked around this issue by running the autoscaler on masters nodes:
```
nodeSelector:
  node-role.kubernetes.io/master: ""
```

and with host dns & network to not rely on kube-dns

```
dnsPolicy: Default
hostNetwork: true
```

**Comment by MaciekPytel** [comment]
It doesn't look like a problem that can be solved by CA in any way. By default CA will not scale-down nodes with system pods, which includes kube-dns (and I assume CA as well? it really depends how you run it - the official way is to do it on master). If you add a PDB to kube-dns, which allows 0 replicas this is you explicitly allowing CA to move it around even if it's killing the last replica. I'm happy to accept a contribution to AWS readme (for example with @johanneswuerbach config), otherwise I don't see much that we can do.

**Comment by DaveTaddei-CR** [comment]
From 1.0 onwards the docs state it will reallocate kube-system pods by default and honour any defined PDBs (I admit the documentation contradicts this in several places).  In any case we also tried adding PDBs to the kube-system pods required (tried minAvailable:1 and maxUnavailable: 0) but these were not being honoured.  We are attempting the workaround suggested by @johanneswuerbach to ease the DNS issue.

**Comment by DaveTaddei-CR** [comment]
ok, the workaround seems to be effective.  There is still an underlying issue surrounding honouring of PDBs however.  #581 is also an issue observed which may be related.

**Comment by MaciekPytel** [comment]
Can you point out where in docs it says it will reallocate kube-system pods by default? That's clearly wrong and I'd like to fix it. Regarding PDBs - we do have e2e tests for CA + PDB (https://k8s-testgrid.appspot.com/sig-autoscaling#gci-gce-autoscaling&include-filter-by-regex=pdb) and they've been passing for months now. 
If you have a case where it's not honored can you open an issue, including your CA config, PDB yaml and CA logs from when it scaled down?

**Comment by MaciekPytel** [comment]
One thing that strikes me in this issue and the other issues you reported is CA consistently scaling to 1 node. Usually it can't go below 3 or so, because scheduler spreads out kube-system pods which CA refuses to touch. 

In particular, based on the config you posted in https://github.com/kubernetes/autoscaler/issues/583 I guess you were running CA in kube-system namespace? If so it shouldn't be able to ever touch the node it was running on in the first place. Is there something else unusual in your setup that allows CA to consistently go down to just 1 node?

**Comment by DaveTaddei-CR** [comment]
We set the minimum number of nodes for this particular cluster to 1 but nothing else strikes me as particularly odd in the setup.  I think I misread the docs regarding the PDB.  The first time it appeared as though "prior to CA 0.6 nodes running kube-system pods would not be touched" and I took that to mean that now it would.  I guess the actual meaning is "from CA 0.6 onwards nodes running kube-system pods with no PDB will not be touched however PDBs will be honoured for pods which have them"

I also realised when the issue arose we were using a PDB with `maxUnavailable: 0`

**Comment by MaciekPytel** [comment]
Even if you have a minimum of 1, CA will generally not go below 3 or so because statistically 'unmovable' system pods will usually be spread on scheduler over 3 or 4 different nodes. Unless you create a PDB that _allows_ 0 replicas of those you will not go to 1 node ever. As I wrote on your other issue - it looks like you have something else deleting nodes, likely a different autoscaler.

**Comment by DaveTaddei-CR** [comment]
We only have a single autoscaler.  We frequently run with 2 nodes or less in our cluster.  We have no PDBs for kube-system pods.

**Comment by MaciekPytel** [comment]
I'm confident that CA did not remove any nodes during the time covered by log you posted on https://github.com/kubernetes/autoscaler/issues/581. The issues you describe are completely disjoint from our experience, tests and reports of our other users. 
1. A common complaint is that CA is slow to scale-down. A node cannot run any kube-system pods and must be unneeded for at least 10 consecutive minutes before it's deleted. This is not consistent with aggressive scale-down you describe.
1. CA can't scale a whole cluster down to 1 node, unless you add PDBs for kube-system pods. In particular CA will never delete a node running DNS or itself (if it's running in kube-system).
1. CA supports PDBs for almost a year. We have automated tests for them running continously and we often recommend our users to use PDBs. No one else complained that they're not respected.

This is too many unexpected things happening at the same time. It would require multiple different bugs in CA that somehow only trigger in your environment. I think a more likely explanation is that there is something in your setup that is conflicting with CA. It could be any custom scheduling mechanism, like custom scheduler, non-standard config of default scheduler, scheduler extender or some such (none of that is supported by CA). My guess is still a metric-based VM-level autoscaler running on your ASG (ie. AWS builtin autoscaler configured to run on underlying VMs, not another pod running in your cluster or anything). We had a lot of users on GCP turning on autoscaling on MIGs (basically GCP equivalent of ASG) and getting exactly the same kind of issues, before we added a warning in UI.

One last thing I can recommend is checking events on cluster-autoscaler-status configmap (`kubectl get events -n kube-system | grep ConfigMap`). Any scale-up or scale-down performed by CA will create an event. If there isn't one it's not CA adding or removing those nodes.
