### ISSUE TITLE
[AWS] Unsafe decomissioning of nodes when ASGs are out of instances

### ISSUE THREAD

**Issue by theintz** [kubernetes/autoscaler#5829]
**Which component are you using?**: cluster-autoscaler

**What version of the component are you using?**: cluster-autoscaler 1.25.1

Component version: chart cluster-autoscaler-9.28.0

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.9-eks-0a21954", GitCommit:"eb82cd845d007ae98d215744675dcf7ff024a5a3", GitTreeState:"clean", BuildDate:"2023-04-15T00:37:59Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**: AWS EKS

**What did you expect to happen?**: We are running EKS on managed nodes using cluster-autoscaler to dynamically scale up and down the sizes of the node groups. Unfortunately, sometimes AWS is unable to fulfil requests for scaling up (Could not launch On-Demand Instances. InsufficientInstanceCapacity). When that happens, cluster-autoscaler gets confused about the size of the ASG and sends unnecessary `SetDesiredCapacity` requests, which result in unsafe scaling down of the ASG (details below).
The expectation is that CA handles these situations transparently and does not scale down the ASG.

**What happened instead?**: We are observing the following behavior, by looking at both the CA logs and the CloudTrail logs of the requests sent. I don't know enough about the internal workings of the CA, so some of this is an assumption.
* Pods are pending, waiting for capacity in a given node group.
* CA wants to scale up this node group and sends a SetDesiredCapacity request to the ASG to increase the size (say from 3 -> 5). This happens async, so the CA fires off the request and goes back to doing different things. However it updates its internal representation of the ASG to be at capacity 5.
* ASG can’t scale up and returns that info to the CA.
* CA comes back around to the request and realizes the ASG is blocked. It updates its internal representation (back to 3)  but crucially for some reason it also updates the ASG, sending a number of SetDesiredCapacity requests, to revert the capacity back down to 3.
* In the meantime, a new instance might have successfully started, so the actual capacity of the ASG is now 4.
* So as a result to receiving the SetDesiredCapacity requests from the CA, the ASG terminates one (or more) of its running instances resulting in the unsafe scale down.

![image](https://github.com/kubernetes/autoscaler/assets/800124/a54d1af3-caf1-40ef-9670-86206931fa50)

See the attached image that shows the sequence of events as well.

**How to reproduce it (as minimally and precisely as possible)**: Difficult to reproduce as it only happens when the AWS capacity issues occur. We are regularly observing this behavior though, I am happy to assist with more information.

**Anything else we need to know?**:

**Comment by steelecliftonberry** [comment]
Would be great to get some insight/review here. It frequently (roughly daily) kills long-running batch jobs related to our model training and optimisation, due to causing accidental node scale down some times when AWS is out of instances (which is a constant thing). 

This happens regardless of the fact we set the do not evict annotation on these Pods, because as above the AWS out of instances issue is not properly factored in.

**Comment by gicuuu3** [comment]
Hello, hello!

We're also being impacted by this issue and would be nice to get some updates on when it can be expected. If not, are there any known workarounds to avoid the problems? (we've tried using stuff like the scaled down after scale up delay but it didn't seem to work)

Our setup has stateful pods so having the scaling group kill active nodes breaks the sessions. 

Thank you for the time and effort!

**Comment by gicuuu3** [comment]
Understood.

We've started using mixed instances and it also helped in our scenario. I guess we'll keep track of this PR and if we ever start hitting the problem again we can use this PR for our own setup also. 

Thank you for the help!

**Comment by gicuuu3** [comment]
In case anyone is still struggling with this issue, another thing we did that helped us is enabled the aws auto scaling group `scale-in protection` 

https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-instance-protection.html

Since our autoscaler always does targeted removal requests, this toggle protects us from random removal due to capacity reduction while allowing the autoscaler to still removes nodes it doesn't need in the cluster by "name"

**Comment by apy-liu** [comment]
We've also observed this happening multiple times across different clusters using cluster autoscaler v1.24.3. 

- The cluster autoscaler attempts to scale up the ASG and hits an OutOfCapacity error creating the placeholder instances as mentioned. 
- After about two minutes the instance is successfully launched
- But the cluster autoscaler has already considered it failed and tries to clean up the placeholder instances - I suspect this is happening more frequently now because of this feature to early abort on OutOfCapacity errors: https://github.com/kubernetes/autoscaler/pull/4489. The logs from the PR match what we see on the cluster:

`1 clusterstate.go:1043] Failed adding 14 nodes (14 unseen previously) to group 
kubernetes-minion-test-mc-a-amd-asg-us-east-1a due to 
OutOfResource.placeholder-cannot-be-fullfilled; 
errorMessages=[]string{"AWS cannot provision any more instances for this node group"}
...
1 auto_scaling_groups.go:287] instance 
i-placeholder-kubernetes-minion-test-mc-a-amd-asg-us-east-1b-0 
is detected as a placeholder, decreasing ASG requested size instead of deleting 
instance`

Cluster autoscaler doesn't recognize there was a successfully launched instance due to the early abort on the first FAILED status and the decreased desiredCount removes a running instance with potential workloads.

If that's the case, it seems like this would be a likely fix of respecting the original backoff duration? https://github.com/kubernetes/autoscaler/pull/5756

**Comment by apy-liu** [comment]
Hey @jlamillan thanks for taking a look and providing a detailed explanation. That makes sense to me, in that case having a flag to respect the backoff duration seems a more stable approach.

> It does seem possible that one or more of the so-called "unfulfillable" instances could actually be provisioned on the provider before DeleteInstances is called to effectively abort the original request.
Attaching some sample logs to provide some context. It looks like a race between the ASG to successfully launch the instance and the CA [cleaning up](https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-1.24.3/cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go#L446) what it thinks are placeholder instances.


`
CA Logs:

23:42:59.970791 1 auto_scaling_groups.go:438] Instance group <> has only 3 instances created while the requested count is 4. Creating placeholder instances.
23:43:00.248897 1 auto_scaling_groups.go:481] ASG <> scaling failed with {
AutoScalingGroupARN: "<>",
AutoScalingGroupName: "<>",

23:43:00.248971 1 auto_scaling_groups.go:446] Instance group <> cannot provision any more nodes!
23:43:50.698297 1 clusterstate.go:1008] Found 1 instances with errorCode OutOfResource.placeholder-cannot-be-fulfilled in nodeGroup <>
23:43:50.698330 1 clusterstate.go:1026] Failed adding 1 nodes (1 unseen previously) to group <> due to OutOfResource.placeholder-cannot-be-fulfilled;  errorMessages=[]string{"AWS cannot provision any more instances for this node group"}

23:43:50.698422 1 static_autoscaler.go:692] Deleting 1 from <> node group because of create errors
23:43:50.698440 1 auto_scaling_groups.go:297] instance i-placeholder-<id> is detected as a placeholder, decreasing ASG requested size instead of deleting instance
23:43:50.698446 1 auto_scaling_groups.go:248] Setting asg <> size to 3


From AWS console:
23:41:33 - 23:41:33.   Failed - Launching a new EC2 instance. Status reason: We currently do not have sufficient...
23:41:43 - 23:41:43.   Failed - Launching a new EC2 instance. Status reason: We currently do not have sufficient...
23:41:53 - 23:41:53.   Failed - Launching a new EC2 instance. Status reason: We currently do not have sufficient...
23:42:03 - 23:42:03.   Failed - Launching a new EC2 instance. Status reason: We currently do not have sufficient...
23:43:07 - 23:43:23.   Successful - launch of new EC2 instance in response to difference between desired and actual
23:43:53 - 23:45:35.   Successful - User request (CA) set group desired capacity changing the desired capacity from 4 to 3.
`

**Comment by jlamillan** [comment]
@apy-liu have you looked into using [termination policies](https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-termination-policies.html) or [scale-in protection](https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-instance-protection.html) as @gicuuu3 suggested as alternative ways to resolve this issue?

**Comment by apy-liu** [comment]
Yes, looking into the suggested mitigations though still hoping to get to a resolution on this through one of the proposed fixes.

**Comment by apy-liu** [comment]
Hi @gjtempleton this was the issue we raised during the SIG meeting. Would be interested to hear your feedback on this issue and the suggested PR to fix it as we're still looking for a long term fix.

**Comment by kmsarabu** [comment]
Hi @gjtempleton Could you please outline the next steps and recommend the optimal approach to address this issue? Additionally, is there any restriction on the range of older versions to which a fix can be backported when requesting a backport fix? Thanks

**Comment by apy-liu** [comment]
Hi @gjtempleton, thank you for providing your feedback at this week's SIG meeting. It sounds like the proposed solution would be adding a check before cleaning up the placeholder instance and updating the internal asgCache to reflect the new instance if it does come up. 

You had mentioned drafting up a PR for the above, so I wanted to check where we could follow along. Also wanted to check on the question @kmsarabu posed above about the range of older versions that backporting is supported. Thanks!

**Comment by drmorr0** [comment]
@gjtempleton I am uncertain about the proposed fix (checking for recent scaling activity before changing the ASG size).  I missed the SIG meeting unfortunately where this was discussed, but I _think_ this doesn't solve the problem, it just narrows the window between which a race can occur (see [my comment](https://github.com/kubernetes/autoscaler/pull/6818#discussion_r1604116007) on #6818).

I think the ideal way to handle this (and how I've seen it done in the past) is to enable scale-in protection on the ASGs (as mentioned by @gicuuu3).  This is the only way I know of to safely change the size of an ASG without accidentally terminating running nodes.

I will try to join the SIG meeting this Monday to discuss further.

**Comment by daimaxiaxie** [comment]
The problem is not just AWS, it also exists on other clouds. For example AliCloud. The root of the problem is that scaling activities on the cloud are asynchronous.
