### ISSUE TITLE
Add support for new instance types in Equinix Metal

### ISSUE THREAD

**Issue by enkelprifti98** [kubernetes/autoscaler#5857]
**Which component are you using?**:

Cluster Autoscaler for Equinix Metal.
**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

The current version is missing support for new instance plan types such as the m3.small.x86. As far as I can tell the current implementation relies on hardcoded instance types which is really not good and ideally should be retrieved from the API. This goes for the “pricing” logic as well. Hardcoded plan types also does not allow support for custom/workload optimized plan types.

**Describe the solution you'd like.**:

Ability to deploy newer / all instance types available on the API for a user.
**Describe any alternative solutions you've considered.**:

None are possible.

**Comment by displague** [comment]
@enkelprifti98 m3.small is included in the hardcoded plans list, since 1.29 (perhaps earlier).

https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/equinixmetal/price_model.go#L45

I agree that the static list is problematic and plans should be fetched from the API since the pricing values may change overtime. Another consideration is that prices are based on metro which is not reflected in the autoscaler today.
