### ISSUE TITLE
Merge addon-resizer 1.8 into master

### ISSUE THREAD

**Issue by kwiesmueller** [kubernetes/autoscaler#5876]
**Which component are you using?**:

addon-resizer

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

Addon-resizer in the `master` branch doesn't seem actively maintained and is outdated with a lot of outdated dependencies (vulnerabilities).
We seem to only maintain the 1.8 branch and it's not intuitive for newcomers to find that.

It also seems like CI is not correctly triggering on the branch resulting in `/test all` to skip because it doesn't find any tests.

**Describe the solution you'd like.**:

I'd propose merging the 1.8 branch into `master` or replacing addon-resizer in `master` with the contents of 1.8.

**Describe any alternative solutions you've considered.**:

Leave it be. This should only be an option if the current version in `master` is actively and heavily used.

**Additional context.**:

I'm looking for input on reasons to keep 1.8 separate. Are there significant differences between the versions and do we need to keep the current head? If so, are we okay with keeping a component that's on a very old version of Godeps and has vulnerabilities? Should we update it instead?

**Comment by jbartosik** [comment]
There are significant differences between 1.8 and 2.x Addon Resizer branches. The last common commit between them is e1eda785ab712823a4aad371c54e9cb71a1fef50[1]. Looking at what happened on the [master](https://github.com/kubernetes/autoscaler/commits/master?after=b91b1271ad3a55dd44eae894b816359d8cbf4a48+34&branch=master&path%5B%5D=addon-resizer&qualified_name=refs%2Fheads%2Fmaster) branch since then I find at least #128 which is a "rewrite" (in June 2017), comments say it's a significant change. It also changes version to 2.0 and has a linked [design doc](https://docs.google.com/a/google.com/document/d/1T0A7GHwNU_w6gpq_eCN166aRth6usbRvxgJJqSZeESU/edit?usp=sharing).

I don't know about people using 2.x addon resizer and I know for example [metrics server](https://github.com/kubernetes-sigs/metrics-server/blob/2d055fb6d88e3c9b1d25ce94f9d6b387732eda9f/manifests/components/autoscale/patch.yaml#L16) still uses 1.8. But I think images od addon resizer 2.x are available so someone might be using them. On the other hand we definitely didn't release 2.x images in a long time so it's probably better to clearly tell people they're deprecated.

I think it's a good idea to bring master branch of addon resizer to such state that we release it from master. I agree current state is confusing. Also addon resizer isn't actively developed.


[1] 

```
$ git merge-base upstream/addon-resizer-release-1.8 upstream/master
e1eda785ab712823a4aad371c54e9cb71a1fef50
```

**Comment by jbartosik** [comment]
Also PRs are not labeled when they go to addon resizer 1.8 branch, I noticed when I had to label  #5682 manually (though this is presumably easy to fix)
