### ISSUE TITLE
VPA: export recommendations

### ISSUE THREAD

**Issue by yuzhouliu9** [kubernetes/autoscaler#5957]
**Which component are you using?**:
VPA

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:
The VPA recommender has a flag [memory-saver](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/FAQ.md#what-are-the-parameters-to-vpa-recommender) which by default is `false`, meaning it tracks all pods even if they don't have an associated VPA object.
For pods tracked by a VPA object, we can run `kubectl describe vpa ...` to get the recommended values.

Is there a way to get the recommended values for pods not associated with a VPA object?
If not, then why track all pods at all?

**Describe the solution you'd like.**:
Ability to export the recommended resource values for all pods tracked by VPA recommender.
Add documentation around this.

Or if this feature is rejected, add documentation to clearly explain there is no way to get recommended values for pods without an associated VPA.

**Describe any alternative solutions you've considered.**:
Prometheus metrics from cAdvisor for running containers.

**Comment by voelzmo** [comment]
> If not, then why track all pods at all?

I think this is an optimization for environments in which people create VPA objects after their workload has been running a while (e.g. a few days or longer). If the recommender tracked them already (default behavior), it stored all the historic usage samples just like for Pods which have a matching VPA.
In this case, the recommendation you get is quite accurate from the start, because it is informed by the already stored usage samples.

Contrast this with memory-saver mode, where the recommender throws away the usage samples for Pods which currently don't have a matching VPA, so once a VPA object is created, you only get recommendations with a low accuracy/confidence. It will take a while (read: days) to get recommendations with the same accuracy as in the default scenario.

All of this is just the recommender's in-memory state, so this assumes the recommender is not disrupted during this period. As you already figured out, there is no way to access this in-memory state and get a recommendation for Pods without a matching VPA.

**Comment by yuzhouliu9** [comment]
Gotcha, thanks for the detailed clarification.

I'll close this. But one suggestion would be to clarify in vpa docs that
> there is no way to access this in-memory state and get a recommendation for Pods without a matching VPA

Maybe I missed it.
