### ISSUE TITLE
Scaled up twice due to pods become RUNNING need some time.

### ISSUE THREAD

**Issue by resouer** [kubernetes/autoscaler#687]
Here's a issue when I using with cluster-autoscaler.

```bash
I0227 19:21:19.864441   22817 static_autoscaler.go:258] Filtering out schedulables
I0227 19:21:19.864711   22817 static_autoscaler.go:268] No schedulable pods
I0227 19:21:19.864748   22817 scale_up.go:56] Pod default/nginx-deployment-54dc474b5-6tvzx is unschedulable
I0227 19:21:19.864766   22817 scale_up.go:56] Pod default/nginx-deployment-54dc474b5-llwv9 is unschedulable
I0227 19:21:20.043259   22817 scale_up.go:88] Upcoming 0 nodes
I0227 19:21:20.123901   22817 scale_up.go:195] Best option to resize: dlws-worker-asg
I0227 19:21:20.123936   22817 scale_up.go:199] Estimated 1 nodes needed in dlws-worker-asg
I0227 19:21:20.205062   22817 scale_up.go:288] Final scale-up plan: [{dlws-worker-asg 2->3 (max: 10)}]
I0227 19:21:20.205132   22817 scale_up.go:340] Scale-up: setting group dlws-worker-asg size to 3
...
I0227 19:32:37.019279   22817 metrics.go:248] Function scaleUp took 11m17.154526618s to complete
I0227 19:32:37.174294   22817 metrics.go:248] Function main took 11m17.464380135s to complete
I0227 19:32:47.174453   22817 static_autoscaler.go:108] Starting main loop
I0227 19:32:47.329947   22817 clusterstate.go:191] Scale up in group dlws-worker-asg finished successfully in 10.309260066s
I0227 19:32:47.330025   22817 utils.go:435] No pod using affinity / antiaffinity found in cluster, disabling affinity predicate for this loop
I0227 19:32:47.330048   22817 static_autoscaler.go:258] Filtering out schedulables
I0227 19:32:47.330332   22817 static_autoscaler.go:268] No schedulable pods
I0227 19:32:47.330363   22817 scale_up.go:56] Pod default/nginx-deployment-54dc474b5-6tvzx is unschedulable
I0227 19:32:47.330381   22817 scale_up.go:56] Pod default/nginx-deployment-54dc474b5-llwv9 is unschedulable
I0227 19:32:47.496404   22817 scale_up.go:88] Upcoming 0 nodes
I0227 19:32:47.577254   22817 scale_up.go:195] Best option to resize: dlws-worker-asg
I0227 19:32:47.577279   22817 scale_up.go:199] Estimated 1 nodes needed in dlws-worker-asg
I0227 19:32:47.657121   22817 scale_up.go:288] Final scale-up plan: [{dlws-worker-asg 3->4 (max: 10)}]
I0227 19:32:47.657157   22817 scale_up.go:340] Scale-up: setting group dlws-worker-asg size to 4
...
```
**My understanding is:**
It seems that cluster-autoscaler will report scale up success when the node is ready. But in this issue, it actually took some time for my Pending pods become Running, and this triggered another scale up.
If it's the case, we should give a "cool down" time for recently scaled up cluster, or use pod status change as a flag. Feel free to correct me if I'm wrong.

**Test env**
```
Kubernetes v1.9.0

./cluster-autoscaler --v=4 --stderrthreshold=error --logtostderr=true --cloud-provider=mytools --skip-nodes-with-local-storage=false --nodes=1:10:dlws-worker-asg --leader-elect=false --scale-down-enabled=false --kubeconfig=./deploy/kubeconfig.yaml
```

btw, I am using my own "Cloud Provider" which is for bare metal cluster (autoprovisioning == false), but this should be unrelated.

Any ideas?

**Comment by MaciekPytel** [comment]
Instead of having cooldown period CA predicts which pods could be scheduled on existing or booting up nodes and accounts for it in its scale-up calculations. There are 2 separate pieces of logic:
 - Nodes that are booting up are taken into account during binpacking part of CA algorithm. Immediately after scale-up you should see `Upcoming X nodes` lines in log, where X is the number of nodes booting up.
- Pods that can fit on existing, ready node are removed from unschedulable pods list and not taken into account in scale-up consideration. Each such pod would be listed in log immediately following `Filtering out schedulables` line, if no pods were filtered out it would instead follow with `No schedulable pods`.

Those are critical and very well tested parts of CA logic, so I think it's more likely this is related to your cloudprovider. Two potential problems that come to my mind immediately:
1. If it logs `Upcoming 0 nodes` even immediately after scale-up your TargetSize implementation probably returns actual number of nodes and not desired number of nodes.
2. If you never see any pods filtered out as schedulable and new scale-up is triggered immediately after nodes register in kubernetes (first loop which logs `Upcoming 0 nodes` after a bunch of loops with `Upcoming X nodes`), that probably means there is a difference between how CA predicts the node will look like and how the node actually looks like. This is quite likely in scale-from-0 scenarios, but otherwise should only happen if nodes in a single node group are not identical.

**Comment by resouer** [comment]
@MaciekPytel Thanks for detailed explanation! `Upcoming 0 nodes` should be the problem in my case as all nodes are identical in the node group. I will take a quick look at my implementation and feedback here.

**Comment by resouer** [comment]
@MaciekPytel Thanks! The issue is fixed by return targetSize as you suggested.

I can see the `Upcoming 1 nodes` now:
```
I0301 21:43:30.005433   15571 static_autoscaler.go:268] No schedulable pods
I0301 21:43:30.005470   15571 scale_up.go:56] Pod default/nginx-deployment-54dc474b5-g2zxg is unschedulable
I0301 21:43:30.005484   15571 scale_up.go:56] Pod default/nginx-deployment-54dc474b5-skkgs is unschedulable
I0301 21:43:30.162329   15571 scale_up.go:88] Upcoming 1 nodes
I0301 21:43:30.162496   15571 scale_up.go:174] No need for any nodes in dlws-worker-asg
I0301 21:43:30.162534   15571 scale_up.go:182] No expansion options
```
And followed by  Schedulable pods present later:
```
I0301 21:44:41.693364   15571 utils.go:129] Pod nginx-deployment-54dc474b5-g2zxg marked as unschedulable can be scheduled on harrydevbox-worker03. Ignoring in scale up.
I0301 21:44:41.693530   15571 utils.go:124] Pod nginx-deployment-54dc474b5-skkgs marked as unschedulable can be scheduled (based on simulation run for other pod owned by the same controller). Ignoring in scale up.
I0301 21:44:41.693562   15571 static_autoscaler.go:265] Schedulable pods present
```

Thank you!

**Comment by SouhailAssal2** [comment]
@resouer I have the same issue that you had here, the only difference is that I'm using aws as a cloud provider, Is there a way to fix the targetSize in this case? @MaciekPytel do you have any ideas about this?
