### ISSUE TITLE
[Documentation] Question regarding Vertical Pod Autoscalar's compatibility with Kubernetes

### ISSUE THREAD

**Issue by mooneeb** [kubernetes/autoscaler#6881]
Hello.

While going through the VPA [Readme.md](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/README.md), I noticed that in a recent [commit](https://github.com/kubernetes/autoscaler/commit/9a48d7be0565565d8de7dc87d8fa65fb1073ca38) the VPA - K8s [compatibility matrix](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/README.md) was updated to specifically show the compatibility for v1.1.1 with k8s v1.25.

I just wanted to clarify if there's any reasoning behind this change? Or do VPA `v1.1.0` and `v1.1.2` have different K8s version compatibilities? 

Thank you :)

**Comment by adrianmoisey** [comment]
May be @voelzmo can answer better than I can, but, 1.1.0 had a null pointer exception bug which is fixed in 1.1.1.
I assume that's why the docs were updated, to try discourage use of 1.1.0.

Regarding compatibility, 1.1.1 and 1.1.2 aren't any more or less compatible with Kubernetes versions than 1.1.0 to my understanding.

**Comment by voelzmo** [comment]
Right, patch versions just contain fixes, no changes in behavior. The change was just done to make sure that people don't use version `1.1.0`, as it has issues which were fixed in the following patch releases.

/close
/kind support
