### ISSUE TITLE
Node count metrics do not contain node group names

### ISSUE THREAD

**Issue by jpds** [kubernetes/autoscaler#778]
Under metric keys such as: `cluster_autoscaler_scaled_up_nodes_total`, `cluster_autoscaler_nodes_count`, `cluster_autoscaler_unneeded_nodes_count` - I do not see anything about which group name the nodes belonged too.

I would like to know which group cluster-autoscaler decided to scale up or down at a particular moment in time for example, right now I only have the totals in my metrics dashboards. Another example of this is that `cluster_autoscaler_nodes_count` also happens to include the masters, which I know will probably always be `3`, but I can't drill down to a non-master number.

**Comment by aleksandra-malinowska** [comment]
I don't think we want to attach any cluster-specific names to metrics. As for the number of master nodes, this would be probably easy to add. Would you be interested in contributing to this?

**Comment by aleksandra-malinowska** [comment]
> why not add a label for the group name? it would make these metrics much more useful

Sorry for late response. The reason is increased cardinality. If we add this feature, we should probably hide it behind a flag (disabled by default.)

**Comment by frittentheke** [comment]
@aleksandra-malinowska First of all, great work with providing such cool metrics. Especially when using magic tools like cluster-autoscalers, one needs to have those insights.

I just ran into the  <s>issue</s>  fact of the master nodes being counted in values like _cluster_autoscaler_nodes_count_ myself. I really believe counting the masters with a dedicated value to allow distinquishing between masters and nodes is the besster way to do it.

I'd also really like to ask you to reconsider adding more labels to the metrics and provide your metrics per ASG. In case there is only one ASG for the nodes, there will be no real change. But when running multiple ASGs for your nodes you really need to know how and which ASG was scaled in which way.

Also I know that one should avoid using label for high cardinality (https://github.com/prometheus/docs/blob/master/content/docs/practices/naming.md#labels) and that point is still valid even with Prometheus 2.x scaling much much higher in regard to number of time-series / series-churn (https://coreos.com/blog/prometheus-2.0-storage-layer-optimization).

But just having "a few more" labels for disinquish between different groups of resources being managed is likely not an issue at all. With all sorts of movement in regards to pods and deployments there are so many time-series created due to label changes, the few more the cluster-autoscaler would add when providing per ASG and per node-type metrics would not even be noticed - but again, be very very helpful.

Prometheus 2.x has no problem with AT log of

**Comment by MaciekPytel** [comment]
A few more label values is not a problem. Cardinality really becomes a problem when you try to aggregate metrics over hundreds or thousands of clusters - adding any cluster specific identifiers as label values effectively removes that option. I don't mind distinguishing master/non-master or other labels with a logical, predefined set of values, but I'd like to avoid using identifiers as label values.

**Comment by aleksandra-malinowska** [comment]
> First of all, great work with providing such cool metrics. Especially when using magic tools like cluster-autoscalers, one needs to have those insights.

Actually, it's @MaciekPytel who added those metrics in the first place. Thank him!

An alternative to get such detailed information may be to watch a stream of Kubernetes events published by Cluster Autoscaler. There should be events published for each scale-up, whether successful or failed, published for its ConfigMap object (since a node group itself isn't a Kubernetes concept): https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/core/scale_up.go#L585

**Comment by frittentheke** [comment]
@MaciekPytel thanks for the rapid feedback. Certainly any way to distinguish nodes and master, be it a label or a dedicated value, would be great - I was not implying labels but rather asking for the split in general ;-)

Regarding per ASG metrics - those I really believe would help tremendously as well to be available.

**Comment by monolithh** [comment]
Are there any chances to get ASG name in metrics? It is really helpful information

**Comment by frittentheke** [comment]
@MaciekPytel  any chance we could get this issue reopened?

**Comment by richerve** [comment]
I'm also interested on this and the information is already collected by cluster-autoscaler so can't understand why not publishing it. Having them behind a feature flag is fair enough I think.

My use case is having min, max and current values per "scaling group" (NodeGroup) to help in building prometheus queries and dashboards around that. Another way would be instrumenting an external service to query the ASG api (in case of AWS), but will be fetching essentially the same information as cluster-autoscaler, so don't see the need for that.

If it's of intererest I can open a PR to include metrics for the exposed methods in the NodeGroup interface

**Comment by xgengsjc2021** [comment]
Any progress/update on this one? Metrics with node group name will be really helpful.

**Comment by luisdavim** [comment]
Should this issue be reopened?
