### ISSUE TITLE
Account for AWS instance limit (or any limit in the number of instances)

### ISSUE THREAD

**Issue by dobesv** [kubernetes/autoscaler#799]
I hit the limit on the maximum number of instances globally on the AWS account.  I was thinking it would be nice if cluster-autoscaler would somehow have an algorithm that works within a maximum number of nodes and somehow "merges" nodes into larger instances to reduce fragmentation as demand increases.

**Comment by aleksandra-malinowska** [comment]
This would be a big change to Cluster Autoscaler. Bin-packing complexity aside, there are other open-ended questions. For example, to avoid disrupting workloads, new nodes should be created first, so that pods from deleted nodes can be rescheduled immediately. But in your case, it wouldn't be possible due to quota, so either some nodes would have to be deleted before creating new ones, or we'd have to settle for avoiding hitting quota for as long as possible. What would be the expected behavior? Speaking of quotas, I wonder if CA should be aware of them, especially as it gets cloud-provider-specific (per project/account.) There's also a matter of redundancy - we don't necessarily want to "optimize" a small cluster to run on a single machine of the largest possible type. That's just a handful of thoughts - I'd be interested to hear yours!

**Comment by dobesv** [comment]
As I've thought of this I think it might be too much to take on right now.  Better to just request a larger limit from AWS when the time comes.
