### ISSUE TITLE
Spare nodes to schedule pods during deployment

### ISSUE THREAD

**Issue by thomaschaaf** [kubernetes/autoscaler#908]
The cluster autoscaler currently works very efficiently for us and it is always utilizing the machines to their full capacity. However this is currently slowing down our deployments if the cluster does not have enough spare capacity to allow scheduling of the pods during a deployment we have to wait 5 minutes for the nodes to come up to be able to schedule the new pods.

Is there an option to always have a spare node ready to allow pods to schedule faster?

**Comment by MaciekPytel** [comment]
There is no such feature in Cluster Autoscaler (there were multiple attempts to implement it, but it turned out it's very hard). Currently we recommend using scheduler priority and preemption to get this, as described in our FAQ: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-configure-overprovisioning-with-cluster-autoscaler.
